feat(politics-tracker): add GA initialize & click event
readr-media/Sachiel pull request #250
Opened 2022-11-17 09:18 UTC by ChangRongXuan

1. `index.jsx` 更動： 從`/constants/config`取得`gaTrackingId`，並建立ReactGA.initialize() & ReactGA.pageview()。
2. 其他檔案 更動：import `react-ga` module，建立不同label的`ReactGA.event`function ＆ 加入onClick事件。

2022-11-17 13:32 UTC, erase2004 requested changes
`ReactGA.initialize(gaTrackingId)` 應該在每個使用的元件上都需要被執行，
因此，與其在每個元件上都補上這一段，不如現在 `utils` 底下先初始化，
然後在匯出初始化後的 instance，使用到的元件再去 import 這個 instance 來使用

可以留意 console 和 network 來確定是不是 ga event 是不是有正確執行
![Snipaste_2022-11-17_21-08-49](https://user-images.githubusercontent.com/1367757/202459787-8dcff661-6e3b-457b-8a52-c90e41547c7b.png)

2022-11-17 13:32 UTC, erase2004 commented on packages/politics-tracker/components/politics/section-toggle.tsx
> +const handlePoliticListOnclick = () => {
這應該只有觸發在第一個選舉之外的按鈕被展開時，才需要送出？

2022-11-18 01:23 UTC, ChangRongXuan commented
更新：

1. `section-toggle.tsx` ：新增GA click function 執行條件 => 將 props.order, props.isActive 傳入 `handlePoliticListOnclick` function，只有當 order !== 0 且 isActive === false 時才會執行，以符合「點擊展開其他選舉欄」的使用情境。

2. 初始化 `ReactGA.initialize`：

    - 目前參考[React-ga官方文件](https://github.com/vercel/next.js/tree/canary/examples/with-react-ga)，新增 `utils/analytics.ts`，將ReactGA.initialize & ReactGA.pageview 改設定於`analytics.ts`中。
    - 同時於`pages/_app.tsx` import進`analytics.ts`，執行 `initGA, logPageView`。

2022-11-18 03:58 UTC, ChangRongXuan commented on packages/politics-tracker/components/nav.tsx
> +  if (prev === '回政見總覽' || prev === '回首頁' || prev === '回個人資訊') {
想確認這部分的修改方向是指：
1) 將 `prev.href.pathname` 作為props傳入 `handlePreviousClick` function內
2) 在 `handlePreviousClick()` 內建立一個Array ( `value`='GA label',  `index`='prev.href.pathname' ) ，然後去條件判定 click 後要顯示哪些對應的 label 值嗎？

2022-11-18 10:58 UTC, ChangRongXuan commented
調整：

1. `utils/analytics.ts`：export`logGAEvent`function，讓不同元件可直接取用該function。function參數包含：

- category：在此專案中固定為 'Projects_PoliticsTracker'。
- action：傳入click.scroll...等event。
- label：傳入對應的GA文字敘述標籤。

2. 調整：`pages`的 `/person/[id].js` & `/politics/detail/[politicId].js` 

    調整上述頁面 `navProps` 中的 href 設定。調整 href 中關於 `pathname` 和 `query` 的設定 (之前僅有處理pathname) ，以利其他元件做後續處理。
    
3. `components/nav.tsx`：新增 `GALabelMap`，存放不同GA click的相應資訊，並透過 `GALabelMap[props.prev.href.pathname]`  取得不同頁面觸發nav event對應的GA label資訊。


4. 其他：調整 `政見總覽頁` 元件

    從原先 import `React-ga` module，改為統一使用 `utils/analytics.ts`中的`logGAEvent`來處理 GA click event。

2022-11-19 07:55 UTC, erase2004 requested changes
目前因為 function 定義或呼叫方式錯誤，導致傳到 GA 參數的內容是有問題的 (ec, ea, el)
![Snipaste_2022-11-19_15-19-08](https://user-images.githubusercontent.com/1367757/202840973-4f99ca61-1c6c-4f48-9d82-93c44b35381a.png)

ec, ea, el 的意義可以參閱文件：
[Measurement Protocol 參數參考資料](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters)

2022-11-19 07:55 UTC, erase2004 commented on packages/politics-tracker/components/nav.tsx
> +                !(
其實只要
```javascript
if (props.prev === undefined ||
  typeof props.prev !== 'object' ||
  typeof props.prev?.href !== 'object'
) {
  return
} else {
  return logGAEvent(...)
}
```
這樣進行下述操作時
```javascript
GALabelMap[props.prev.href.pathname]
```
型別判斷上就會合理了，

現在弄出來的條件，理解上不是那麼直觀

2022-11-19 07:55 UTC, erase2004 commented on packages/politics-tracker/components/politics/section-toggle.tsx
> +  order: any
按照上層 (`SectionList`) 傳入的 `props`，這裡應該沒有理由使用 `any`，實際上是 `number`

2022-11-19 07:55 UTC, erase2004 commented on packages/politics-tracker/utils/analytics.ts
> +export const logGAEvent = (
如果 function 的參數為 optional 的情況下，應當將 optional 的參數放在後面的位置，
例如：
```javascript
func test(a = 1, b, c) {
  return a + b + c
}

test(2, 3)
```
在這情況下，`test` 裡面的 a,  b, c 數值分別是 2, 3, undefined，而不是 1, 2, 3
或者用
```javascript
func test({a =1, b, c}) {
  return a + b + c
}

test({b: 2, c: 3})
```
的形式

參閱：
* [Default parameters | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)
* [Destructuring assignment](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

2022-11-20 09:30 UTC, ChangRongXuan commented on packages/politics-tracker/utils/analytics.ts
> +export const logGAEvent = (
了解，謝謝指正！

目前已將 `utils/analytics.ts` 的logGAEvent 調整為：
 ```
export const logGAEvent = (action = '', label = '') => {
  if (action) {
    ReactGA.event({
      action,
      label,
      category: 'Projects_PoliticsTracker',
    })
  }
}
```

1) 從原本 export `action/label/category` 三個參數，改為 export `action/label`，在不同元件使用 `logGAEvent` 時，在呼叫時僅需帶入該事件對應的數值。ex: logGAEvent ( '`action事件名稱`', '`label內容`' ) 。

2) 預設`category`值：此專案因 `category`值固定為 'Projects_PoliticsTracker'，調整後會將此預設值改放置於 `ReactGA.event({....., category: 'Projects_PoliticsTracker')}`，呼叫function時僅需提供 `action/label`，`category`值會統一在utils進行處理。

3) 在調整 `logGAEvent` function後，傳到 GA 參數問題已解決。（ ec =>對應`category` ; ea =>對應`action`, el =>對應`label`)

2022-11-20 09:37 UTC, ChangRongXuan commented on packages/politics-tracker/components/nav.tsx
> +                !(
了解，目前修正為：
```
if (props.prev === undefined ||
  typeof props.prev !== 'object' ||
  typeof props.prev?.href !== 'object' ||
  !props.prev.href.pathname
) {
  return
} else {
  return logGAEvent(...)
}
```

有在if判斷中多加入`!props.prev.href.pathname`條件，用以防止`props.prev.href.pathname===null` 或 `props.prev.href.pathname===undefined`的狀況發生。 ( 如pathname為null/undefined，會有typescript error)

2022-11-20 14:13 UTC, erase2004 approved these changes
LGTM 👏 🎉

2022-11-20 14:13 UTC, erase2004 commented on packages/politics-tracker/utils/analytics.ts
> +export const logGAEvent = (action = '', label = '') => {
GA 的 `category` 是作為群組管理使用，未來或許會作為傳入參數使用，因此未必會固定為 `Projects_PoliticsTracker`

2022-11-20 14:53 UTC, ChangRongXuan commented on packages/politics-tracker/utils/analytics.ts
> +export const logGAEvent = (action = '', label = '') => {
了解，如果方便的話想請教：如果將`category`重新設為function參數，在未來使用/維護上會不會比較方便呢？( 調整後的影響是在元件呼叫`logGAEvent`上，都會需要多帶入 `Projects_PoliticsTracker` 此一參數值。 
```
export const logGAEvent = (action = '', label = '', category = '') => {
  if (action) {
    ReactGA.event({
      action,
      label,
      category,
    })
  }
}
```

2022-11-21 00:59 UTC, merged