feat(about): add landing of about
readr-media/Sachiel pull request #303
Opened 2023-03-09 17:54 UTC by v61265

### 描述
- 新增 `about` 頁面的 landing。
- 包含可以選擇語言，並且根據語言選擇顯示內容。
- 使用說明：將設計稿上黃色的部分用 `<b>` tag 標記起來，中文的話整塊標即可，英文部份考慮換段需求，請一個單字一個單字標。（例如：`<b>this</b> <b>is</b> <b>a</b> <b>book.</b>`)
- 字串處理原則：先經過 `parsedContent()` 將字串切分成一個字母一個 element，之後更改 state `contentHtml`，並由 `decodeText()` 開始更改 elements 的 className，達成設計稿上預期的動畫效果。

### 參考資料
- 設計稿：https://www.figma.com/file/RfJHjsr8rBa7iIC7ir41AZ/2021_READr_Website?node-id=3360-21686&t=I7ZmiFsdRAogQS0B-0
- 動畫參考：https://codepen.io/BRacicot/pen/Nryjpa

2023-03-10 04:35 UTC, erase2004 requested changes
幾個問題與建議：
1. 在頁面高度不夠的情況下，語系切換會和文字重疊
![Snipaste_2023-03-10_11-14-53](https://user-images.githubusercontent.com/1367757/224223336-3229cbdc-831d-448b-89a3-48ee091706c5.png)

2. 結構上，建議可以改用 section + h2 或者 sectoion + div(role="heading" aria-level="2")
![Snipaste_2023-03-10_11-16-46](https://user-images.githubusercontent.com/1367757/224223559-b6eee599-0983-4736-897a-d7e25e4e19ca.png)

3. ESLint 的 `react-hooks/exhaustive-deps` 有時候會給出錯誤的提示，其實應該不需要那麼多 useCallback，畢竟這些 function 都沒有成為 child component 的 props，而且使用 useCallback, useMemo 這類效能影響的 hook，有初次載入時間增加的副作用，使用 useCallback/useMemo 沒有提昇效能，反而反最佳化的情況也是有可能的
目前有觀察到明顯的問題是：一次的 contentHtml 更新，parsedContent 卻跑了 2 次 (dev 環境會是 4 次)，而且第二次的執行並沒有改變輸出，只是浪費計算。

我的調整供參：
[landing.tsx.patch](https://github.com/readr-media/Sachiel/files/10938526/landing.tsx.patch)

2023-03-10 04:35 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +import { Language } from '~/types/about'
使用 import type 明確標示 import 內容是 type

2023-03-10 04:35 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +    landing: {
landing 的內容如果在不同 langugage key 底下都一樣的話，可以考慮抽出來成獨立的 type，
這樣的話，就可以使用 `type Wording = Record<Language, [Another Type]>` 來表示
Ref: https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type)

2023-03-10 04:35 UTC, erase2004 commented on packages/readr/components/about/landing.tsx
> +import { Language } from '~/types/about'
使用 import type 明確標示 import 內容是 type

2023-03-10 04:35 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +const wording: Wording = {
註解一下內容使用 `<b>` 的用意

2023-03-10 04:35 UTC, erase2004 commented on packages/readr/components/about/landing.tsx
> +  z-index: 1;
不太清楚這裡使用 z-index 的必要性，這幾組 z-index 移除並不影響結果的樣子，如果可以的話，盡量避免使用 z-index

2023-03-20 07:10 UTC, v61265 commented on packages/readr/pages/about.tsx
> +const wording: Wording = {
感謝提醒，已於 [f930d74](https://github.com/readr-media/Sachiel/pull/303/commits/f930d74d8c5f613aaf76588383473b07ef7b50cc) 補充。

2023-03-20 07:11 UTC, v61265 commented on packages/readr/pages/about.tsx
> +    landing: {
感謝提醒，已於 [02b985e](https://github.com/readr-media/Sachiel/pull/303/commits/02b985e5c2322baae42f6a680213b55b0b7e5dd3) 補上。

2023-03-20 07:15 UTC, v61265 commented on packages/readr/components/about/landing.tsx
> +  z-index: 1;
這是為了防止背景的線條擋住字，為了讓使用者更方便像是一般文章段落選取內容，才想說用 z-index 移到前面。不過剛骯實測後發現加錯位置，已於 [3278e5a](https://github.com/readr-media/Sachiel/pull/303/commits/3278e5a7fdd66549272811421711c6f81fcf729d) 調整，還是有更建議的寫法呢？

2023-03-20 07:47 UTC, v61265 commented
> 螢幕高度過小會重疊問題

感謝提醒，已於 [6a7665c](https://github.com/readr-media/Sachiel/pull/303/commits/6a7665c0650f15a637993fe6cea20e10baba0921) 調整，

> ESLint 的 react-hooks/exhaustive-deps 有時候會給出錯誤的提示，其實應該不需要那麼多 useCallback，畢竟這些 function 都沒有成為 child component 的 props，而且使用 useCallback, useMemo 這類效能影響的 hook，有初次載入時間增加的副作用，使用 useCallback/useMemo 沒有提昇效能，反而反最佳化的情況也是有可能的
目前有觀察到明顯的問題是：一次的 contentHtml 更新，parsedContent 卻跑了 2 次 (dev 環境會是 4 次)，而且第二次的執行並沒有改變輸出，只是浪費計算。

原來如此，學到很多，感謝🙏
目前已於 [24eb06e](https://github.com/readr-media/Sachiel/pull/303/commits/24eb06eed50a4b229babb03cdbb79173cff4d8ed) 調整。

2023-03-20 08:25 UTC, erase2004 requested changes
觀察到問題 1 尚未被解決

2023-03-21 04:59 UTC, v61265 commented
拍謝沒注意到，已於 [9de2b50](https://github.com/readr-media/Sachiel/pull/303/commits/9de2b502f5bf95dd0acbdb766e7f9b2f4b447686) 調整！

2023-03-21 05:41 UTC, erase2004 approved these changes
LGTM 👏 

順道一提，裡面 `1096px` 的數字，應該可以考慮用 `styles/theme/index.ts` 中，width/main 的資訊來做取代，邏輯上應該是共通，可以統一管理。

2023-03-21 05:59 UTC, merged