fix(readr/post): update external link with `constants` & adjust filtering criteria.
readr-media/Sachiel pull request #307
Opened 2023-03-15 03:09 UTC by ChangRongXuan

### 調整
- 更新贊助按鈕連結為 `DONATION_PAGE_URL` 。
- 新增相關報導連結資訊（使用 `SITE_URL` ）。
- 修復 `media-link.tsx` 內的連結複製功能，且改為 `window.location.href`。
- `graphql/query/post.ts` 的 `relatedPosts` 新增 `heroImage` 相關設定。

### 更新
- `@readr-media/react-component` 使用版本升至 `1.0.2-alfa.2`

2023-03-16 06:37 UTC, erase2004 commented on packages/readr/components/post/post-credit.tsx
> +        {Number(writers?.length) > 0 && (
請問是遇上什麼情況，所以調整為這樣子？

2023-03-16 06:37 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
> +            defaultImage={'/icons/default/post.svg'}
應該可以改用 `/constants/constants` 中的 `DEFAULT_POST_IMAGE_PATH`

2023-03-16 06:37 UTC, erase2004 commented on packages/readr/package.json
> +    "@readr-media/react-component": "^1.0.2-alfa.2",
`alfa` 應該是 `alpha`，不過這問題在 package 那邊，所以僅做提醒

2023-03-16 06:37 UTC, erase2004 commented on packages/readr/graphql/query/post.ts
> +        heroImage {
GraphQL 結構改變，輸出的 `PostDetail` 內容也需要更新，另外，看到 `/components/post/report` 中有使用 `RelatedPost` type，或許可以在此檔案中 export `RelatedPost` type 去讓 `/components/post/report`

2023-03-16 06:47 UTC, erase2004 requested changes

2023-03-16 06:47 UTC, erase2004 commented on packages/readr/components/post/report.tsx
> +      {Array.isArray(relatedData) && relatedData.length && (
`&& relatedData.length &&` 調整為 `&& relatedData.length > 0 &&` 會比較好

2023-03-16 06:47 UTC, erase2004 commented on packages/readr/components/post/report.tsx
> +    link: `http://${SITE_URL}/post/${item.id}`,
應該有 http 和 https 的差別

2023-03-17 04:52 UTC, ChangRongXuan commented on packages/readr/components/post/post-credit.tsx
> +        {Number(writers?.length) > 0 && (
`writers`、`designers`、`dataAnalysts` 如無資料的話皆為 empty array，
`Boolean([])` 為 true，因此判斷原先透過 `writers` 布林值進行是否顯示的判定無意義，因此移除。

修改為 `Number(writers?.length) > 0`，是之前 code-review 看到類似寫法，
想說加上 Number( ) 後在針對 `.length` 的判定上會較為嚴謹，因此在這次修改一併補上。

2023-03-17 05:09 UTC, ChangRongXuan commented on packages/readr/package.json
> +    "@readr-media/react-component": "^1.0.2-alfa.2",
感謝提醒，已修正為 `@readr-media/react-component": "^1.0.2-alpha.6"`

2023-03-17 05:35 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
> +    link: `http://${SITE_URL}/post/${item.id}`,
感謝指正 :raised_hands:  目前修正是透過 `useEffect` 取得 `window.location.protocol` 為 http / https。

備註：也有看到透過 `useRouter` 取得 protocol 的寫法，但評估後（閱讀上比較不好理解？:thinking:）以 useEffect 寫法作修改。
```
import { useRouter } from 'next/router';
....
const router = useRouter();
const protocol = router?.req?.headers?.referer?.split(':')[0] || 'http';
```

2023-03-17 08:56 UTC, ChangRongXuan commented
### 更新
- 更新 `@readr-media/react-component` 版本為：1.0.2-alpha.6。

### 修正
- 透過 `window.location.protocol` 判斷 http/https。
- 修正條件判斷： `relatedData.length > 0` 
- 更新 `/query/post` ：新增 "heroImage" 於 `RelatedPost` type。
- `/components/post/report` 中的 `RelatedPost` type 改為透過 import `query/post` 作設定。
- 預設圖片改為：`DEFAULT_POST_IMAGE_PATH`。

2023-03-19 13:57 UTC, erase2004 requested changes

2023-03-19 13:57 UTC, erase2004 commented on packages/readr/graphql/query/post.ts
> +  'id' | 'publishTime' | 'name' | 'readingTime' | 'heroImage'
`heroImage` 的 type 為 `GenericPhoto`，這會導致 `GenericPhoto` 變動時，`heroImage` type 的內涵也跟著一起變動，然而實際的 gql 其實沒有變動，進而產生 type 與 gql 沒有 match 的結果。
可以參考 `PostDetail` 的情況，在 `PostDeatil` type 的 `heroImage` 的 type 為 `Photo`，而 `Photo` 是經過處理，為 `GenericPhoto` 的 subset，並且一定程度上不受到 `GenericPhoto` 的改變影響。
現在應該有 `Override` 方法，也可以考慮用 `Override` 的方式來處理。

2023-03-19 13:57 UTC, erase2004 commented on packages/readr/components/post/post-credit.tsx
> +        {Number(writers?.length) > 0 && (
`Number()` 的作用不是判斷，是型別轉換，然後，觀察 writers, designers 和 dataAnalysts  的資料來源 `renderNames`，輸出 type 為 `JSX.Element[]`，那其實用 `writers.length > 0` 應該就夠用了，除非上游來源的 type `PostDetail` 的內容有寫錯，導致實際執行時出錯，如果是這樣的話，應該從 `PostDetail` 去做修正。

2023-03-20 14:50 UTC, ChangRongXuan commented on packages/readr/graphql/query/post.ts
> +  'id' | 'publishTime' | 'name' | 'readingTime' | 'heroImage'
了解，已修正為：
```
export type RelatedPost = Pick<
  Required<GenericPost>,
  'id' | 'publishTime' | 'name' | 'readingTime'
> & {
  heroImage: Photo
}
```

修正 `RelatedPost` 內的 heroImage type 為 `Photo` 而非 `GenericPhoto`，讓 gql 的 `relatedPosts.heroImage` 能與 type 內容一致（ex: no `urlOriginal` type )。

2023-03-20 14:51 UTC, ChangRongXuan commented
### 調整
- 移除 `Number()`
- 修正  type `RelatedPost` 內的 `heroImage` 設定。

2023-03-20 14:59 UTC, erase2004 approved these changes
LGTM 👏

2023-03-20 15:26 UTC, merged