feat(post): adjust @mirrormedia/lilith-draft-renderer style for specific blocks
readr-media/Sachiel pull request #312
Opened 2023-03-21 02:26 UTC by ChangRongXuan

### 調整
- 調整 `[postId]` 頁面中特殊區塊的 draft-style：「報導重點摘要」「如果你關心這個議題」「引用資料」。
- 更新 `summary / actionList / citation / content` 的 typescript 定義。

### 新增
- import `@mirrormedia/lilith-draft-renderer` （version: 1.0.0-beta.1）
- 新增 `@mirrormedia/lilith-draft-renderer` d.ts 檔。

2023-03-21 07:41 UTC, erase2004 requested changes
我發現 1.0.0-beta.1 版本的內容沒有 lib，所以無法在本地端執行進行驗證
https://unpkg.com/browse/@mirrormedia/lilith-draft-renderer@1.0.0-beta.1/

2023-03-21 07:41 UTC, erase2004 commented on packages/readr/package.json
> +    "@mirrormedia/lilith-draft-renderer": "^1.0.0-beta.1",
從 [PR 的內容](https://github.com/mirror-media/Lilith/pull/263/files) 和[既往 publish 的 semver 邏輯](https://www.npmjs.com/package/@mirrormedia/lilith-draft-renderer?activeTab=versions) 這個 package 的版本號不應該為 `1.0.0-beta.1`，版本號的變化可以為 alpha -> beta -> x.y.z -> x'.y'.z' 的 alpha -> x'.y'.z' 的 beta -> x''.y''.z''，其中 x'.y'.z' 的組合，數值上會大於 x.y.z，例如：1.0.1 或 1.1.0 或 2.0.0 就會比 1.0.0 還要大，變動數字是越左邊的，其代表的變化越大。

2023-03-21 07:41 UTC, erase2004 commented on packages/readr/draft-renderer.d.ts
> +declare module '@mirrormedia/lilith-draft-renderer'
有沒有考慮在 `lilith-draft-renderer` 進行 compile 時，就順便輸出 .d.ts 檔案，畢竟它本來就是用 TypeScript 來寫的，生成 .d.ts 應該不太困難，這樣的話，在這裡就不用藉由自己弄一個 .d.ts 檔案，來迴避掉 ESLint 的 error，同時，因為 是從 package 端生成的 .d.ts 檔案，其內容也與 package 同步，使用上搭配 IDE 的功能，比較能做完整的提示。

2023-03-23 03:01 UTC, ChangRongXuan commented on packages/readr/package.json
> +    "@mirrormedia/lilith-draft-renderer": "^1.0.0-beta.1",
感謝指正 :pray: 
目前版本已更新為：@mirrormedia/lilith-draft-renderer": "^1.1.0-beta.3",

此版本內容更動為：[相關pr](https://github.com/mirror-media/Lilith/pull/270)
- 增加 `.babelrc.js` 處理 svg/png。
- 處理之前 package 內沒有 build 成功導致無內容的狀況。

2023-03-23 03:02 UTC, ChangRongXuan commented on packages/readr/draft-renderer.d.ts
> +declare module '@mirrormedia/lilith-draft-renderer'
感謝建議  🙏 
不好意思評估了一下修改時間之後，這個 comment 的修改會排到後續優化項目QQ
改為之後發 pr 更新

2023-03-23 03:12 UTC, ChangRongXuan commented
### 調整：
- 修正 `@mirrormedia/lilith-draft-renderer` 問題。
- 更新套件版本至 `^1.1.0-alpha.3`。

2023-03-23 05:12 UTC, erase2004 approved these changes
看起來可以，不太清楚實際進度，在 post (2913) 會出現問題，另外，有觀測到關聯文章的破圖問題。

2023-03-23 05:44 UTC, ChangRongXuan commented
不好意思請問  post (2913) 是指下圖這個 error msg 嗎？
<img width="953" alt="截圖 2023-03-23 下午1 42 26" src="https://user-images.githubusercontent.com/104489150/227114286-ec7a5932-2eb0-4b8d-ada5-4808b4bd2adf.png">

2023-03-23 06:13 UTC, ChangRongXuan commented
### 修復
- `block` error handle：當無 summary / citation / content / actionList 資料時，不顯示對應欄位，以免 draft-renderer 抓不到 block 資訊，進而報錯。

2023-03-23 08:04 UTC, merged