feat(readr/error): modify error page to conditionally render custom 404 or 500 error
readr-media/Sachiel pull request #321
Opened 2023-03-23 09:58 UTC by bibibobobi

- 透過 [getInitialProps](https://github.com/readr-media/Sachiel/pull/321/commits/0774ba5d2ff9108882ba0ec9669152d428629351) 取得四篇 latestPosts 資料及 statusCode。
- 用 PostsContainer 的高度，並設定`overflow: hidden;`，達到在不同螢幕寬度顯示不同篇數的效果。
- 根據 statusCode 來決定 render 404 或 500 UI，目前是除了404 以外的 error，都顯示 500。
- 取消註解以下幾行 code，可以測試 500 error 的 UI：
```
  // if (process.env.NODE_ENV === 'development') {
  //   statusCode = 500
  // }
```

2023-03-23 14:11 UTC, erase2004 requested changes

2023-03-23 14:11 UTC, erase2004 commented on packages/readr/pages/_error.tsx
> +  width: 1096px;
應該可以使用 `theme.width.main` 做統一管理

2023-03-23 14:11 UTC, erase2004 commented on packages/readr/pages/_error.tsx
> +  z-index: 9;
z-index 用 1 應該就好了

2023-03-23 14:11 UTC, erase2004 commented on packages/readr/pages/_error.tsx
> +  const articleItems: ReactElement<ArticleCard>[] | undefined =
type 為 `ReactElement[] | undefined` 就好了

2023-03-23 14:11 UTC, erase2004 commented on packages/readr/pages/_error.tsx
> +            href={`/post/${article.id}`}
href 資訊應該用 article 搭配 getHref 去算出結果

2023-03-23 14:11 UTC, erase2004 commented on packages/readr/pages/_error.tsx
> +      const images = article.heroImage?.resized?.w800 ?? {}
images 內容直接用 `article?.heroImage?.resized` 就好了，如果是要僅要顯示 w800 的圖片的話，建議是傳 `{ original, w800 }` 這兩組下去，補一個 original，可以讓 w800 沒資料時還可以做顯示，或者另一個方式就是用 `AricleListCard` 新增加 `rwd` 和 `breakpoint` 參數去做圖片顯示的控制

2023-03-23 14:11 UTC, erase2004 commented on packages/readr/pages/_error.tsx
> +            href={`/post/${article.id}`}
這一整串從 article 到 `ArticleListCard` 的 props 處理，其實可以套用 `convertPostToArticleCard` 來處理就好了

2023-03-25 02:46 UTC, bibibobobi commented on packages/readr/pages/_error.tsx
> +  const articleItems: ReactElement<ArticleCard>[] | undefined =
修改 type 之後，結果報錯，所以這邊我先保留喔

2023-03-25 04:30 UTC, bibibobobi commented on packages/readr/pages/_error.tsx
> +            href={`/post/${article.id}`}
感謝review～以上都已在此[pr](https://github.com/readr-media/Sachiel/commit/90ec5866de665c500f5cc9fbe66b7015573e6a39)中修改，但我剛剛 force push 發生了可怕的事，先關閉此pr，再重發一個，抱歉造成困擾 > <

2023-03-25 04:51 UTC, bibibobobi commented
- 以上回饋皆已修正，感謝～

- 改為使用 convertPostToArticleCard Util function 統一處理 posts

2023-03-25 05:17 UTC, erase2004 approved these changes
LGTM 👏

2023-03-25 05:24 UTC, merged