feat(about): add section of more
readr-media/Sachiel pull request #322
Opened 2023-03-24 07:58 UTC by v61265

### 描述
- 新增「更認識我們」區塊
- 在 ssr 時先抓取中文版本（page 在 `about` 中）、替換語言時才抓取英文版（page 在 `about-en` 中）。

### 參考資料
- 設計稿：https://www.figma.com/file/RfJHjsr8rBa7iIC7ir41AZ/2021_READr_Website?node-id=3360-21270&t=TKEZZEBqh34T76vV-0

2023-03-25 02:37 UTC, erase2004 requested changes
提問：我看設計稿提到「圖片 zoom in 參考 READr 首頁」，
目前文字也跟著放大的，這和首頁不太一樣，請問這部份的行為是否要一致？

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/components/about/more.tsx
> +  .tail-arrow {
More 區塊應該沒用到 `tail-arrow.svg`，所以應該不需要 .tail-arrow 的樣式？

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/components/about/more.tsx
> +                      defaultImage={'/icons/default/collaboration.svg'}
請問：圖片預設是用協作專區的樣式？

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/components/about/more.tsx
> +                      rwd={{
上下兩個圖片，完整的設定似乎是
```
< 768px (md) : 100vw
≧ 768px (md) AND ﹤1200 (xl) : 441px
≧ 1200 (xl) : 352px
```
可以藉由 breakpoint + rwd 達成設定

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/graphql/query/page-variable.ts
> +  'id' | 'name' | 'imageFile' | 'resized'
query 的 relatedImage 中只有 id, resized ，與輸出的 type 資訊不符合

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/graphql/query/page-variable.ts
> +  id: string
query 資訊中有 id, page, name, relatedImage, value, url，與輸出的 type 資訊不符合

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +import {
PageVariable 是 type，應當用 import type 做明顯區隔

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +  const fetchENMore = useCallback(async () => {
雖然會有 ESLint `react-hooks/exhaustive-deps` 的提示，但實際上該 function 沒有必要用 useCallback 包起來，也沒有必要成為 useEffect 的 dependency，所以此提示為為錯誤的提示

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +    return moreReportData
return value 未被使用，應該不需要？

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +    if (!renderedMore[language]?.length) {
如果抓回來的資料是 `[]`，因為 renderedMore 的更新，會再次觸發 useEffect 的行為，導致再次呼叫 fetchENMore，而產生 infinite loop，請問這是預期的行為嗎？

2023-03-25 02:37 UTC, erase2004 commented on packages/readr/graphql/query/page-variable.ts
> +          w1200
因為 768 (md) 以下圖片顯示大小是 100vw，如果以 DPR (deivce pixal ratio) 3 來計算的話，會是 2,304，應該會需要 w2400，用 DPR 1, 2, 3 與 320 - 728 所取得的顯示圖片範圍，可得 w480 ~ w2400 的資訊應該都需要

一些常見手機裝置的 DPR 資訊： https://www.mydevice.io/

2023-03-26 15:48 UTC, v61265 commented
> 目前文字也跟著放大的，這和首頁不太一樣，請問這部份的行為是否要一致？

（不好意思我不太熟用網址直接分享設計稿節點的技巧，只能貼截圖。）文字放大的部分是參考設計稿最左邊 style 區塊下方，如截圖。
![](https://ppt.cc/fIA0wx@.png)

2023-03-26 16:20 UTC, v61265 commented on packages/readr/pages/about.tsx
> +  const fetchENMore = useCallback(async () => {
不好意思想再確認一次，具體而言你會怎麼判斷是否需要 useCallback 呢？

2023-03-26 16:26 UTC, v61265 commented on packages/readr/components/about/more.tsx
> +  .tail-arrow {
感謝提醒，已於 [fca601a](https://github.com/readr-media/Sachiel/pull/322/commits/fca601aad960c4e5d76b75877ccfb1cbc3012690) 移除～

2023-03-26 16:27 UTC, v61265 commented on packages/readr/components/about/more.tsx
> +                      defaultImage={'/icons/default/collaboration.svg'}
已詢問需求方，目前先 pending。

2023-03-26 16:27 UTC, v61265 commented on packages/readr/graphql/query/page-variable.ts
> +  'id' | 'name' | 'imageFile' | 'resized'
感謝提醒，已於 [43869df](https://github.com/readr-media/Sachiel/pull/322/commits/43869df27c197120a4bd51ab736fd346d82deacf) 修改。

2023-03-26 16:27 UTC, v61265 commented on packages/readr/graphql/query/page-variable.ts
> +  id: string
感謝提醒，已於 [43869df](https://github.com/readr-media/Sachiel/pull/322/commits/43869df27c197120a4bd51ab736fd346d82deacf) 修改。

2023-03-26 16:28 UTC, v61265 commented on packages/readr/pages/about.tsx
> +import {
感謝提醒，已於 [43869df](https://github.com/readr-media/Sachiel/pull/322/commits/43869df27c197120a4bd51ab736fd346d82deacf) 連之前 award 一起修改。

2023-03-26 16:28 UTC, v61265 commented on packages/readr/pages/about.tsx
> +  const fetchENMore = useCallback(async () => {
總之先改爆：[ea4013b](https://github.com/readr-media/Sachiel/pull/322/commits/ea4013bb6bc2abc145819aa7d75b6e410951b1c0)

2023-03-26 16:28 UTC, v61265 commented on packages/readr/pages/about.tsx
> +    return moreReportData
對耶，感謝提醒，已於 [ea4013b](https://github.com/readr-media/Sachiel/pull/322/commits/ea4013bb6bc2abc145819aa7d75b6e410951b1c0) 修改

2023-03-26 16:29 UTC, v61265 commented on packages/readr/pages/about.tsx
> +    if (!renderedMore[language]?.length) {
已於 [ea4013b](https://github.com/readr-media/Sachiel/pull/322/commits/ea4013bb6bc2abc145819aa7d75b6e410951b1c0) 修改，將 `renderedMore` 中多存一個 `hasFetched` 判斷是否抓過資料。

2023-03-26 16:30 UTC, v61265 commented on packages/readr/graphql/query/page-variable.ts
> +          w1200
感謝提醒，已於 [ea4013b](https://github.com/readr-media/Sachiel/pull/322/commits/ea4013bb6bc2abc145819aa7d75b6e410951b1c0) 修改。

2023-03-26 16:31 UTC, v61265 commented on packages/readr/components/about/more.tsx
> +                      rwd={{
感謝提醒，已於 [ea4013b](https://github.com/readr-media/Sachiel/pull/322/commits/ea4013bb6bc2abc145819aa7d75b6e410951b1c0) 修改。
因為我們的斷點和 [@readr-media/react-image](https://www.npmjs.com/package/@readr-media/react-image) 相同，就先沒設定了。

2023-03-27 02:22 UTC, erase2004 commented
> > 目前文字也跟著放大的，這和首頁不太一樣，請問這部份的行為是否要一致？
> 
> （不好意思我不太熟用網址直接分享設計稿節點的技巧，只能貼截圖。）文字放大的部分是參考設計稿最左邊 style 區塊下方，如截圖。 ![](https://camo.githubusercontent.com/5495fa5adba43f76c410aa1e0febfda32a4173904582ab5fad305f33a4d9f25d/68747470733a2f2f7070742e63632f664941307778402e706e67)

https://www.figma.com/file/RfJHjsr8rBa7iIC7ir41AZ/2021_READr_Website?node-id=1059-7596&t=yR3bgZYxi2ERrhjh-0
在原先的效果中，hover 只會使圖片變大 / 文字產生底線的效果

https://www.figma.com/file/RfJHjsr8rBa7iIC7ir41AZ/2021_READr_Website?node-id=3400-23625&t=IgLJn5GTFDL6amkh-0
但現在的效果中，hover 會使圖片變化 / 文字變大 / 文字產生底線的效果

兩者的效果不一致，需要和設計和需求方確認用意。

2023-03-27 04:43 UTC, erase2004 requested changes

2023-03-27 04:43 UTC, erase2004 commented on packages/readr/graphql/query/page-variable.ts
> +          w1200
resized 的內容可以使用 `graphql/fragments/resized-images` 的內容，這樣未來在一起調整時比較方便

2023-03-27 04:43 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +    en: { hasFetched: false, data: moreReportData },
en 的預設值從 `[]` 變成 `moreReportData` ?

2023-03-27 05:03 UTC, v61265 commented on packages/readr/pages/about.tsx
> +    en: { hasFetched: false, data: moreReportData },
感謝提醒，已於 [aec1716](https://github.com/readr-media/Sachiel/pull/322/commits/aec17167afa9e67f8a8ecb4b485a4c80a0a8d13f) 修改。

2023-03-27 05:12 UTC, v61265 commented
> 

剛剛和設計師確認過，確實是失誤，目前已於 [62d8c31](https://github.com/readr-media/Sachiel/pull/322/commits/62d8c3181954369d90555332d1facf98d32a6488) 調整。

2023-03-27 05:13 UTC, v61265 commented
> resized 的內容可以使用 graphql/fragments/resized-images 的內容，這樣未來在一起調整時比較方便

感謝提醒，已於 [f23ecb9](https://github.com/readr-media/Sachiel/pull/322/commits/f23ecb99d0af0d3b49d554868b3558593e218f76) 調整。

2023-03-27 05:28 UTC, erase2004 approved these changes
LGTM 👏 🥳

2023-03-27 05:38 UTC, merged