feat(post): add `tags` & `latesPosts` & update relevant types
readr-media/Sachiel pull request #324
Opened 2023-03-25 05:16 UTC by ChangRongXuan

### 新增
- 標籤頁： `/tag/[name]`。
- 文章頁下方的「標籤列表」，點按後可另開分頁至對應的標籤頁（同 2.0 設定）。
- 補上 query 中 `tag` 的 typescript 設定。
    -  於 `types/common` 新增 `GenericTag` 
    -  於 `GenericPost` 新增 `tags: GenericTag[]`
    
- 文章頁新增「最新報導」：除相關報導外，透過 `latestPosts` 取得最新 4 篇報導。

### 調整
- 文章頁首圖（HeroImage）
   - 調整 ReactImage 格式與 #309 相同。
   - 增加 HeroImage 圖說（figcaption)
   - `content、summary、actionList、citation` 的 JSON 新增對應的 `GenericBlocks` & `GenericEntity` type。

### 提問＆討論
-  `GenericTag`：不好意思想請教關於 tag 的欄位目前只會使用到 `id`、`name`，想請教在設定 `GenericTag` 的細項時，需要把 tag 所有的項目都列出（ex: brief. heroVideo....) ，後續使用再透過 `Pick<>` 方式選取想要的項目就好嗎？（還是可以維持目前設定，列出所需的項目即可）

- 發現在新增「最新報導」時，發現會與「相關報導」在 type 上有差異：
    - `latestPosts`：`Post[]` 
    - `relatedPosts`：`RelatedPost[]`
    
- 但其實這兩者在內容上差異不多，有在想是否當初我這邊寫 `RelatedPost[]` type 時，沒有考慮清楚，導致目前這兩者 type 定義重疊性極高，使用上只需要保留其中一項即可。

2023-03-25 05:35 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
> +      link: `${protocol}//${SITE_URL}/post/${post.id}`,
目前相關報導因為是使用 `react-components` 元件（React)，無法使用 NextLink 方式去處理報導連結，因此原始做法是透過傳入使用 `protocol` 和 `SITE_URL` 組合的 report-link 處理 ，但發現在 `SITE_URL` 的部分：
- prod：`www.readr.tw`
- staging：`staging.readr.tw`
- dev：`dev.readr.tw`
- default：`localhost`

在 [dev](https://readr-next-dev-4g6paft7cq-de.a.run.app/post/2171) 上測試後發現沒有辦法正確連結（ dev 需要是 `readr-next-dev-4g6paft7cq-de.a.run.app/post/[postId]` 才有辦法連結，跟目前透過 `SITE_URL` 是會產生 `dev.readr.tw/post/[postId]` 。

想請教是因為我誤用 `SITE_URL` 去處理，還是建議是 `react-components` 元件那邊去做調整才OK :bowing_woman:

2023-03-25 05:44 UTC, ChangRongXuan commented on packages/readr/components/post/post-content.tsx
> +  }
補充：增加 `checkValue` 去判斷是否顯示與 draft 有關的UI。

會新增 `checkValue` 是發現當 `summary` 等欄位在沒填資料的狀況下，依舊會收到：
```
  "summary": {
        "blocks": [
          {
            "key": "crhgf",
            "data": {},
            "text": "",
            "type": "unstyled",
            "depth": 0,
            "entityRanges": [],
            "inlineStyleRanges": []
          }
        ],
        "entityMap": {}
      },
```
導致使用原先 `postData?.summary && ... ` 的判斷無效，因此增加此 function 去做 true/false 判斷，
但也因此新增了相關的 `GenericContent`、`GenericBlocks`、GenericEntity` 的 type 設定。

2023-03-25 05:58 UTC, ChangRongXuan commented on packages/readr/components/post/post-content.tsx
> +  const checkValue = (blocks: GenericBlocks[]) => {
補充：增加 `checkValue` 去判斷是否顯示與 draft 有關的UI。

會新增 `checkValue` 是發現當 `summary` 等欄位在沒填資料的狀況下，依舊會收到：
```
  "summary": {
        "blocks": [
          {
            "key": "crhgf",
            "data": {},
            "text": "",
            "type": "unstyled",
            "depth": 0,
            "entityRanges": [],
            "inlineStyleRanges": []
          }
        ],
        "entityMap": {}
      },
```
導致使用原先 `postData?.summary && ... ` 的判斷無效，因此增加此 function 去做 true/false 判斷，
但也因此新增了相關的 `GenericContent`、`GenericBlocks`、GenericEntity` 的 type 設定。

2023-03-25 07:58 UTC, erase2004 requested changes
> GenericTag：不好意思想請教關於 tag 的欄位目前只會使用到 id、name，想請教在設定 GenericTag 的細項時，需要把 tag 所有的項目都列出（ex: brief. heroVideo....) ，後續使用再透過 Pick<> 方式選取想要的項目就好嗎？（還是可以維持目前設定，列出所需的項目即可）

列出目前使用中的項目，使用時從 GenericTag 中 Pick 出使用的部份



> 發現在新增「最新報導」時，發現會與「相關報導」在 type 上有差異：
> 
>     latestPosts：Post[]
>     relatedPosts：RelatedPost[]

目前兩者看起來有差異，如果要使內容一致的話，要調整既有 `posts` query 和輸出的 `PostDetail` type 的內容

如果內容不能一致，那還是維持兩個獨立的 type name

2023-03-25 07:58 UTC, erase2004 commented on packages/readr/types/common.ts
> +export type GenericContent = {
好奇，關於 draft-js 的資料 (`GenericContent`, `GenericBlocks`, `GenericEntity`)，有沒有可能用 [@types/draft-js](https://www.npmjs.com/package/@types/draft-js) 來處理就可以了？

2023-03-25 07:58 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
> +  .readr-media-react-image {
標注一下這是改寫 `<SharedImage />` 的樣式

2023-03-25 07:58 UTC, erase2004 commented on packages/readr/components/post/report.tsx
> +export default function PostContent({
component 匯出名稱需要調整，和檔名不符

2023-03-25 07:58 UTC, erase2004 commented on packages/readr/components/post/report.tsx
> +      link: `${protocol}//${SITE_URL}/post/${post.id}`,
你可以用 `getHref` 去取得 post 的 url 資訊，你需要傳入 post 的 style, id 和 slug 資訊，
需要調整 query 內容和輸出的 type 內容

2023-03-25 07:58 UTC, erase2004 commented on packages/readr/components/post/report.tsx
> +          <RelatedReport relatedData={addLinkToPosts(relatedPosts)} />
需要解決圖片載入失敗的破圖

2023-03-25 07:58 UTC, erase2004 commented on packages/readr/components/post/tag.tsx
> +    cursor: pointer;
li 底下的 a 用
```
display: inline-block;
```
並把 li 的 padding 下放到 a
同時移除 li 上的 padding 和 `cursor: point`
這樣鍵盤導覽與滑鼠操作的範圍便會一致

2023-03-25 07:58 UTC, erase2004 commented on packages/readr/components/shared/media-link.tsx
> +  margin = '0 auto 48px',
margin 不是整合進 className，獨立抽出來做設定的原因？

2023-03-25 08:17 UTC, ChangRongXuan commented on packages/readr/components/shared/media-link.tsx
> +  margin = '0 auto 48px',
已更正，不好意思之前因為 props 設定只有 `margin`， `className` 是後面追加，
沒有考慮到功能重疊的部分，已移除 :pray: :pray:

2023-03-25 10:54 UTC, ChangRongXuan commented on packages/readr/types/common.ts
> +export type GenericContent = {
謝謝建議 :crab:   剛剛嘗試改寫如下：

```
// types/common.ts

import type { ContentBlock, Entity } from 'draft-js'

export interface GenericContentBlock extends ContentBlock {
  key: string
  text: string
  type: string
}

export type GenericEditorState = {
  blocks: GenericContentBlock[]
  entityMap: Entity
}
...

export type GenericPost = { 
  ...
  content: GenericEditorState // draft-renderer JSON
}
```
### 觀察
- 雖然可以直接透過 `ContentBlock` 去做 type 設定，但如果使用到 `blocks` 的 property `type`、`text` 就會報錯，因此判斷 `ContentBlock` 雖然可以使用，但對於內部 property 細節 type 並沒有多做定義 :thinking:
<img width="708" alt="截圖 2023-03-25 下午6 47 04" src="https://user-images.githubusercontent.com/104489150/227712629-a55468e0-831a-45cc-91f6-0ac4599a4534.png">

- 因此在寫法上選擇用 `interface` 去擴展原有 `ContentBlock` 的內容（目前只會使用到 `type`、`text`），並新定義一個 type：`GenericEditorState` ，讓「文章頁」和「關於我們」頁面都可以使用。

2023-03-26 15:25 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
> +          <RelatedReport relatedData={addLinkToPosts(relatedPosts)} />
### 調整
破圖問題透過調整 `@readr-media/react-compoents`  套件內容處理。 [readr-media/Almisael/pull/8](https://github.com/readr-media/Almisael/pull/8) 

調整項目：

1. 報導圖片改用 `react-image` 套件處理。
2. defaultImage 使用 `DEFAULT_POST_IMAGE_PATH`，透過傳入 props.defaultImage 設定。
3. 報導閱讀時間/發佈時間：改為使用 `dayjs` 處理。
4. 每篇報導的標題，改為可透過 `postData.name` 或 `postData.title` 傳入。

### 討論 ＆ 說明
- 有觀察到 `Post[]` type 設定中，跟報導標題相關的 property 名稱為 `title` 而非 `name`（其實蠻好奇會這樣設定的原因 :raised_hands: ）
- 因此上面 4. 的改動，主要是為了讓同一個元件（related-report），可以同時讓 `latestPosts` 和 `relatedPosts` 這兩個在 property 有些微差異的資料格式使用。
```
   <ReportInfo  title={post.name || post.title} ..... />
```
- 目前修改方向是讓共用元件先找 `postData` 內的 `name` 資料，如果沒有會轉而使用 `title` 的內容。

2023-03-26 15:28 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
> +      link: `${protocol}//${SITE_URL}/post/${post.id}`,
謝謝提醒....:bowing_woman: :bowing_woman: 
一直卡住以為要用絕對路徑去處理，已經改成統一用 `getHref` 解決問題。

2023-03-26 17:38 UTC, ChangRongXuan commented
### 修改
- 傳入 `RelatedReport` 的報導連結改用 `getHref` 處理。
- draft-renderer 相關的 ts 設定改用 `draft-js` 內的 type 處理。細節紀錄於 [#r1148350319](https://github.com/readr-media/Sachiel/pull/324#discussion_r1148350319)。
- 修正「相關報導」破圖問題：修改 `@readr-media/react-compoents` 內容，細節紀錄於 [#r1148579494](https://github.com/readr-media/Sachiel/pull/324#discussion_r1148579494)。
- `PostDetail` type 修正：

   - 刪除不會用到的 property 
   - 將 graphql 中對於  `relatedPosts` 的篩選條件，修改為與 `latestPosts` 相同


### 紀錄 ＆ 討論
- 整理了 `RelatedPosts` 和 `Post` 的差異：因為「報導標題」的部分有 `title` 和 `name` property 名稱的差異，加上 `RelatedPosts` 沒有 `ogImage` 的需求，所以目前是分開定義沒有整併。

![type](https://user-images.githubusercontent.com/104489150/227793096-ff16d2ea-20c3-4e24-856b-ea4fccfa6f09.svg)

- 因為兩者細節不同，但都需要共用 `<RelatedReport>` 元件，所以目前在針對傳入該共用元件的 posts type 定義，採用以下方式進行處理：
```
  function addLinkToPosts(posts: (RelatedPost | Post)[]) { .... }
```

- Q：方便的話想好奇詢問在 `/fragments/post.ts` 中，會特別將 `name` 改為以 `title` 處理，是有特別的原因嗎？感謝 :pray:
```
export const postFragment = gql`
  fragment PostFields on Post {
    id
    slug
    style
    title: name
    .....
  }
`
```

### 其他
- 增加 `.readr-media-react-image` 的 comment 註解。
- 修正 `post/report.tsx` 的錯誤 component 匯出名稱，改為與檔名相同。
- 將專案使用的 `readr-media/react-component` 版本升至 `^2.0.0-alpha.1`（等 PR & 驗收確認無誤後，才會升至 `^2.0.0` 正式版）

2023-03-27 09:38 UTC, ChangRongXuan commented on packages/readr/types/common.ts
> +export type GenericContent = {
2023/3/27 16:00 更新：

- 改為透過 `draft-js` 原生 type 去定義 `summary` 等 JSON 和 `blocks`。
```
import type { RawDraftContentState } from 'draft-js' // type for summary/content/actionList/citation
import type { RawDraftContentBlock } from 'draft-js'   // type for blocks
```
- 移除 `GenericEditorState`、`GenericContentBlock` 等多餘設定。

2023-03-27 09:38 UTC, ChangRongXuan commented
### 更新
- 改為透過 `draft-js` 原生 type 去定義 `summary` 等 JSON 和 `blocks`。
```
import type { RawDraftContentState } from 'draft-js' // type for summary/content/actionList/citation
import type { RawDraftContentBlock } from 'draft-js'   // type for blocks
```
- 移除 `GenericEditorState`、`GenericContentBlock` 等多餘設定。

2023-03-28 04:31 UTC, erase2004 requested changes
需等 https://github.com/readr-media/Almisael/pull/8 調整完畢後，這邊一併更新

2023-03-28 04:35 UTC, erase2004 commented
> 
    Q：方便的話想好奇詢問在 /fragments/post.ts 中，會特別將 name 改為以 title 處理，是有特別的原因嗎？感謝 🙏

原先專案中這麼寫，單純維持相同行為而已

2023-03-29 02:22 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
> +            postData={addLinkToPosts(latestPosts)}
問題描述：因為套件改為只用 `name` 取得報導標題，最新報導因為是用 `title` 處理所以沒有資料。

提問：請問我可以改 `/fragment/post` 的 title 變為 name 嗎？因為如果是直接在 `/post/report` 這邊強制 `latestPosts`把 title 替換成name，試起來 typescript 也會報錯（因為`(RelatedPost | Post)[]` 都不符合更新後的 `latestPosts`）。

```
export type Post = Override<
  Pick<
    GenericPost,
    | 'id'
    | 'slug'
    | 'style'
    | 'title'
    | 'publishTime'
    | 'readingTime'
    | 'heroImage'
    | 'ogImage'
  >,
  {
    heroImage: PhotoWithResizedOnly | null
    ogImage: PhotoWithResizedOnly | null
  }
>
```

2023-03-29 02:24 UTC, ChangRongXuan commented
### 調整 
- `@readr-media/react-component` 套件版本升至 `2.0.0-alpha.4` 

### 備註
- 使用新版本，目前會有 typescript 的問題，細節紀錄於 [#1151325907](https://github.com/readr-media/Sachiel/pull/324#discussion_r1151325907)。

2023-03-29 04:56 UTC, erase2004 commented on packages/readr/components/post/report.tsx
> +            postData={addLinkToPosts(latestPosts)}
幾個解法：
1. postFragment 只輸出 `name`，那與 postFrament 相關的處理邏輯、type 都要調整
2. postFragment 輸出 `name` 和 `title`，與 postFrament type 都要調整
3. 調整 `dataWithLink` 的處理邏輯，讓它在接收到不論是 `RelatedPost` 還是 `Post` 的資料，都能夠輸出 `RelatedReport` 所需要的 postData 資訊

2023-03-29 09:52 UTC, ChangRongXuan commented
### 調整 
- 更新 `@readr-media/react-components` 版本至 `2.0.0-alpha.5`
- 增加 `convertTitleToName` function 去轉換 `latestPosts` 的資料。
   - 將 `latestPosts` 的 property `title` 轉成 `name`。
   - 轉為 `name` 後， `@readr-media/react-components` 才有辦法讀取報導標題的內容。

2023-03-29 09:53 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
> +            postData={addLinkToPosts(latestPosts)}
目前採用方法 3. 修改。調整細節可見：[0b0dfc4](https://github.com/readr-media/Sachiel/pull/324/commits/0b0dfc47d35fe7345acd4de452536f658b8d1933) 。

2023-03-29 10:05 UTC, erase2004 reviewed
忽然想到一個問題
https://mirrormedia.slack.com/archives/C6R90LWLA/p1679909337935099
關聯文章的圖片是不是也要先用圖片的 og image 資訊，再用 hero image 資訊？

(忽然覺得 `RelatedPost` 和 `Post` type 的內容可能會是相同了)

2023-03-29 10:05 UTC, erase2004 commented on packages/readr/components/post/report.tsx
> +  function convertTitleToName(posts: Post[]) {
輸出 type 為 `RelatedPost[]`

2023-03-29 10:05 UTC, erase2004 commented on packages/readr/components/post/report.tsx
>    function addLinkToPosts(posts: (RelatedPost | Post)[]) {
輸入 type 為 `RelatedPost`

2023-03-29 14:28 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
>    function addLinkToPosts(posts: (RelatedPost | Post)[]) {
更新：改為只保留 type [Post]，目前 `latestPosts` 和 `relatedPosts` 都是 `Post[]`

2023-03-29 14:30 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
> +  function convertTitleToName(posts: Post[]) {
- 更新：改為只保留 type [Post]，目前 `latestPosts` 和 `relatedPosts` 都是 Post[]
- 透過 Function `addLinkToPosts`  輸出的 `dataWithLink`，有另用 type `RelatedReport` 作定義。

2023-03-29 14:58 UTC, ChangRongXuan commented
### 說明
- 因為需求上 `relatedPosts` 也需要 ogImage 資訊，加上 ogImage 後`RelatedPost` 和 `Post` 重疊度極高（只差在 `title` 和 `name` 的差異）。
- 為了避免日後維護上的名稱混淆，因此拿掉 `RelatedPost`，改為統一用 `Post` type。
- 影響頁面：`[postId]`、`report.tsx`

### 調整 
- 重構 `graphql/query/post`中，取得單篇文章的 graphql 架構，使用 `postFragment` 取代掉重複的 graphql 語法。 [345ca2e](https://github.com/readr-media/Sachiel/pull/324/commits/345ca2ef49d8ff03accfb890d3e6183f650cbb4b)

   - 因為改用 `postFragment`，原先文章頁有使用到 `name` 的一律改為 `title`
- type `PostDetail` 中的 `relatedPosts` 定義改為 type `Post[]` 。[345ca2e](https://github.com/readr-media/Sachiel/pull/324/commits/345ca2ef49d8ff03accfb890d3e6183f650cbb4b)
### `report.tsx` 調整項目
- 原先相關報導遇到的 `RelatedPost` 和 `Post` 衝突，因上述調整改為統一使用 type `Post`。[b8b22a6](https://github.com/readr-media/Sachiel/pull/324/commits/b8b22a67163dc48fa13d088546e6ae4e968fbb13)
- 但因為傳入 `<RelatedReport>` 套件元件的資料，與 `Post` 有部分差異，因此另定義一個 `RelatedReport` type，因目前看起來只有在 `report.tsx` 這個元件會用到這個 type，所以獨立寫在這個元件內。
```
type RelatedReport = Pick<
  Post,
  | 'id'
  | 'slug'
  | 'title'
  | 'style'
  | 'publishTime'
  | 'readingTime'
  | 'heroImage'
  | 'ogImage'
> & {
  name: string
  link: string
  images: ResizedImages | null
}
```

2023-03-29 15:58 UTC, erase2004 requested changes

2023-03-29 15:58 UTC, erase2004 commented on packages/readr/graphql/query/post.ts
> +export type PostDetail = Override<
`PostDetail` type 的敘述我會用

```
export type PostDetail = Override<
  Post &
    Pick<
      GenericPost,
      | 'heroCaption'
      | 'content'
      | 'summary'
      | 'actionList'
      | 'citation'
      | 'dataAnalysts'
      | 'writers'
      | 'designers'
      | 'relatedPosts'
      | 'categories'
      | 'tags'
    >,
  {
    heroImage: PhotoWithResizedOnly | null
    ogImage: PhotoWithResizedOnly | null
    dataAnalysts: Author[]
    writers: Author[]
    designers: Author[]
    relatedPosts: Post[]
    categories: Category[]
    tags: Tag[]
  }
>
```

因為 id, slug, style, title, heroImage, ogImage, publishTime, readingTime 都是從 postFragment 來，
而 postFragment 輸出 type Post，
未來 postFragment 與輸出的 Post 修改時，這邊也能即時反應更動

2023-03-29 15:58 UTC, erase2004 commented on packages/readr/components/post/report.tsx
> +    })) as RelatedReport[]
這邊不該用 as 來去假定輸出會是那樣的內容，應該把 `RelatedReport[]` 放在 function 的 return type，然後調整 function 的處理，來確保輸出內容符合 `RelatedReport[]` 內容

2023-03-30 03:13 UTC, ChangRongXuan commented on packages/readr/components/post/report.tsx
> +    })) as RelatedReport[]
了解，已改寫為：
```
  function addLinkInPosts(posts: Post[]) {
    const dataWithLink: RelatedReport[] = posts?.map((post: Post) => ({
      ...post,
      name: post.title,
      images: post.ogImage?.resized || post.heroImage?.resized || null,
      link: getHref({
        style: post.style,
        id: post.id,
        slug: post.slug,
      }),
    }))
    return dataWithLink
  }
  ```

2023-03-30 03:15 UTC, ChangRongXuan commented on packages/readr/graphql/query/post.ts
> +export type PostDetail = Override<
感謝建議 :ok_woman: :ok_woman: 
已於 [7ad48d5](https://github.com/readr-media/Sachiel/pull/324/commits/7ad48d52af2dd64b307a9ad308aa2f98f433fc3d) 修改。

2023-03-30 03:24 UTC, erase2004 approved these changes
LGTM 🥳 🎉

2023-03-30 03:29 UTC, merged