feat(post): add article-type (scrollable-video/blank/news/frame) components
readr-media/Sachiel pull request #333
Opened 2023-03-30 06:05 UTC by ChangRongXuan

### 新增
- 新增 `scrollable-video/blank/news/frame` 元件。

#### 針對 `blank` 頁面需求的調整：
- post query 新增 `otherByLine` 以取得作者欄位資訊。
- 使用 `@readr-media/share-button` 套件，作為 `blank` 的`navbar`  使用。 範例：[/2905](https://www.readr.tw/post/2905)。
  
#### 針對 `scrollable-video`  頁面需求的調整：
- `post-title` 新增 `showTitle` 變數去控制是否顯示文章標題。 範例：[/2932](https://www.readr.tw/post/2932)

### 重構
- `[postId]` 頁面內容改為透過 `style` 決定 render 相應的 `article-type` 元件。
- 移除 `post-heading.tsx`：改至 article-type 內各自設定。（因不同 article-type 對於 heading 需求不同）
- 新增 `subscribe-button` 元件，降低程式碼重複性。

2023-03-30 12:15 UTC, ChangRongXuan commented
（不好意思檢查的時候發現資料抓取有些 bug，所以比較晚 request review... 上班時間再看就好，不好意思 :bowing_woman: ）

### Article Type 特點整理

#### Frame ( K6-dev `/post/2461` 為 Frame 文章）
- 使用特定 Header（ @readr-media/react-component 元件的 Logo + @readr-media/share-button 的社群分享按鈕）
- 如有首圖，顯示為滿版（100vw)
- 有特殊 Credit 區塊，需放 footer 前，且欄位抓 `otherByLine`，需轉換字串為特殊格式。
- 參考範例（READr2.0）：[/2905](https://www.readr.tw/post/2905) 確診（無首圖）、[/2934](https://www.readr.tw/post/2934) 港人房間（有首圖）。
<img width="328" alt="截圖 2023-03-30 下午8 19 37" src="https://user-images.githubusercontent.com/104489150/228833979-be3f2d44-00b3-4261-a7e9-9da084870396.png">
<img width="310" alt="截圖 2023-03-30 下午8 19 44" src="https://user-images.githubusercontent.com/104489150/228834012-a8e62d95-4354-4b20-a600-d973866169e9.png">


#### Blank ( K6-dev  `/post/2250` 為 Blank 文章）
- 只抓內文資料，且需蓋掉原本 header 
- 需要 footer，底色固定為 #ffffff
- 參考範例（READr2.0）：[/2909](https://www.readr.tw/post/2909) 裴洛西

#### Scrollable-Video ( K6-dev  `/post/2855` 為 Scrollable-Video 文章）
- 文章首圖需蓋掉原有 header，且文章標題放首圖上
- 抓「內文」欄位內排序第一個的 Embedded-code，接續在首圖之後
- 「內文」顯示 Embedded-code 需跳過第一個（因為第一個已拉至最前面顯示）
- 其他部分同一般文章，但原大標區塊就不顯示標題文字了（如下圖）
- 參考範例（READr2.0）：[/2932](https://www.readr.tw/post/2932) 兵推
![截圖 2023-03-30 下午8 13 35](https://user-images.githubusercontent.com/104489150/228832461-651ecfee-fc50-408e-8f76-98a41933089f.png)

### 備註：[READr 3.0 Article-type 文件](https://paper.dropbox.com/doc/READr-3.0-article-type--B1ekLN0Ji2KrQOXkqP0piNOZAg-w86BzpkoGgmuiYvHhVFwq)

2023-03-31 03:33 UTC, erase2004 requested changes

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/styles/theme/index.ts
> +    articleType: 650, // type: `frame`, `blank`, `scrollablevideo` need to cover `header`
請讓 `zIndex` 底下項目依照數字大小遞減排序

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/article-type/blank.tsx
> +  .layout-footer {
註解一下是改寫 `<Footer />` 的樣式

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/article-type/news.tsx
> +import Content from '~/components/post/post-content'
import name 和 export default name 不一致的原因？

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/subscribe-button.tsx
> +const SubscribeWrapper = styled.section`
應該用 `<div>` 就好了，這個區塊沒有 heading 的需求

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/post-content.tsx
> +      blocks.length === 1
`blocks.length === 1` 的判斷應該優先於其他

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/post-content.tsx
> +      <>
這一堆 Fragment (`<></>`) 應該多餘的

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
> +    case 'news':
應該用 `ValidPostStyle` 去表示每一個 case

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
需要消除 Ln. 56. data 為 any 的情況

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
getServerSideProps 中的 try catch 行為都雷同，這樣的話，我會把全部只放在一個 try catch 中，每一組 query 放在各自的 `{}` 底下處理

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/article-type/frame.tsx
> +  .DraftEditor-root {
註解一下是改寫 `<PostContent>` 下 `<DraftRenderer>` 的樣式

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/article-type/frame.tsx
> +  z-index: ${({ theme }) => theme.zIndex.articleType};
Header 的目標看起來是要保持文章在捲動時，不被文章內容給覆蓋，基於這樣的目的，
其實可以設定為:
1. ~~10~~ 110 (同一層高於其他元件，但目前觀察到會受到相關報導和最新報導區塊標題的不太合理的 100 給覆蓋)
2. inherit (與 `FrameWrapper` 相同，z-index 行為預設是不會 `inherit`)

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/post-content.tsx
看了一下結構，`<Container>`、`<Summary>`、`<Content>`、`<ActionList>`、`<Citation>`，結構上可以用以下形式表示
```
article
  |－ section
  |－ section
  |－ section
   ﹂ section
```
或
```
article
  |－ article
  |－ article
  |－ article
   ﹂ article
```
section 和 article 的差別在於 section 之一，
會需要 heading 元素，目前情況每個 section 看來是缺乏 heading 元素，
按照內容與結構來看，或許可以改用 article

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
> +    default:
其他文章樣式、沒有填寫文章樣式，以及不存在文章的，通通跑到 default case，導致出錯

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
Ln. 51
`let postData, latestPosts`
在宣告時須指定 type

2023-03-31 03:33 UTC, erase2004 commented on packages/readr/components/post/article-type/scrollable-video.tsx
結構上來講，`<ScrollTitle>` 和 `<SharedImage>` 適合放在 `<HeroImage>` 底下，然後 `<HeroImage>` 與 `<ScrollVideo>` 適合放在一個群組，然後在這個群組設定一次 `z-index` 就好了

2023-03-31 05:22 UTC, ChangRongXuan commented on packages/readr/styles/theme/index.ts
> +    articleType: 650, // type: `frame`, `blank`, `scrollablevideo` need to cover `header`
此項已修正於 [7e07891](https://github.com/readr-media/Sachiel/pull/333/commits/7e07891ca0bc0cc4b468a9e3952afddaf6a5e9c3) :raised_hands:

2023-03-31 05:23 UTC, ChangRongXuan commented on packages/readr/components/post/article-type/blank.tsx
> +  .layout-footer {
此項已修正於 [b8b359e](https://github.com/readr-media/Sachiel/pull/333/commits/b8b359e13a0b8c935dc6873bbeb875475cb889e6) 🙌

2023-03-31 05:25 UTC, ChangRongXuan commented on packages/readr/components/post/article-type/news.tsx
> +import Content from '~/components/post/post-content'
之前擔心太多 Post 開頭會不好閱讀 :rofl:
目前已全部改成 import name / export default name 使用上名稱一致 🙌  [ba711b1](https://github.com/readr-media/Sachiel/pull/333/commits/ba711b1969a150c307f291dd9afaf0a20dc11fa2)

2023-03-31 05:26 UTC, ChangRongXuan commented on packages/readr/components/post/subscribe-button.tsx
> +const SubscribeWrapper = styled.section`
此項已修正於 [57956c1](https://github.com/readr-media/Sachiel/pull/333/commits/57956c17f39981be0838e595cbf0e2d8e177049a) 🙌

2023-03-31 05:27 UTC, ChangRongXuan commented on packages/readr/components/post/post-content.tsx
> +      blocks.length === 1
項已修正於 [55da5d5](https://github.com/readr-media/Sachiel/pull/333/commits/55da5d54ea49b656835be57bff9babcc0ad203a6) 🙌

2023-03-31 05:27 UTC, ChangRongXuan commented on packages/readr/components/post/post-content.tsx
> +      <>
此項已修正於 [55da5d5](https://github.com/readr-media/Sachiel/pull/333/commits/55da5d54ea49b656835be57bff9babcc0ad203a6) 🙌

2023-03-31 06:14 UTC, ChangRongXuan commented on packages/readr/components/post/article-type/frame.tsx
> +  z-index: ${({ theme }) => theme.zIndex.articleType};
目前用 2. 方法修改（改為 inherit）
關於 1. 的 相關報導和最新報導的 z-index：100 這個數值我回 @readr-media/react-component 修改一下 ( 拍謝連我自己都沒發現..... :dizzy_face: :face_with_spiral_eyes: 會補上文件＋看數值是否修改為合理一點，以免其他專案用的時候又被干擾到）

2023-03-31 06:17 UTC, ChangRongXuan commented on packages/readr/pages/post/[postId].tsx
> +    case 'news':
此項修正於 [599ba01](https://github.com/readr-media/Sachiel/pull/333/commits/599ba01251b3680453a5226d4e5f8e18bbdc7993)   🙌 ，使用 `ValidPostStyle` 取代 `postData.style`

2023-03-31 06:21 UTC, ChangRongXuan commented on packages/readr/pages/post/[postId].tsx
上述項目修正於 [599ba01](https://github.com/readr-media/Sachiel/pull/333/commits/599ba01251b3680453a5226d4e5f8e18bbdc7993) 中  🙌 

> 需要消除 Ln. 56. data 為 any 的情況

增加 `... client.query<{ post: PostDetail }>({ ....`  設定，定義 `data` type 為 ` { post: PostDetail }`。

> Ln. 51
> let postData, latestPosts
> 在宣告時須指定 type

修正為：
``` 
let postData: PostDetail, latestPosts: Post[]
```

2023-03-31 06:23 UTC, ChangRongXuan commented on packages/readr/components/post/article-type/frame.tsx
> +  .DraftEditor-root {
此項修正於 [7904589](https://github.com/readr-media/Sachiel/pull/333/commits/7904589e6ee7118f5891382d4d3016e309b6a333) 中，感謝提醒 :bowing_woman:

2023-03-31 06:24 UTC, ChangRongXuan commented on packages/readr/components/post/article-type/scrollable-video.tsx
此項修正於 [57956c1](https://github.com/readr-media/Sachiel/pull/333/commits/57956c17f39981be0838e595cbf0e2d8e177049a) 中（覺得這個寫簡潔很多～～感謝建議！！！！）

2023-03-31 07:07 UTC, ChangRongXuan commented on packages/readr/components/post/post-content.tsx
此項於 [55da5d5](https://github.com/readr-media/Sachiel/pull/333/commits/55da5d54ea49b656835be57bff9babcc0ad203a6) 修改，改為：
```
article
  |－ article
  |－ article
  |－ article
   ﹂ article
```

2023-03-31 07:54 UTC, ChangRongXuan commented on packages/readr/pages/post/[postId].tsx
> +    default:
### 調整
- 在 `[postId]`  fetch post 資料時，判斷如果 `data.post` 沒資料會回傳 notFound。
- 增加 `ValidPostStyle` 為 `PROJECT3`、`EMBEDDED`、`REPORT` 的 case 判斷。
- 上述修改紀錄於：[8ecc52a](https://github.com/readr-media/Sachiel/pull/333/commits/8ecc52a42224e118aab8f49849385493c69c9f94)

目前用不同的文章類型做測試，會呈現下方對應的 article-type 呈現：

**其他文章樣式：**（目前需求上以 NEWS 版型呈現即可）
- EMBEDDED： ex:  `/1000` (K6-dev)
- REPORT：ex: `/500` (K6-dev)

**沒有填寫文章樣式**：( 在 READr2.0 如果沒填文章樣式，預設以 NEWS 版型呈現）
- style null：ex: `/1500` (K6-dev)

**不存在的文章**：( 在 READr2.0 如果無該 id 文章，會跳 404 頁面）

2023-03-31 15:52 UTC, erase2004 requested changes

2023-03-31 15:52 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
> +    default:
補一個問題，`draft` 狀態的文章也不應該顯示出來。

2023-04-03 14:33 UTC, ChangRongXuan commented on packages/readr/pages/post/[postId].tsx
> +    default:
目前是透過 `data.post.state !== 'published'` 篩選掉 `published` 以外的文章。[0bcd397](https://github.com/readr-media/Sachiel/pull/333/commits/0bcd397f7b80f04abd105daf057137cca9a1c083)

會跟後端協調看能否修改 `post` 的 `where: PostWhereUniqueInput!` 條件，改透過 `state: { equals: "published" }` 在 query 階段篩選。如後端有做更改，會再發 PR 更換寫法。

2023-04-06 02:39 UTC, erase2004 commented on packages/readr/pages/post/[postId].tsx
> +    default:
如果是這樣子，建議使用的是 `posts` 而不是 `post` 的 query

2023-04-06 02:42 UTC, erase2004 approved these changes
LGTM 👍 
關於一些情況下，文章頁在開發環境下有 hydration error 的問題，或許需要先標註在 README，以便未來再回來處理之類

2023-04-06 02:59 UTC, ChangRongXuan commented
> 關於一些情況下，文章頁在開發環境下有 hydration error 的問題，或許需要先標註在 README，以便未來再回來處理之類

感謝建議！目前先記錄在 `README` 中的「備註」欄位。

2023-04-06 03:00 UTC, merged