feat(category): add `category` page
readr-media/Sachiel pull request #334
Opened 2023-04-06 04:53 UTC by ChangRongXuan

### 新增
- 新增「列表頁」。
- 新增 `/hooks/useInfiniteScroll`，提供「列表頁」、「標籤頁」使用。

### 調整
- 修正：「文章頁」的 category 點擊後改為使用 `slug` 而非 `title`，一併調整相關 graphql 設定。
- 調整  `latestPosts` variable：
   - 新增 `$category` 變數，提供「列表頁」、「標籤頁」無限滾動 fetch data 使用。
   - 當有提供 `$category`，則篩選具有該 `$category` 的 post。
   - 當無提供 `$category`，不針對 category 的內容做篩選（功能同原本的 `latestPosts` ）。

2023-04-07 06:53 UTC, erase2004 requested changes
1. header 的類別導覽列，點擊後，會使類別頁自己的導覽頁切換到目標類別與文章內容
![Snipaste_2023-04-07_14-05-53](https://user-images.githubusercontent.com/1367757/230551473-93ac6425-6286-4fc9-af5b-855d9e22a43f.png)

2023-04-07 06:53 UTC, erase2004 commented on packages/readr/utils/post.ts
> +export const postConvertFunc = (post: Post): ArticleCard => {
`pages/index` 的一併取代？

2023-04-07 06:53 UTC, erase2004 commented on packages/readr/hooks/useInfiniteScroll.ts
> +  Dispatch,
Dispatch, MutableRefObject 和 SetStateAction 應該用 import type

2023-04-07 06:53 UTC, erase2004 commented on packages/readr/hooks/useInfiniteScroll.ts
> +  dependency?: any
dependency 的 type 應該設為 unknown

2023-04-07 06:53 UTC, erase2004 commented on packages/readr/hooks/useInfiniteScroll.ts
> +  }, [element, dependency])
dependency array 的內容應該是 `[dependency, amount]`

2023-04-07 06:53 UTC, erase2004 commented on packages/readr/hooks/useInfiniteScroll.ts
> +  const element = ref.current
element 的初始化與賦值應該在 useEffect 中

2023-04-10 01:20 UTC, ChangRongXuan commented on packages/readr/utils/post.ts
> +export const postConvertFunc = (post: Post): ArticleCard => {
此項於 [a949177](https://github.com/readr-media/Sachiel/pull/334/commits/a949177b18959925ab223b8d423868c7bd508a64) 修正 :raised_hands:

2023-04-10 01:20 UTC, ChangRongXuan commented on packages/readr/hooks/useInfiniteScroll.ts
> +  Dispatch,
此項於 [7ed1599](https://github.com/readr-media/Sachiel/pull/334/commits/7ed1599594215f02e6499b45a2fd4b9d36e49f35) 中修正 :raised_hands:

2023-04-10 01:21 UTC, ChangRongXuan commented on packages/readr/hooks/useInfiniteScroll.ts
> +  dependency?: any
此項於 [7ed1599](https://github.com/readr-media/Sachiel/pull/334/commits/7ed1599594215f02e6499b45a2fd4b9d36e49f35) 中修正 :raised_hands:

2023-04-10 01:21 UTC, ChangRongXuan commented on packages/readr/hooks/useInfiniteScroll.ts
> +  }, [element, dependency])
此項於 [7ed1599](https://github.com/readr-media/Sachiel/pull/334/commits/7ed1599594215f02e6499b45a2fd4b9d36e49f35) 中修正 :raised_hands:

2023-04-10 01:22 UTC, ChangRongXuan commented on packages/readr/hooks/useInfiniteScroll.ts
> +  const element = ref.current
此項於 [7ed1599](https://github.com/readr-media/Sachiel/pull/334/commits/7ed1599594215f02e6499b45a2fd4b9d36e49f35) 中修正 :raised_hands:

感謝更正 :joy: 在寫標籤頁的時候發現用 useInfiniteScroll 會一直出現 element undefined 的錯誤，原來是因為這個原因！

2023-04-10 01:26 UTC, ChangRongXuan commented
### 修正 
- 當點擊 header 分類選項時，會一併更新 category 標籤項目。[f5ae187](https://github.com/readr-media/Sachiel/pull/334/commits/f5ae187d30d0dab013ee7355cbab7d8628f6685b)
- 統一將其他頁面的 `postConvertFunc` 改為自 utils 引入。  [a949177](https://github.com/readr-media/Sachiel/pull/334/commits/a949177b18959925ab223b8d423868c7bd508a64)
- `useInfiniteScroll`：type error /  dependency array 修正。

2023-04-10 04:42 UTC, erase2004 approved these changes
LGTM 👏

2023-04-10 04:42 UTC, erase2004 commented on packages/readr/hooks/useInfiniteScroll.ts
> +      if (ref && entry.isIntersecting) {
應該用 `ref.current`

2023-04-10 04:46 UTC, merged