feat(readr/member): add team members component and cards flip animation
readr-media/Sachiel pull request #336
Opened 2023-04-10 01:48 UTC by bibibobobi

- 於 about page 新增 團隊成員卡片及翻卡動畫，此 pr 僅處理 UI，串接資料及語言切換會於下個 pr 處理。
- 卡片上半部與下半部「相關作品」有分開的 hover 行為。
- 翻卡的事件綁於整張卡片，但在相關作品區域加了 `e.stopPropagation()`，故不會影響相關作品的點擊。
- 目前還沒有作品頁的設計，所以點擊「相關作品」會先連回首頁。

2023-04-13 08:10 UTC, erase2004 requested changes
![Snipaste_2023-04-13_16-09-40](https://user-images.githubusercontent.com/1367757/231696095-2ac8a991-0d56-4826-8103-616c9904214b.png)

2023-04-13 08:10 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +import { members as MembersGql } from '~/graphql/query/member'
應該維持命名風格，使用 `membersGql`

2023-04-13 08:10 UTC, erase2004 commented on packages/readr/pages/about.tsx
>  import { ApolloQueryResult } from '@apollo/client/core'
補修正為 `import type`

2023-04-13 08:10 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +  try {
這邊 try catch 區塊中的 error handle 與前面 try catch 區塊相同，這樣是否放在同一個 try catch 區塊中就可以了？
或者 catch 的處理行為抽出來用一個 function 來處理

2023-04-13 08:10 UTC, erase2004 commented on packages/readr/pages/_error.tsx
> +        <title>{`${pageTitle}｜ Oops, something went wrong`}</title>
提問：頁面標題的文字格式調整為 `[狀態文字] | Oops, something went wrong`？
註：原本的格式是：`[狀態文字] | [SITE_TITLE]`

2023-04-13 08:10 UTC, erase2004 commented on packages/readr/graphql/query/member.ts
> +export type Member = {
`Member` 的內容源自於 `Author`，建議把 Member 增加的內容更新到 `types/common` 中的 `GenericAuthor`，然後在這裡用 `Pick` 或 `Override` 的方式去建立 `Member` type

`Project` 亦同

2023-04-13 08:10 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +  const filterHandler = (id: string) => {
我會建議把 member 資料分類後，顯示時直接直接使用分類後的資料，而不是顯示時還要做 filter 的處理，這樣可以大幅降低計算上的消耗
例如：
```JavaScript
const memberMap = [
  [members_of_type_1], [members_of_type_2], ...
]
```
或者搭配 index 情況下，會是
```JavaScript
const memberMap = {
  index_1: [members_of_type_1],
  index_2: [members_of_type_2],
  ...
}
// 要注意，Object 在遍歷過程中，並不保證順序，需要特別處理
```

2023-04-13 08:10 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +      'front-end engineer': 'Front-end Engineer',
像 `front-end engineer` 這些在 code 裡面重複的 string，又是特定的 key 值，且在 DB 中是 select field 的資料，我會建議參考 `ValidPostStyle` 的方式，將它們用一個 `enum` 變數來管理，降低未來調整上會出錯的可能。

2023-04-13 08:10 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +  const filterHandler = (id: string) => {
弄出一個變數上的另一好處就是顯示實際數字時，如果分類錯了，顯示的數字也會是錯的，不會說只有其中一邊對的情況，因為只需要用 `length` 屬性就可以取得該類別的成員數

2023-04-13 12:35 UTC, bibibobobi commented on packages/readr/pages/_error.tsx
> +        <title>{`${pageTitle}｜ Oops, something went wrong`}</title>
以上已於此 [commit ](https://github.com/readr-media/Sachiel/pull/336/commits/83aaa83c4265085b4e1a745700dd7d5d0b3a2b54)中修正～

2023-04-14 03:51 UTC, bibibobobi commented on packages/readr/components/about/members.tsx
> +  const filterHandler = (id: string) => {
已於此 [commit ](https://github.com/readr-media/Sachiel/pull/336/commits/186eabb0955c157198a058b9ee013a8b909674d7)中修改～

2023-04-14 05:47 UTC, bibibobobi commented on packages/readr/graphql/query/member.ts
> +export type Member = {
已於此 [commit](https://github.com/readr-media/Sachiel/pull/336/commits/ff741cae6ebaac463ab0324aac4ddc41773ee6c5) 中修正

2023-04-14 07:32 UTC, bibibobobi commented on packages/readr/components/about/members.tsx
> +      'front-end engineer': 'Front-end Engineer',
以上皆已修正，感激～

2023-04-15 08:01 UTC, bibibobobi commented
以上問題都已修正，並於 indexFilter 的前方加上` index-` 前綴，以減少僅用數字當 key name 造成的困惑。想請 @erase2004 有空再幫我看看～感激

2023-04-16 07:14 UTC, erase2004 requested changes

2023-04-16 07:14 UTC, erase2004 commented on packages/readr/graphql/query/member.ts
> +export type Member = Override<
搭配 `Pick`，選取使用到的 field，這樣產生 `Member` 不會因為 `GenericAuthor` 增加新的 field，導致也跟著一起被增加

2023-04-16 07:14 UTC, erase2004 commented on packages/readr/types/common.ts
> +  isMember?: boolean
`?` 可以不用，因為使用時會搭配 `Pick`，因此使用端不會因為上游增加 field，也跟著一起變動

2023-04-16 07:14 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +    const [awardsResult, pageVariablesResult, membersResult] =
`awardsResult`, `pageVariablesResult`, `membersResult` 這幾個 type 都是 `ApolloQueryResult<any>`，
請參考其他 `client.query`，讓它們不有 any

2023-04-16 07:14 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +  const positionTranslations: {
type 可以調整為 `Record<string, Record<ValidJobTitles, string>>`，不過因為是複合的 type，
建議先建立額外的 type 來處理，而不是用 inline 的方式描述

2023-04-16 07:14 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +      positionTranslations[language]?.[position as ValidJobTitles] ?? position
會需要一個 function，使用 type guard 的方式，讓 position 能夠被檢查是不是 `ValidJobTitles` type，而不是用 as 的方式來處理
ref: [Indexing objects in TypeScript](https://dev.to/mapleleaf/indexing-objects-in-typescript-1cgi)

2023-04-16 07:14 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +  const filterByJobTitles = (members: Member[], jobTitles: string[]) => {
其實這部份處理的調整，還是沒有達成「避免每次切換類別時，都要對整個 member list 跑 fitler 的問題」
origin: https://github.com/readr-media/Sachiel/pull/336#discussion_r1165145071

處理上應該把資料都先分類好，選分類時，只要拿已經分類好的其中一小塊就好了

2023-04-17 00:58 UTC, bibibobobi commented on packages/readr/types/common.ts
> +  isMember?: boolean
以上已於此 [commit](https://github.com/readr-media/Sachiel/pull/336/commits/224e37fe1e0c74c93e2774c20f60a02faea0bcbc) 中修正

2023-04-17 01:47 UTC, bibibobobi commented on packages/readr/pages/about.tsx
> +    const [awardsResult, pageVariablesResult, membersResult] =
[已修正](https://github.com/readr-media/Sachiel/pull/336/commits/1f13ba13fc299058ba3e0a400d3a47f318068154)～

2023-04-17 16:44 UTC, bibibobobi commented on packages/readr/components/about/members.tsx
> +  const filterByJobTitles = (members: Member[], jobTitles: string[]) => {
在這個 [commit](https://github.com/readr-media/Sachiel/pull/336/commits/4ac868f858ca3aa15810c0f3da64c5a4967d196a) 新增了一個 function 來確認傳入的 position 是不是 ValidJobTitles

2023-04-17 16:45 UTC, bibibobobi commented on packages/readr/components/about/members.tsx
> +      positionTranslations[language]?.[position as ValidJobTitles] ?? position
在這個 [commit](https://github.com/readr-media/Sachiel/pull/336/commits/4ac868f858ca3aa15810c0f3da64c5a4967d196a) 新增了一個 function 來確認傳入的 position 是不是 ValidJobTitles

2023-04-18 03:33 UTC, bibibobobi commented on packages/readr/components/about/members.tsx
> +  const filterByJobTitles = (members: Member[], jobTitles: string[]) => {
在此 [commit ](https://github.com/readr-media/Sachiel/pull/336/commits/da7a3fd30c0d37a787728694cf5ca30dbdda771e) 將 count 及 filtered members array 存入 indexData，避免每次切換類別都重新計算的問題。

2023-04-18 04:53 UTC, erase2004 requested changes
修改方向大致是正確的，只是一般資料會和頁面變動所響應的 state 混為一談，所以導致額外使用非必要的 state 來處理

2023-04-18 04:53 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +    return Object.values(ValidJobTitles).includes(position as ValidJobTitles)
```TypeScript
return Object.values(ValidJobTitles).includes(position as ValidJobTitles)
```
這一段只需要用
```TypeScript
return position in Object.values(ValidJobTitles)
```
處理就好了，因為 `in` 可以作為 type guard 操作使用

2023-04-18 04:53 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +  const [indexData, setIndexData] = useState<
`indexData` 不必是 state，是一般 array 就好了，因為頁面的 state 對象是 `filteredMembers`，而不是 `indexData`

2023-04-18 04:53 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +    Array<{ position: string; count: number; id: string; members: Member[] }>
把 Array 中的內容抽出來用一個 type 表示，然後用 type[] 的型式處理

2023-04-18 04:53 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +  useEffect(() => {
不需要 useEffect 來處理這一段

2023-04-18 04:53 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +    const indexFilterLengths: { [key: string]: number } = {}
`indexFilterLengths` 其實是多餘的，只需要用 `indexFilterArrays[index].length` 的方式就可以取得 count 所需資訊

2023-04-18 05:40 UTC, bibibobobi commented on packages/readr/components/about/members.tsx
> +    Array<{ position: string; count: number; id: string; members: Member[] }>
已移除此 useState

2023-04-18 06:07 UTC, bibibobobi commented on packages/readr/components/about/members.tsx
> +    return Object.values(ValidJobTitles).includes(position as ValidJobTitles)
改寫成這樣的話，似乎會把 key 傳進 position，沒辦法做到 format 及 translate position，在想到原因前，這邊我先維持原寫法喔 > <
<img width="739" alt="Screen Shot 2023-04-18 at 2 02 45 PM" src="https://user-images.githubusercontent.com/66411169/232686084-97e161c9-df2a-455a-afdb-9fbe2fa3c583.png">

2023-04-18 07:15 UTC, erase2004 commented on packages/readr/components/about/members.tsx
> +    return Object.values(ValidJobTitles).includes(position as ValidJobTitles)
修正一下建議，調整為
```TypeScript
return Object.values<string>(ValidJobTitles).includes(position)
```

2023-04-18 07:16 UTC, erase2004 approved these changes
LGTM 🥳 👏

2023-04-18 07:19 UTC, bibibobobi commented on packages/readr/components/about/members.tsx
> +    return Object.values(ValidJobTitles).includes(position as ValidJobTitles)
原來如此，感激～～

2023-04-18 07:22 UTC, merged