feat(readr/about): add QA section and fetch data
readr-media/Sachiel pull request #362
Opened 2023-04-20 08:33 UTC by bibibobobi

- 新增 `EDITOOLS_API_ENDPOINT` 環境變數，於 SSR `getSeverSideProps` 時使用。
- 由於是抓特定 id 的 qALists，又必須區分中英文版本，為了方便管理，跟 PM 討論過後，決定統一抓 prod CMS 資料，根據不同ENV 環境決定抓取哪一筆資料。在 `local` 及 `dev` 環境，抓取 `id: '8'`（英文）, `id:'9'`（中文）；在 `staging` 及 `prod` 環境，抓取 `id: '6'`（英文）, `id:'7'`（中文）資料。
- 原本打算使用 `@readr-media/react-qa-list` 套件，但會一直出現 `TypeError: Cannot read property 'useDebugValue' of null`錯誤訊息，查詢過後似乎是 React hook 版本相容性的問題。若直接貼上 embedded code 也會有 layout 無法相容的問題，所以目前使用的暫時方法是把 react-qa-list component 整個資料夾搬過來用，若之後套件更新，可以再換回來。

2023-04-20 10:58 UTC, erase2004 requested changes

2023-04-20 10:58 UTC, erase2004 commented on packages/readr/README.md
> +| EDITOOLS_API_ENDPOINT | 字串      | ''                       | GraphQL API 端點                                 |
變數說明和前者 `API_ENDPOINT` 做一些區別

2023-04-20 10:58 UTC, erase2004 commented on packages/readr/apollo-editools-client.ts
就檔案命名來講，應該是 `edittools-apollo-client` ，不然用 `editools-client` 也可以 🤔

2023-04-20 10:58 UTC, erase2004 commented on packages/readr/graphql/query/qa.ts
> +  content: string
我記得 `content` 是 draft-js 的 JSON，不過要表示 JSON type 過於複雜，這時候可以用 `unknown`，
如這個案例中所示
https://github.com/readr-media/Sachiel/blob/202ea72956d3418970cefc5accf836ce592ffd05/packages/readr/graphql/query/page-variable.ts#L14

2023-04-20 10:58 UTC, erase2004 commented on packages/readr/pages/about.tsx
> +    const variables =
我會比較偏好把這一段放在 `constants/environment-variables` 中，輸出一個變數來處理，例如：`QA_RECORD_CONFIG`

2023-04-20 10:58 UTC, erase2004 commented on packages/readr/components/readr-media-qaLists-components/index.js
因為是從 `@readr-media/react-qa-list` 中搬移過來的，建議標注搬移的套件與版本資訊，以便未來做相關更新處理。

2023-04-20 10:58 UTC, erase2004 commented on packages/readr/components/readr-media-qaLists-components/list/qa-card.js
> +  font-family: 'Noto Sans CJK TC', sans-serif;
`Noto Sans CJK TC` 沒有作用，看是不是要調整為 `Noto Sans TC`，或者增加 `Noto Sans TC` 在 `Noto Sans CJK TC` 後面。

2023-04-20 10:58 UTC, erase2004 commented on packages/readr/components/readr-media-qaLists-components/list/qa-list.js
> +const ListTitle = styled.h2`
這一個雖然顯示沒有內容，但有顯示於 DOM 當中，然而在這一個區塊，因為上層已經用 `<h2/>` 了，所以請降級到 `<h3/>` 之類

2023-04-20 11:49 UTC, bibibobobi commented on packages/readr/graphql/query/qa.ts
> +  content: string
以上已於此 [commit ](https://github.com/readr-media/Sachiel/pull/362/commits/9e18a5a61625ef559b25e2a5e0f94b6d4b79bde3)中修改～

2023-04-20 14:58 UTC, bibibobobi commented on packages/readr/components/readr-media-qaLists-components/list/qa-list.js
> +const ListTitle = styled.h2`
以上套件相關已於此 [commmit ](https://github.com/readr-media/Sachiel/pull/362/commits/4eb4b4ba9aca3fe9e74e2278400e9d0e563bb6da)修正～

2023-04-21 02:21 UTC, erase2004 requested changes

2023-04-21 02:21 UTC, erase2004 commented on packages/readr/components/about/qa.tsx
> +  const questions = language === 'ch' ? qaLists[1]?.items : qaLists[0]?.items
應該還是會報錯，會需要 `[]` 當作最終的 fallback value

2023-04-21 02:21 UTC, erase2004 commented on packages/readr/constants/environment-variables.ts
> +const QA_RECORD_CONFIG = {
放進對應的 switch case 區塊吧

2023-04-21 04:02 UTC, bibibobobi commented on packages/readr/constants/environment-variables.ts
> +const QA_RECORD_CONFIG = {
以上[已修正](https://github.com/readr-media/Sachiel/pull/362/commits/db4d986d15326df55d30ad444bd88c95eb65fbd3)～

2023-04-21 06:06 UTC, erase2004 approved these changes
LGTM 👏

2023-04-21 06:06 UTC, erase2004 commented on packages/readr/components/about/qa.tsx
> +    language === 'ch' ? qaLists[1]?.items || [] : qaLists[0]?.items || []
應該用就可以了
```TypeScript
const questions = (language === 'ch' ? qaLists[1]?.items : qaLists[0]?.items) ?? []
```

2023-04-21 06:11 UTC, merged