feat(mesh): add mesh project
readr-media/Sachiel pull request #758
Opened 2024-04-23 15:16 UTC by caesarWHLee

# Base setup

1. use tailwindcss
2. add normalize css
3. update html lang
4. add env variables
5. setup next.config.mjs
6. set min node version
7. add /api/robots together with next.config.rewrites to handle robots.txt
8. add apollo client

## Document
Convention 初版[文件](https://paper.dropbox.com/doc/Convention--CNzgsPmJonaQAB42iFSK8czLAg-yDGKaFsVLerISYtxFlM9e)，待討論後定案。

2024-04-23 16:30 UTC, erase2004 requested changes

2024-04-23 16:30 UTC, erase2004 commented on packages/readr/package.json
> +    "node": ">=18.17.0"
調整為 `>=18.16.0`，或者調整 dockerfile 所使用的 Node.js 版本，不過後者需要檢驗一下既有 package 是否會有問題

2024-04-23 16:30 UTC, erase2004 commented on packages/mesh/tsconfig.json
> +    "moduleResolution": "bundler",
這裡使用 `bundler` 的原因？
btw, Next.js 這邊的範例都是用 `node`

2024-04-23 16:30 UTC, erase2004 commented on packages/mesh/tsconfig.json
> +      "@/*": ["./*"]
相對路徑會用 `@` 來作為起始？

2024-04-23 16:30 UTC, erase2004 commented on packages/mesh/styles/normalize.css
Tailwind 自帶 normalization，不用額外設定這部份
ref: https://tailwindcss.com/docs/preflight

2024-04-23 16:30 UTC, erase2004 commented on packages/mesh/postcss.config.js
可以上 production optimization 設定
ref: https://tailwindcss.com/docs/optimizing-for-production

2024-04-23 16:30 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +import '@/styles/normalize.css'
normalize.css 移除後，可以改用 global.css 的命名

2024-04-23 16:30 UTC, erase2004 commented on packages/mesh/README.md
README 補上網站名稱

2024-04-24 01:16 UTC, tyc67 commented on packages/mesh/tsconfig.json
> +    "jsx": "preserve",
建議設定 `"jsx": "react"`

2024-04-24 01:34 UTC, tyc67 commented on packages/mesh/tsconfig.json
> +    ],
-這邊應該不用plugin  [TS DOC](https://www.typescriptlang.org/tsconfig#plugins)
-可以考慮加`"forceConsistentCasingInFileNames": true`   [TS DOC](https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames)

2024-04-24 01:50 UTC, tyc67 commented on packages/mesh/tailwind.config.js
> +  ],
-建議考慮加`html` [Tailwind DOC](https://tailwindcss.com/docs/content-configuration)

2024-04-24 02:15 UTC, erase2004 commented on packages/mesh/tsconfig.json
> +    ],
> -這邊應該不用plugin [TS DOC](https://www.typescriptlang.org/tsconfig#plugins)

這個 plugin 其實是有用途的，只是 Sachiel 的 global node_modules 底下的 TypeScript 版本還是 `4.8.4`，所以沒產生效果，如果調整 VSCode 設定如下
```json
{
  "typescript.tsdk": "packages\\mesh\\node_modules\\typescript\\lib"
}
```
reload 畫面後，便會產生效果了
![Snipaste_2024-04-24_10-13-14](https://github.com/readr-media/Sachiel/assets/1367757/95d2c45a-7d04-45c1-8c3d-ac306e1e467d)


ref: https://nextjs.org/docs/app/building-your-application/configuring/typescript#typescript-plugin

2024-04-24 02:21 UTC, tyc67 commented on packages/mesh/constants/environment-variables.ts
有沒有考慮用 `env. development `,`env.production` 儲存環境變數呢? [NEXT DOC](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#default-environment-variables)

2024-04-24 02:26 UTC, caesarWHLee commented on packages/readr/package.json
> +    "node": ">=18.17.0"
新版的 next.js 要求使用 18.17.0 以上，[文件](https://nextjs.org/docs/getting-started/installation)，還是要把各個 package 各自管理 Dockerfile 以免影響到其他 package ?

2024-04-24 02:28 UTC, erase2004 commented on packages/mesh/constants/environment-variables.ts
這檔案嚴格來講，不是 .env 這類動態調整的內容，
而是依照 NEXT_PUBLIC_ENV 數值，在編譯時寫入的固定且非敏感資訊，因此可以上 git，
如果是 .env 這類，需要另外開的 repo 來存放，並調整既有 CI/CD 處理

2024-04-24 02:34 UTC, erase2004 commented on packages/readr/package.json
> +    "node": ">=18.17.0"
那就其他 package 也升上 18.17 測試看看 (目前看起來只有 politics-tracker 需要測試一下)

2024-04-24 02:40 UTC, caesarWHLee commented on packages/mesh/tsconfig.json
> +    "moduleResolution": "bundler",
這邊的值是 create-next-app 直接產生，不過看了一下[文件](https://www.typescriptlang.org/tsconfig#moduleResolution)，`node` (or `node10`) 是給 Node v10 以前的版本使用，要改的話應該也是改成 `nodenext` ?

2024-04-24 02:46 UTC, tyc67 commented on packages/mesh/tsconfig.json
> +    ],
了解, ref link 說也可以直接用VSCode設定。Typescript 4.84版有支援，可參考 [Youtube](https://www.youtube.com/watch?v=pqMqn9fKEf8)

2024-04-24 02:48 UTC, caesarWHLee commented on packages/mesh/tsconfig.json
> +    "jsx": "preserve",
設置成 react 在起 dev server 的時候會被 next.js 改 preserve，看來 next.js 希望不要透過 typescript 來處理 jsx 語法

```
   We detected TypeScript in your project and reconfigured your tsconfig.json file for you. Strict-mode is set to false by default.
   The following mandatory changes were made to your tsconfig.json:

        - jsx was set to preserve (next.js implements its own optimized jsx transform)
```

2024-04-24 02:50 UTC, caesarWHLee commented on packages/mesh/tsconfig.json
> +      "@/*": ["./*"]
對，目前的預設行為，要統一改成 `~` 也可以，定好一致的 convention 就好

2024-04-24 02:59 UTC, erase2004 commented on packages/mesh/tsconfig.json
> +    "moduleResolution": "bundler",
well, Next.js 的 package.json 沒有設定 "type": "module"，所以預設是用 cjs，如果要調整為 ESM，嘛，有不少東西要跟著一起調，你可以試一下來驗證有多少錯誤跑出來

2024-04-24 03:04 UTC, tyc67 commented on packages/mesh/constants/environment-variables.ts
了解, 我看檔名有點誤會。我想建議可以考慮將檔名改為 `api-endpoint.ts`，這樣和 `.env` 可以有區別，增加可讀性。

2024-04-24 03:07 UTC, erase2004 commented on packages/mesh/constants/environment-variables.ts
檔案開頭加上說明的註解應該就可以

2024-04-24 03:13 UTC, caesarWHLee commented on packages/mesh/tailwind.config.js
> +  ],
next.js app router 應該是不會有直接編輯 html 副檔名的地方？
目前設置參考 [Tailwind next.js guide](https://tailwindcss.com/docs/guides/nextjs)

2024-04-24 03:21 UTC, caesarWHLee commented on packages/mesh/constants/environment-variables.ts
關於環境變數的放法可以在討論一下，因為 app router 可以透過 server action 來處理 client side 的 request，這樣會需要透過 NEXT_PUBLIC_ENV expose 到 client side 的資訊相對會少很多，而如果我們是以統一在 server side 發 request 的 convention 的話看要不要把 api_endpoint 的值放回去 .env 裡面。

原本這個檔可能還是會隨著開發新增更多的靜態設定值，可以參考[週刊3.0](https://github.com/mirror-media/Adam/blob/dev/packages/mirror-media-next/config/index.mjs) 會比較有感覺，檔案的命名部分可以比照其他 project 調整成 config.ts，以便和 .env 裡面存的環境變數區隔，目前這邊的命名是想對齊同 monorepo 下命名方式，

2024-04-24 03:25 UTC, erase2004 commented on packages/mesh/constants/environment-variables.ts
但你 Firebase config 之類的，因為是要輸出到 browser 頁面上，所以還是要在 build 時就寫入，無法依靠 runtime 設定，因此還是會需要一個依照環境差異，在 build time 寫入的設定檔

2024-04-24 04:15 UTC, caesarWHLee commented on packages/mesh/constants/environment-variables.ts
對，所以應該是兩者併行，server 才會用到的敏感資料就放到 .env，不敏感 or 必須 expose 到 client side 就維持在 config.ts 上

2024-04-24 04:16 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
> +import '@/styles/normalize.css'
感謝建議，已在 commit [226c982](https://github.com/readr-media/Sachiel/pull/758/commits/226c98265e70ac37115aafee95542d9789b27454) 上更新。

2024-04-24 04:16 UTC, caesarWHLee commented on packages/mesh/styles/normalize.css
感謝建議，已在 commit [226c982](https://github.com/readr-media/Sachiel/pull/758/commits/226c98265e70ac37115aafee95542d9789b27454) 上更新。

2024-04-24 04:26 UTC, caesarWHLee commented on packages/mesh/postcss.config.js
感謝建議，已在 commit [ea442d1](https://github.com/readr-media/Sachiel/pull/758/commits/ea442d1e7406357d969ef4c7013ddd02fa5c6265) 上設定。

2024-04-24 04:42 UTC, caesarWHLee commented on packages/mesh/tsconfig.json
> +    ],
是說 vscode 上我需要裝什麼 extension 先嗎，因為你們兩個的方法我都試過，但看不到任何的 hover information XD

2024-04-24 04:45 UTC, caesarWHLee commented on packages/mesh/README.md
已補在 commit [ab2ee53](https://github.com/readr-media/Sachiel/pull/758/commits/ab2ee536184cb87f3177ad575f18a3b800ba4ce3)，詳細的文件等 convention 確定後再來補上。

2024-04-24 05:29 UTC, caesarWHLee commented on packages/mesh/tsconfig.json
> +    "moduleResolution": "bundler",
package.json 設定 "type": "module" 會導致編譯報錯，看起來是 webpack loader 要調整。

是說好奇問一下 moduleResolution 設定成 `nodenext` or `bundler` 有一定要把 package.json 設定為 "type": "module" 嗎？ 因為看[文件](https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution) nodenext 實際上是 support CJS 和 ESM ?

2024-04-24 05:30 UTC, caesarWHLee commented on packages/readr/package.json
> +    "node": ">=18.17.0"
測試方式是指直接更新 Dockerfile 看其他 package 有沒有正常的運作嗎？

2024-04-24 05:41 UTC, tyc67 commented on packages/mesh/tsconfig.json
> +    ],
試試看重開VSCode , ` Cmd + P ` -> `"TypeScript: Restart TS Server".` 有沒有幫助

2024-04-24 06:27 UTC, caesarWHLee commented on packages/mesh/tsconfig.json
> +    ],
有了，發現要先 Select TypeScript Version 選到 Use Workspace Version 4.8.4 之後再去改 .vscode/settings.json，改成
```
{
  "typescript.tsdk": "packages/mesh/node_modules/typescript/lib"
}
```

然後再 Select TypeScript Version 一次選成 Use Workspace Version 5.4.5 就可以了，原本我是使用 Use VS Code's Version 5.4.5，難怪沒有 😅 。

不過這樣設定的話整個 monorepo 的設定都會導向 mesh 的 typescript 版本，不確定其他 pakages 開發會不會有問題。

> -這邊應該不用plugin [TS DOC](https://www.typescriptlang.org/tsconfig#plugins)
最後回應一下這個 plugin 也是 next.js 預設要放的，拿掉的話跑 yarn dev 會再被加回來XD

2024-04-24 12:50 UTC, caesarWHLee commented on packages/mesh/tsconfig.json
> +    "moduleResolution": "bundler",
根據 huddle 套論後結論改回使用 "node" 來使用預設 commonJs 的方式，改動在 [3a28736](https://github.com/readr-media/Sachiel/pull/758/commits/3a28736aec5abf6e05a5b45a9512afbf9042c4c7)

2024-04-24 13:49 UTC, caesarWHLee commented on packages/readr/package.json
> +    "node": ">=18.17.0"
經過測試其他的 package 都可以在 node v18.17.0 的環境下正常運行，在 commit [e0014af](https://github.com/readr-media/Sachiel/pull/758/commits/e0014af6625e4da49bbf520d2ae8a6ab223dc7ae) 中更新各 package.json 中的 engines、在 commit [7f210f4](https://github.com/readr-media/Sachiel/pull/758/commits/7f210f478ecd8ccd93e948a3a69673921a1b5e88) 中更新 dockerfile node version 為 18.17.0

2024-04-24 14:05 UTC, caesarWHLee commented
[633b5b1](https://github.com/readr-media/Sachiel/pull/758/commits/633b5b133c31e99f0b256f77ed5720426a6021b3) 新增 prettier，比照政見追蹤平台的版本，避免 plugin 衝突

2024-04-24 15:32 UTC, erase2004 approved these changes
README 增加到
https://paper.dropbox.com/doc/Mesh-web--CN2DrFEpAkUpluVXgc9LawafAg-IKnh8OyzeYAa988YljLX2
此文件的資訊

2024-04-25 03:39 UTC, caesarWHLee commented
[10b4585](https://github.com/readr-media/Sachiel/pull/758/commits/10b45855bc2a24c614cced1993449b9f9882a1b0) 新增專案連結到 README.md

2024-04-25 03:39 UTC, merged