refactor(mesh): update rwd layout
readr-media/Sachiel pull request #759
Opened 2024-05-02 02:24 UTC by caesarWHLee

# Notable Change

1. use `next/font/google` to setup Noto Sans TC font
2. add tailwind-merge to handle classname combination
3. setup breakpoints in tailwind config.js
4. build rwd layout

follow-up:
Layout 中的 header, footer, aside, nav 和 main 等 element 會被封裝到各自的 component 中，這邊只是依照設計稿把各個區塊會產生的變化用直觀的方式呈現。

2024-05-02 04:23 UTC, erase2004 requested changes

2024-05-02 04:23 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +          <div className="mx-auto h-full max-w-[1440px]">這是 header</div>
你可以加上 JSX comment 標註區塊
ref: [add-comments-in-jsx.english.md](https://github.com/Manish-Giri/FreeCodeCamp/blob/master/curriculum/challenges/english/03-front-end-libraries/react/add-comments-in-jsx.english.md#solution)

2024-05-02 04:23 UTC, erase2004 commented on packages/mesh/app/page.tsx
> +import Image from 'next/image'
目前尚未用到

2024-05-02 04:23 UTC, erase2004 commented on packages/mesh/tailwind.config.js
> +        15: '3.75rem',
用 15 其實當作 key 其實很意義不足，很不直觀

2024-05-02 04:23 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +    <html lang="zh-Hant" className={twMerge('h-full', notoSans.className)}>
html tag 上字型設定還可以理解，但上 style 就沒有效果

2024-05-02 04:23 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +      <body className="h-full pt-15 pb-16 sm:pl-32 sm:pt-16 sm:pb-0 md:pl-[220px] xl:pl-[calc((100vw-1440px)/2+320px)]">
過於複雜，body 應該是整個畫面的基底，`min-h-screen w-screen` 之類的比較合理

2024-05-02 04:23 UTC, erase2004 commented on packages/mesh/app/layout.tsx
![layout](https://github.com/readr-media/Sachiel/assets/1367757/9cfa5ba8-84f0-4a02-8eb8-e9bc0996d921)
layout 應該設計成這樣子，另外，須留意 layout 和 template 的差異，確認要的是 layout 還是 template
ref: https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates

2024-05-02 04:23 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +        <aside className="fixed left-0 top-16 hidden h-[calc(100%-64px)] w-32 border sm:block md:w-[220px] xl:w-[calc((100vw-1440px)/2+320px)] ">
`1440px` 這個看起來是某個區塊的寬度，應該可以寫到 tailwind config 中，然後用 `theme()` 的方式去引用數值
ref: https://tailwindcss.com/docs/functions-and-directives#theme

2024-05-02 05:14 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
> +    <html lang="zh-Hant" className={twMerge('h-full', notoSans.className)}>
html 設定 height:100% 有效果，會是實際 viewport 的大小， body 的 height: 100% 也是看 html 的值 (目前在 chrome, safari 上測試都是這個行為）

2024-05-02 05:27 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
> +      <body className="h-full pt-15 pb-16 sm:pl-32 sm:pt-16 sm:pb-0 md:pl-[220px] xl:pl-[calc((100vw-1440px)/2+320px)]">
h-screen 對應到的 css 會是 100vh，這個值在 mobile 的狀況下會被瀏覽器的導覽列給佔用，而沒辦法取得最終的可見高度，所以才設計成從 html, body 一路設置 height: 100% 來得到實際高度，以供子 element 設定其高度」。

另外 aside 的效果是需要 fixed 在螢幕左邊，故而直接透過 fixed 設定，body 直接透過 padding 把 fixed 的空間給預留 (header, table:aside, mobile:nav)，因此才會這麼複雜。

建議可以透過 debug tool 實際看過各個螢幕寬度的顯示比例會比較容易理解目前的設計方式，不過有更簡潔的寫法也可以提出來，感謝。

2024-05-02 05:32 UTC, caesarWHLee commented on packages/mesh/tailwind.config.js
> +        15: '3.75rem',
15 主要是要補足 tailwind 預設沒有 h-15 但有 h-14, h-16 的值，計算方式是一樣的。

2024-05-02 06:27 UTC, erase2004 commented on packages/mesh/app/layout.tsx
https://github.com/readr-media/Sachiel/pull/759#discussion_r1587070280
https://github.com/readr-media/Sachiel/pull/759#discussion_r1587079588
一起講好了
* 現在只要 body 設定 min-height 就有效果了，如果要針對 mobile browser 的 UI 處理的話，可以用套 `dvh`，再 fallback 回 vh
ref:
1. https://www.freecodecamp.org/news/html-page-width-height/ **The Modern Solution is Simplified**
2. https://www.linkedin.com/pulse/use-svh-dvh-instead-vh-moeed-khan-0blaf/
* 左邊那塊屬性按照設計稿是 nav 不是 aside，功能是作導覽
3. 另外，如果是 main + footer 因高度超過 100vh 產生捲動，那應該在這個區塊做 overflow 及 scroll 的處理，其他區塊就未必要 `postion: fixed`

2024-05-02 06:35 UTC, caesarWHLee commented
補充一下目前的寫法，會在 header, footer, aside, nav, main 中再新增 div 主要是在處理螢幕寬度超過 1440 的時候頁面變化是由 1440 寬度兩側往外長寬的設計，因為長寬的時候會需要各個 element 各自處理寬度變化，所以透過多一層的 div 來固定原本 element 的寬度。

2024-05-02 06:36 UTC, caesarWHLee commented on packages/mesh/app/page.tsx
> +import Image from 'next/image'
已在 [76101c8](https://github.com/readr-media/Sachiel/pull/759/commits/76101c885a5a595fe397d139e5c4eb1df60f0dd6) 中刪除

2024-05-02 06:40 UTC, tyc67 commented on packages/mesh/app/layout.tsx
> +      <body className="h-full pt-15 pb-16 sm:pl-32 sm:pt-16 sm:pb-0 md:pl-[220px] xl:pl-[calc((100vw-1440px)/2+320px)]">
不知道能不能在 <body> 用 `flex-1` 設定 ?  (可以減少 twMerge dependency)

2024-05-02 07:04 UTC, erase2004 commented
> 補充說明一下目前的寫法，會在 header, footer, aside, nav, main 中再新增 div 主要是在處理螢幕寬度超過 1440 的時候頁面變化是由 1440 寬度兩側往外長寬的設計，因為長寬的時候會需要各個 element 各自處理寬度變化，所以透過多一層的 div 來固定原本 element 的寬度。

這裡應該只需要
```Html
<body>
  <header>
    <div /> <!-- header content (max-width: 1440px) -->
  </header>
  <div> <!-- container (max-width: 1440px) -->
    <nav /> <!-- left part -->
    <div class="main-and-footer"> <!-- container for main and footer -->
      <main />
      <footer />
    <div />
    <aside /> <!-- optional, not used in latest or popular page -->
  </div>
```
這樣的結構，然後在 `div.main-and-footer` 做出 `overflow-y: scroll` 的效果，
`<nav />` 和 `<aside />` 用上 `flex-1 grow-1` 並設定 `basis`，讓彼此自動等效長寬

2024-05-02 07:56 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
> +      <body className="h-full pt-15 pb-16 sm:pl-32 sm:pt-16 sm:pb-0 md:pl-[220px] xl:pl-[calc((100vw-1440px)/2+320px)]">
`flex: 1;` 會需要 parent 設定 `display: flex` 一樣會需要在 html 上面設定 css，還是會需要 twMerge，如果真的要省的話就是直接當字串處理。

2024-05-02 08:03 UTC, caesarWHLee commented
> 
> 補充說明一下目前的寫法，會在 header, footer, aside, nav, main 中再新增 div 主要是在處理螢幕寬度超過 1440 的時候頁面變化是由 1440 寬度兩側往外長寬的設計，因為長寬的時候會需要各個 element 各自處理寬度變化，所以透過多一層的 div 來固定原本 element 的寬度。
> 
> 這裡應該只需要
> 
> ```
> <body>
>   <header>
>     <div /> <!-- header content (max-width: 1440px) -->
>   </header>
>   <div> <!-- container (max-width: 1440px) -->
>     <nav /> <!-- left part -->
>     <div class="main-and-footer"> <!-- container for main and footer -->
>       <main />
>       <footer />
>     <div />
>     <aside /> <!-- optional, not used in latest or popular page -->
>   </div>
> ```
> 
> 這樣的結構，然後在 div.main-and-footer 做出 overflow-y: scroll 的效果，
> <nav /> 和 <aside /> 用上 flex-1 grow-1 並設定 basis，讓彼此自動等效長寬
> 

`<div> <!-- container (max-width: 1440px) -->` 不能設定 max-width: 1440px，因為其中的 left nav、main 和 footer 都會需要在超過 1440 寬度的時候去平分左右多出來的間隔，同時又要保留他們的底色，nav 需要需要長白色、footer 需要長白色、main 需要依照頁面的底色來長，社群頁就會是灰色往右邊長。

2024-05-02 09:14 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
關於高度的問題，原本是想說 dvh 支援度還不夠高(92.54%)所以先使用了從 html 去取得 viewport 高度一路下傳的設計，要直接使用也是可以，不過好像可以來定一下 can i use 上面的要到多少的支援度才能使用的 convention。

aside 改命名為 nav 已修正在 [61d4aec](https://github.com/readr-media/Sachiel/pull/759/commits/61d4aece228a4ab80b2b30fd142cee5b5a0ae991)，基本上兩個 nav 對應到不同的螢幕寬度，左側 nav 顯示於平板以上的螢幕寬度，而置底的 nav 只顯示於手機的寬度。

另外目前的理解是 header, nav bar 因為都是固定在畫面之中，位置不會改變，所以使用 `position: fixed` 搭配由 body 設置 padding 來預留 fixed 的位置，main, footer 則直接使用 body content block 中的範圍，這個方式和你建議的作法上感覺只是風格不同，應該是等效的，還是說會有其他效能上的考量嗎？

2024-05-02 10:26 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
目前已移除 html 上 `height: 100%;`，body 修改成 `min-height: 100vh; min-height: 100dvh;` (透過 tailwind.config.js 設定 fallback)，main min-height 對應調整，修改於 [e342d44](https://github.com/readr-media/Sachiel/pull/759/commits/e342d44af8d6854c47e935cb0419fb40182ad529)。

2024-05-02 11:23 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
> +        <aside className="fixed left-0 top-16 hidden h-[calc(100%-64px)] w-32 border sm:block md:w-[220px] xl:w-[calc((100vw-1440px)/2+320px)] ">
改動在 [160a56b](https://github.com/readr-media/Sachiel/pull/759/commits/160a56bd5146871323c9d3aa2b835641e3977d7c)，是說好奇問一下這樣的話會不會造成 tailwind.config.js 越來越肥大？

2024-05-03 08:42 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
根據中午的討論，保持 header, nav, footer 中透過 nested div 的方式來控制螢幕尺寸超過 1440px 的元件寬度，修改 body 上設定 padding 的做法，main 修改成 div 將 div.main-and-aside 和 footer 包在其中並設定 padding，main 改由各頁面的 page.tsx 來控制，讓有 aside 的頁面可以區隔 main 和 aside 區塊，改動在 [726244f](https://github.com/readr-media/Sachiel/pull/759/commits/726244f85c849e9c6a9de069af120efbfbde2e26)。

2024-05-05 17:11 UTC, erase2004 requested changes

2024-05-05 17:11 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +        <header className="fixed top-0 left-0 h-[theme(height.header.default)] w-full border bg-white sm:h-[theme(height.header.sm)]">
`border` 換成 `border-b`
`w-full` 換成 `right-0`

2024-05-05 17:11 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +        <div className="border bg-gray-50 pb-[theme(height.nav.default)] pt-[theme(height.header.default)]  sm:pb-0 sm:pt-[theme(height.header.sm)] sm:pl-[theme(width.nav.sm)] md:pl-[theme(width.nav.
應該不用 border，border 設在 header, nav 和 footer 上就好了

2024-05-05 17:11 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +          <div className="mr-auto min-h-[calc(100dvh-theme(height.header.default)-theme(height.footer.default)-theme(height.nav.default))] max-w-[theme(width.maxMain)] sm:min-h-[calc(100dvh-theme(hei
在 parent 用 `d-flex flex-col`，在這一層用 `grow` 的話，就不用再計算高度了

2024-05-05 17:11 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +          <footer className="h-[theme(height.footer.default)] border bg-white sm:h-[theme(height.footer.sm)]">
`border` 換成 `border-t`

2024-05-05 17:11 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +        <nav className="fixed left-0 top-16 hidden h-[calc(100%-theme(height.header.sm))] w-[theme(width.nav.sm)] border bg-white sm:block md:w-[theme(width.nav.md)] xl:w-[calc((100vw-theme(width.max
`border` 換成 `border-r`
`h-[calc(100%-theme(height.header.sm))]` 換成 `bottom-0`

2024-05-05 17:11 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +          <div className="absolute top-0 right-0 h-full w-full xl:max-w-[theme(width.nav.xl)]">
上層用 `d-flex justify-end`，這層用 `grow` 的話，就可以省去 `absolute top-0 right-0 h-full w-full` 這一堆了

2024-05-05 17:11 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +        <nav className="fixed bottom-0 left-0 h-[theme(height.nav.default)] w-full border bg-white sm:hidden">
`border` 換成 `border-t`
`w-full` 換成 `right-0`

2024-05-06 03:53 UTC, caesarWHLee commented
https://github.com/readr-media/Sachiel/pull/759#discussion_r1590227493
https://github.com/readr-media/Sachiel/pull/759#discussion_r1590350836
https://github.com/readr-media/Sachiel/pull/759#discussion_r1590352718
https://github.com/readr-media/Sachiel/pull/759#discussion_r1590354239
https://github.com/readr-media/Sachiel/pull/759#discussion_r1590354788
https://github.com/readr-media/Sachiel/pull/759#discussion_r1590364218
https://github.com/readr-media/Sachiel/pull/759#discussion_r1590364346

以上 comments 已修正在 [36bec35](https://github.com/readr-media/Sachiel/pull/759/commits/36bec3580eb6d1cbff3b77352cf1bbbf788ba96d)

2024-05-06 03:54 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
> +          <div className="mr-auto min-h-[calc(100dvh-theme(height.header.default)-theme(height.footer.default)-theme(height.nav.default))] max-w-[theme(width.maxMain)] sm:min-h-[calc(100dvh-theme(hei
補充一下，parent 要多設定 `min-h-screen`，已設定

2024-05-06 06:47 UTC, erase2004 commented on packages/mesh/app/layout.tsx
[layout.tsx.patch](https://github.com/readr-media/Sachiel/files/15217584/layout.tsx.patch)
style 應該可以調整為這樣子
P.S. 有上背景色，記得再移除

2024-05-06 06:47 UTC, erase2004 commented on packages/mesh/tailwind.config.js
> +        maxMain: '1220px',
數值應該是 1120 而不是 1220?

2024-05-07 04:06 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
已修正在 [c8b1cf1](https://github.com/readr-media/Sachiel/pull/759/commits/c8b1cf19cbfed7c39e7281fd1be93f261ced990a)

2024-05-07 04:06 UTC, caesarWHLee commented on packages/mesh/tailwind.config.js
> +        maxMain: '1220px',
已修正在 [6b1bb47](https://github.com/readr-media/Sachiel/pull/759/commits/6b1bb47092cbdd2fd310f3f01bf687469c3287ee)

2024-05-07 07:14 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +            <div className="mr-auto h-full max-w-[theme(width.maxMain)]">
`mr-auto` 不用了

2024-05-07 07:14 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +          <div>置底 nav bar, 只在手機尺寸顯示</div>
這裡應該需要 `h-full`

2024-05-07 07:14 UTC, erase2004 commented on packages/mesh/app/layout.tsx
應該把 header, nav 和 footer 上的 border 設定下放到其 child element 上，這樣頁面的呈現才會與設計稿一致
例如：在大尺寸下， header 和 nav 的左邊界沒有對齊
![Snipaste_2024-05-07_15-12-32](https://github.com/readr-media/Sachiel/assets/1367757/44939d92-6fd2-4a83-9245-f3463dd46449)

2024-05-07 08:10 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +          <div className="mx-auto h-full max-w-[theme(width.maxContent)]">
`border-b` 搬到這裡

2024-05-07 08:10 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +          <div className="h-full">置底 nav bar, 只在手機尺寸顯示</div>
`border-t` 搬到這裡

2024-05-07 08:10 UTC, erase2004 commented on packages/mesh/app/layout.tsx
> +            <div className="h-full max-w-[theme(width.maxMain)]">
`border-t` 搬到這裡

2024-05-07 08:45 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
> +          <div className="mx-auto h-full max-w-[theme(width.maxContent)]">
搬進去 border 就不會長滿整個螢幕寬

2024-05-07 08:46 UTC, caesarWHLee commented on packages/mesh/app/layout.tsx
> +            <div className="h-full max-w-[theme(width.maxMain)]">
搬進去 border 就不會長滿整個 footer 區域了

2024-05-07 08:51 UTC, caesarWHLee commented
我覺得目前的 review 已經有點太執著在非常細微的調整，如果沒有 bug 之外的部分這個 PR 就準備要 merge 了，有任何建議還是可以提出來不過就之後可以另外開 PR 來調整，不然現在這樣有點花太多時間在 layout 上面了，感謝

2024-05-07 09:00 UTC, erase2004 approved these changes
LGTM 🎉

2024-05-07 09:16 UTC, merged