feat(mesh): add custom color and IconButton
readr-media/Sachiel pull request #760
Opened 2024-05-02 09:58 UTC by tyc67

- [Figma Guideline Color Palette](https://www.figma.com/file/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?type=design&node-id=3889-258018&mode=design&t=PaUEdsYGkVQteEVm-0) 設定TailwindCSS extend color
- [Figma Component](https://www.figma.com/file/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?type=design&node-id=3889-182910&mode=design&t=PaUEdsYGkVQteEVm-0) 製作共用Button Component

使用範例: 
```
        <IconButton
          size="sm"
          onClick={() => console.log('button-sponsor')}
          text="贊助"
          bgColor="blue"
        >
          <Dollar />
        </IconButton>
```
```
        <IconButton
          size="sm"
          onClick={() => setIsActive(!isActive)}
          text="精選"
          isActive={isActive}
          activeText="已精選"
          bgColor="white"
        >
          {isActive ? <StarSolid /> : <StarOutline />}
        </IconButton>
 ```
```
        <IconButton
          size="xs"
          onClick={() => console.log('button-publish')}
          text="發布"
          bgColor="primary"
          disable={true}
        />
```

2024-05-03 15:49 UTC, caesarWHLee commented on packages/mesh/components/icon-button.tsx
> +import React from 'react'
button 只能用在 client component，依照 convention 加上 'use client'

另外 `import React from 'react'` 不用特別寫了，見此[討論](https://stackoverflow.com/questions/63090037/importing-react-into-pages-in-next-js-and-also-react-and-cra-apps)

2024-05-03 15:49 UTC, caesarWHLee commented on packages/mesh/components/icons/dollar.tsx
如果沒有特別需要依照狀態來修改 svg 的內容的話比較建議使用 next/image 的方式來引入 svg，讓 next.js 來處理圖片載入的優化同時避免 code base 因為 svg 而變肥。

`<Image src="/icons/dollar.svg" width="16" height="16"/> `

2024-05-03 15:49 UTC, caesarWHLee commented on packages/mesh/components/icon-button.tsx
> +            {children}
目前的按鈕設計不需要在 hover 的時候改變 svg 的顏色，但如果像是設計稿中 "互動元件 icon" 會需要在 hover/active 的時候改變改變圖片，可以考慮改成透過 component 的方式來傳入 Icon component (如下面的 code)，並透過 tailwind group-{modifier} 的方式來修改 Icon component 中的 svg code，這樣會有比較高的彈性可以使用，可以參考這篇[文章](https://www.developerway.com/posts/react-component-as-prop-the-right-way)。

`<Button Icon={Icon} />`

2024-05-03 15:49 UTC, caesarWHLee commented on packages/mesh/components/icon-button.tsx
> +  const iconSize = size === 'lg' ? 'h-5 w-5 text-xl' : 'h-4 w-4 text-base'
目前 size 的分類方式跟設計稿的 button 名稱有點難對應，需要透過 sizeDefault 裡面的值來看是哪些 button，建議可以把 button 分類命名 (設計稿上的命名有點混亂可能需要跟設計討論一下命名)，目前看起來大致分成以下幾種：
1. 非固定寬度、高度38px、border-radius:4px 的 button 
2. 非固定寬度、高度32px、border-radius:4px 的 button
3. 固定寬度、高度46px、border-radius:6px 的 button
4. 非固定寬度、高度38px、border-radius:100px 的 button
5. 非固定寬度、高度30px、border-radius:100px 的 button
p.s. 顏色、背景色、有無 icon 就另外設定，非固定寬度的 button 就靠 padding 撐開，固定寬度的 button 就讓 icon + 文字整個是水平置中的方式擺放。

以上幾個類別對應的 padding, 寬度、高度、border-radius、font-size、icon-size 都可以 grouping 起來，使用上針對上面 p.s. 中的項目另外讓 button 使用者傳入控制，在使用和維護上應該會相對乾淨一點，之後設計新增的 button 也可以套進這幾種 button 之中。

看你覺得這樣的設計有沒有比較好，可以再討論看看。

2024-05-04 14:59 UTC, erase2004 requested changes

2024-05-04 14:59 UTC, erase2004 commented on packages/mesh/tailwind.config.js
> +      colors: {
在考慮有 dark theme 的情況下，我會把顏色切成下圖中的組合，除了 `readr` 之外的組的底下，會用
```
{
  DEFAULT: <color>,
  dark: <color in dark mode>
}
```
的結構來表示
![Color Palette](https://github.com/readr-media/Sachiel/assets/1367757/54133ee9-b85c-4b1e-a4c3-ffc9698a8dab)

2024-05-04 14:59 UTC, erase2004 commented on packages/mesh/components/icon-button.tsx
我覺得可以考慮用 cva 的方式來處理，讓這個乘載許多樣式差異的按鈕元件，在使用管理時可以更加明確
https://cva.style/docs/examples/react/tailwind-css

2024-05-04 14:59 UTC, erase2004 commented on packages/mesh/components/icon-button.tsx
Icon 可有可無的話，命名為 Button 或 BaseButton 之類？

2024-05-04 14:59 UTC, erase2004 commented on packages/mesh/components/icon-button.tsx
> +  onClick: () => void
這裡的 type 應該是 `MouseEventHandler<HTMLButtonElement>`，這樣上層呼叫的 function 才能夠正確解析 event

2024-05-04 14:59 UTC, erase2004 commented on packages/mesh/components/icon-button.tsx
> +  children?: React.ReactNode
Ln. 12 都用了 `React.PropsWithChildren`，Ln. 19 的 children 是多餘的

2024-05-06 02:05 UTC, tyc67 commented on packages/mesh/components/icons/dollar.tsx
使用Next.js  `<Image>`  API 的好處是不用自己製作 react component, 缺點是`<img>` 好像沒辦直接用[CSS fill properties](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes) 去控制`<svg>`, 取代方案 1. image src 指向不同顏色的 icon.svg 或 2. [CSS filter property](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)

2024-05-07 01:33 UTC, tyc67 commented
1. Component名稱修改為`Button` 
2. `Button` 型態變化改由高度和padding控制 30px, 32px, 38px, 46px
3. `Button` 的 icon 改由props傳入

```jsx
<Button
  size="sm"
  onClick={() => console.log('button-sponsor')}
  text="贊助"
  bgColor="blue"
  icon={{ iconName: 'icon-dollar-white', size: 's' }}
/>

<Button
  size="sm"
  onClick={() => setIsActive(!isActive)}
  text="精選"
  isActive={isActive}
  activeText="已精選"
  bgColor="white"
  icon={{ iconName: 'icon-star-primary', size: 's' }}
  activeIcon={{ iconName: 'icon-star-white', size: 's' }}
/>
```

3. 製作`Icon`Component , 採用 Next `<Image>` API 方式 import SVG, 可利用 size props 改變大小 
4. 色票設定和設計師討論後有更新 key name , 以 [Figma Guideline Color Palette](https://www.figma.com/file/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?type=design&node-id=3889-258018&mode=design&t=PaUEdsYGkVQteEVm-0) 為主

2024-05-07 01:42 UTC, tyc67 commented on packages/mesh/tailwind.config.js
> +      colors: {
色票設定和設計師討論後有更新 key name , 以 [Figma Guideline Color Palette](https://www.figma.com/file/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?type=design&node-id=3889-258018&mode=design&t=PaUEdsYGkVQteEVm-0) 為主, 修改於 [1ea4b49](https://github.com/readr-media/Sachiel/pull/760/commits/1ea4b4974e52f0de5ee10de2c97f2d466f81bf97)

2024-05-07 03:29 UTC, erase2004 reviewed
請問按鈕的顏色是否也會有 dark theme 切換的設定？這樣的話，button 的色彩設定需要加上 dark，並且 svg icon 應該要改回用 component，如此一來， svg icon 才能夠響應 theme 的變化

2024-05-07 03:29 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +        {isActive && activeIcon ? (
我會把 span 內的內容，用 props 傳入來控制，如同
https://github.com/mirror-media/Adam/blob/dev/packages/mirror-media-next/components/shared/buttons/primary-button.js

2024-05-07 03:29 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    disable: 'bg-disable text-primary-400',
disable 效果可以考慮放在 primary 底下，用 `disabled:` 的形式處理？

2024-05-07 03:29 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    disable: 'bg-disable text-primary-400',
disabled 應該有 `cursor-not-allowed` 的效果

2024-05-07 03:29 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +      onClick={onClick}
在 disable 狀態下，應該避免呼叫來自 props 的 onClick，避免按鈕在 disabled 狀態下，還能夠觸發功能

2024-05-07 06:37 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    disable: 'bg-disable text-primary-400',
請問一下是指 `<button disabled={true}` 狀態下, 應該是無法觸發 `onClick` ,還需再加上 `cursor: not-allowed` 的效果嗎？

2024-05-07 07:55 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    disable: 'bg-disable text-primary-400',
一般狀態下用 `cursor: pointer`，disabled 狀態下用 `cursor: not-allowed`，兩組一起做搭配

2024-05-07 08:01 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +        {isActive && activeIcon ? (
目前設計稿沒有 button dark mode的狀態設定, 未來如果有應該可以在 colorDefault 擴充 `dark:`

目前設計稿 button 沒有 isLoading 狀態設計, `button`內容狀態分為

- 純文字 → active文字
- Icon+文字 → activeIcon+active文字

👆因為設計才有 `<span>` 的判斷邏輯

不太確定將`<span>`內容 abstract 出去和目前用 props properties 控制的差異為何？



另外我可能會將 props data type 改為
```
  activeState?: {
    isActive: boolean
    activeText?: string
    activeIcon?: IconProps
  }
```

2024-05-07 08:22 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    disable: 'bg-disable text-primary-400',
disabled 狀態修正於 [1b083d7](https://github.com/readr-media/Sachiel/pull/760/commits/1b083d7602bb1783e6e3c609faafd563f7798eb0)

2024-05-07 09:14 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +        {isActive && activeIcon ? (
可以藉由傳比較少的參數，達成顯示效果，而且使用方的可調整性會比較大
```JSX
<Button>
  {isActive ? <ActiveDisplay> : <DefaultDisplay>}
</Button>
```
ActiveDisplay 可以是
```JSX
<ActiveIcon>
<ActiveText>
```
```JSX
<ActiveIcon />
```
```JSX
<ActiveText />
```
等等內容

2024-05-07 09:49 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +        {isActive && activeIcon ? (
dark theme 的問題，應該需要釐清的是，
在 color palette 已經有對應顏色的情況下，是直接在實作時套用就好，
還是需要等對應 dark theme 的設計出來，才要實作

2024-05-07 10:13 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +        {isActive && activeIcon ? (
[9996f94](https://github.com/readr-media/Sachiel/pull/760/commits/9996f941f6ad7c95c080a37a7b1376ff3f09a571)
點擊只換button顏色

```jsx
          <Button
            size="md-100"
            text="政治"
            activeState={{ isActive: isActive }}
            onClick={() => setIsActive(!isActive)}
            bgColor="white"
          />
```
點擊只換顏色+文字
```jsx
          <Button
            size="md"
            text="追蹤"
            activeState={{
              isActive: isActive,
              activeText: '追蹤中',
            }}
            onClick={() => setIsActive(!isActive)}
            bgColor="white"
          />
```
點擊換顏色＋Icon+文字
```jsx
          <Button
            size="sm"
            onClick={() => setIsActive(!isActive)}
            text="精選"
            bgColor="white"
            icon={{ iconName: 'icon-star-primary', size: 's' }}
            activeState={{
              isActive: isActive,
              activeText: '已精選',
              activeIcon: { iconName: 'icon-star-white', size: 's' },
            }}
          />
```

- 這個的好處是直接用 props properties 決定button要的形式, 不需要再多寫`<ActiveDisplay>`和 `<DefaultDisplay>`

- button dark theme 的部分我的理解是, 等設計出來在實作.

2024-05-07 10:32 UTC, caesarWHLee commented on packages/mesh/components/button.tsx
> +        <div className={`${fontSize} font-normal`}>
建議不要把 div 放到 span 之中，如果都會設定外層為 `display: flex;` 可以考慮把 span 改成 div 就好

2024-05-07 10:32 UTC, caesarWHLee commented on packages/mesh/components/button.tsx
> +          <Icon {...icon} />
目前有 icon 的狀況下沒設定到 icon 和 text 之間的間距，要再補上。

另外目前的 size 其實就是 button 的類型，size, fontSize 和這個 comment 要補上的間距設定，其實都是依照 size 來決定，目前的寫法雖然有隱含了這個邏輯，但在閱讀上需要把 `sizeDefault`, `fontSize` 的邏輯都理解完才能形成一個完整的各個類型對應到的設定，可以考慮改成以下方式，依照 size 把各字需要個別設定的部分放在一起，閱讀上比較好理解一點 (不過就是比較冗長)，看你覺得如何。

```
  const buttonStyles = {
    xs: {
      buttonSize: 'h-[30px] px-4 py-2 rounded-[100px]',
      fontSize: 'text-sm',
      contentGap: '', // no icon for now
    },
    sm: {
      buttonSize: 'h-8 px-3 py-1 rounded',
      fontSize: 'text-sm',
      contentGap: '2px',
    },
    md: {
      buttonSize: 'h-[38px] px-5 py-2 rounded',
      fontSize: 'text-base',
      contentGap: '2px',
    },
    'md-100': {
      buttonSize: 'h-[38px] px-4 py-2 rounded-[100px]',
      fontSize: 'text-base',
      contentGap: '', // no icon for now
    },
    lg: {
      buttonSize: 'w-full h-[46px] rounded',
      fontSize: 'text-base',
      contentGap: '4px',
    },
  }

  const buttonStyle = buttonStyles[size]
```

2024-05-07 11:15 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +          <Icon {...icon} />
修正於 [8a82c1c](https://github.com/readr-media/Sachiel/pull/760/commits/8a82c1c046725e18047d4af37d0b3923fb5c9039)

2024-05-07 11:15 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +        <div className={`${fontSize} font-normal`}>
修正於 [8a82c1c](https://github.com/readr-media/Sachiel/pull/760/commits/8a82c1c046725e18047d4af37d0b3923fb5c9039)

2024-05-08 03:41 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +          <Icon {...icon} />
補充說明: 增加透明色 button style [3ca7215](https://github.com/readr-media/Sachiel/pull/760/commits/3ca72157cba4da73c1760aa631e0fcd0309dbbe7)

<img width="342" alt="Screenshot 2024-05-08 at 11 03 05 AM" src="https://github.com/readr-media/Sachiel/assets/114332515/5645f291-4d10-4beb-9c9c-a3f448ad3756">

2024-05-08 03:43 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +          <Icon {...icon} />
這組顏色行為不是 white?

2024-05-08 03:46 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +          <Icon {...icon} />
Figma 看是沒有給色, 剛有問manzoo, 他說要加一個無底色的

2024-05-08 04:01 UTC, caesarWHLee reviewed
https://github.com/readr-media/Sachiel/pull/760#discussion_r1588942370

目前我這邊看起來就差 button.tsx 和 icon.tsx 加一下 'use client'，或是覺得不用特別加的話可以討論 convention 要不要修改

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +      'bg-transparent text-primary-700 border border-primary-700 disabled:bg-disable disabled:text-primary-400 disabled:border-none disabled:cursor-not-allowed',
沒有 hover 效果？

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    blue: 'bg-custom-blue text-white disabled:bg-disable disabled:text-primary-400 disabled:cursor-not-allowed',
key name 用 `custom-blue` 與 bg-xxx 對齊

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    xs: 'h-[30px] px-4 py-2 rounded-[100px] text-sm',
應該有 `leading-1` 的 style，來消除 `text-sm` 自帶的 `line-height`

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    md: 'h-[38px] px-5 py-2 rounded text-base',
應該有 `leading-[1.4]` 的 style，來消除 `text-base` 自帶的 `line-height`

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    sm: 'h-8 px-3 py-1 rounded text-sm gap-0.5',
`px-3` 應該修正為 `pl-2.5 pr-3`？

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    sm: 'h-8 px-3 py-1 rounded text-sm gap-0.5',
應該有 `leading-[24px]` 的 style，來消除 `text-sm` 自帶的 `line-height`

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    sm: 'h-8 px-3 py-1 rounded text-sm gap-0.5',
這兩個應該都用 sm 這組，但是 `padding-left` 數值上不一樣

![Snipaste_2024-05-08_12-08-27](https://github.com/readr-media/Sachiel/assets/1367757/e65c3920-224e-47cf-9967-94230fe10a6c)
![Snipaste_2024-05-08_12-08-49](https://github.com/readr-media/Sachiel/assets/1367757/8ee4450f-0dc5-443f-bf95-6d77be3a3b14)

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    sm: 'h-8 px-3 py-1 rounded text-sm gap-0.5',
另一組參考
![Snipaste_2024-05-08_12-10-09](https://github.com/readr-media/Sachiel/assets/1367757/24c433ea-f6a9-4339-9895-57d9f8936e5d)
![Snipaste_2024-05-08_12-10-13](https://github.com/readr-media/Sachiel/assets/1367757/cd31c1c5-90c9-4c38-8fa4-1bb546f4ef52)

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    lg: 'w-full h-[46px] rounded text-base gap-1',
lg 應該也有 padding
![Snipaste_2024-05-08_12-11-54](https://github.com/readr-media/Sachiel/assets/1367757/f5e1b79c-1e4e-4442-92a0-06255f082dea)

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    lg: 'w-full h-[46px] rounded text-base gap-1',
應該有 `leading-[1.4]` 的 style，來消除 `text-base` 自帶的 `line-height`

2024-05-08 04:17 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    'md-100': 'h-[38px] px-4 py-2 rounded-[100px] text-base',
應該有 `leading-[1.4]` 的 style，來消除 `text-base` 自帶的 `line-height`

2024-05-08 07:14 UTC, tyc67 commented on packages/mesh/components/icon-button.tsx
> +import React from 'react'
我個人覺得可以在上層 Server Component 和 Client Component 中間加 (參考 [ref](https://nextjs.org/docs/app/building-your-application/rendering/client-components#using-client-components-in-nextjs) ), 不需要另外加在共用的 UI Component.

2024-05-08 07:15 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    xs: 'h-[30px] px-4 py-2 rounded-[100px] text-sm',
請問一下, `Button` 理論上不會有多行文字的情況, 還需要另外給給定 `line-height` 值嗎

2024-05-08 08:26 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +      'bg-transparent text-primary-700 border border-primary-700 disabled:bg-disable disabled:text-primary-400 disabled:border-none disabled:cursor-not-allowed',
Figma有更新, 加 hover 效果於 [20791e6](https://github.com/readr-media/Sachiel/pull/760/commits/20791e6cf360c1f979de45cefa57c7d2df600bdc)

2024-05-08 08:26 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    blue: 'bg-custom-blue text-white disabled:bg-disable disabled:text-primary-400 disabled:cursor-not-allowed',
修改於 [20791e6](https://github.com/readr-media/Sachiel/pull/760/commits/20791e6cf360c1f979de45cefa57c7d2df600bdc)

2024-05-08 08:32 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    sm: 'h-8 px-3 py-1 rounded text-sm gap-0.5',
為維持共用 buttonStyle[sm] 的Style , Button內容位置變化改由`translate-x-0` 和 `translate-x-[-2px]` , 此修正於 [20791e6](https://github.com/readr-media/Sachiel/pull/760/commits/20791e6cf360c1f979de45cefa57c7d2df600bdc)

2024-05-08 14:28 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    xs: 'h-[30px] px-4 py-2 rounded-[100px] text-sm',
`line-height` 會影響文字自身顯示的高度

2024-05-08 23:37 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    xs: 'h-[30px] px-4 py-2 rounded-[100px] text-sm',
|  | Figma | Tailwind Default |
| --- | --- | --- |
| xs | font-size: 14px<br>line-height: 14px | text-sm<br>font-size: 14px<br>line-height: 20px |
| sm | font-size: 14px<br>line-height: 24px | text-sm<br>font-size: 14px<br>line-height: 20px |
| md | font-size: 16px<br>line-height: 22.4px | text-base<br>font-size: 16px<br>line-height: 24px |
| md-100 | font-size: 16px<br>line-height: 22.4px | text-base<br>font-size: 16px<br>line-height: 24px |
| lg | font-size: 16px<br>line-height: 22.4px | text-base<br>font-size: 16px<br>line-height: 24px |

![image](https://github.com/readr-media/Sachiel/assets/114332515/81d1f580-ee41-46af-9295-03b14431be0e)


我的理解是 [line-height](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) 改變 `line-box` 的高度, 多行文字下產生行與行的間距效果
單行文字狀態下, `font-size` > `line-height` 或者 `font-size` < `line-height` 都不會影響文字本身顯示狀態, 因此這邊比較傾向不給特定的 `leading` 值

2024-05-09 08:25 UTC, caesarWHLee commented on packages/mesh/components/icon-button.tsx
> +import React from 'react'
根據討論修改 convention 為
- put ‘use client’ on the top most client component

此 comment 可忽略

2024-05-09 10:02 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +    xs: 'h-[30px] px-4 py-2 rounded-[100px] text-sm',
![Snipaste_2024-05-09_17-59-21](https://github.com/readr-media/Sachiel/assets/1367757/75686fc5-e355-40bf-a283-72092806be74)

其實單行就會產生效果了，另外，有注意到文字有統一的 style guide，應該會有對應的 class，此 PR 有關 leading 的問題先擱置
```HTML
<div class="container">
  <div class="text case1">This is text</div>
  <div class="text case2">This is text</div>
</div>
```

```CSS
* {
  box-sizing: border-box;
}

.container {
  display: flex;
  column-gap: 10px;
}

.text {
  display: inline-block;
  color: white;
  background-color: blue;
  padding: 10px;
  width: 100px;
  height: 36px;
  font-size: 16px;
}

.case1 {
  line-height: 1;
}

.case2 {
  line-height: 1.5;
}
```

2024-05-09 10:18 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    xs: 'h-[30px] px-4 py-2 rounded-[100px] text-sm',
好像 `display: inline-block` 有效果, 但如果用 `display: flex` 我試著改變 `line-height: 1.5` 沒有產生反應

2024-05-10 00:58 UTC, erase2004 commented on packages/mesh/components/button.tsx
> +          icon ? 'flex translate-x-[-2px] items-center' : 'translate-x-0'
這個設定沒辦法套用在比較大的 button 上，大的 button 是沒有 left shift，另外，後面的 `translate-x-0` 是多餘的
![Snipaste_2024-05-09_19-07-43](https://github.com/readr-media/Sachiel/assets/1367757/594f4c40-83c7-40d3-8c8c-5ab86d0c3a89)

2024-05-10 02:31 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +          icon ? 'flex translate-x-[-2px] items-center' : 'translate-x-0'
修正於 [4937de6](https://github.com/readr-media/Sachiel/pull/760/commits/4937de6506973b70845858d07e20da6da4caaff9)

2024-05-10 03:52 UTC, erase2004 approved these changes
👏

2024-05-10 04:52 UTC, merged