feat(mesh/social): add social page
readr-media/Sachiel pull request #764
Opened 2024-05-21 09:13 UTC by tyc67

## [ Mesh Readr Web 社群頁面 ]
- 刻社群頁卡片 UI
- 精選/留言顯示邏輯以時間最新為主
- 新增 `Icon` extra classname props, 以利減少CLS問題
- mock data 先用 apollo client 打原來的 gql server，proxy server 的部分尚在研究中

2024-05-22 05:58 UTC, erase2004 requested changes

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/_components/header.tsx
> +    <header className="fixed top-0 left-0 right-0 z-10 h-[theme(height.header.default)] border-b bg-white sm:h-[theme(height.header.sm)]">
z-index 應該參考 https://github.com/readr-media/Sachiel/blob/2745acb067a5cd8036921e7a88d863cfff8b599a/packages/politics-tracker/constants/index.ts#L1 這樣的模式，在 tailwind config 下妥善管理 cc @caesarWHLee

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/constants/config.ts
> +    API_ENDPOINT = 'https://mesh-gql-dev-4g6paft7cq-de.a.run.app/api/graphql'
dev 環境的 `API_ENDPOINT` 數值應該也是相同的？

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/components/icon.tsx
> +  const classProps = className ? ` ${className}` : ''
` ${className}` 這裡前面多一個空白的原因？

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/types/graphql.ts
`__typename` 我們通常不會標註它，他的使用只有在資料是 union type 的情況下，才會被使用
ref: `https://graphql.org/learn/schema/#union-types`

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/types/graphql.ts
一個建議，如果 type 是代表 graphql query 或 fetch 的結果，是否 graphql schema 或 fetch util 放在一起管理會比較好？
cc @caesarWHLee

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/types/graphql.ts
再來，針對 graphql schema，如果欄位的 type 標示沒有 `!` 的話，那個欄位回傳的數值可能是空值
ref: https://graphql.org/learn/schema/#object-types-and-fields

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/graphql/query/get-user-following.ts
graphql query/mutation 底下的每個檔案，應該代表針對特定 list 的相關的操作，像這個檔案的命名應該調整為 `member.ts`，因為其資料操作對象是 `member` list，我的理解是這樣子，需要 @caesarWHLee 那邊確定

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/page.tsx
提問：目前還沒實作頁面滾動往上滑，載入更多 picks 的功能？
還是其實沒這個需求？

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/page.tsx
> +  const feedsNumber = 20
要顯示的數量是 20 則，但針對每個 following 只抓到 10 則，
假設使用者跟隨 [A, B, C]，而 A, B, C 各有 21, 0, 0 則，這樣組出來的顯示結果，最多只會有 10 則，
這是 ok 的？

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/page.tsx
> +
關於 Ln. 30 和 Ln. 42，我在 JSX 內容之外用個別變數來儲存
```JavaScript
const firstSectionAmount = 2
firstSectionPicks = sortedPicksByPickTime.slice(0, firstSectionAmount)
secondSectionPicks = sortedPicksByPickTime.slice(firstSectionAmount)
```
這樣未來在調整顯示數量，不會發生只調整一邊的情況

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +function getLatestActionData(picks: Pick[], comments: Comment[]) {
我看這裡的處理，是從 Pick 和 Comment 當中，抓最新一筆，來判斷是要回傳 `Pick[]` 還是 `Comment[]`，
從速度來考量的話，抓最新一筆其實不用用到 sort，用 array.reduce 就可以了，
這樣一來，時間複雜度便可從 `O(n logn)` 降到 `O(n)`

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +  const differenceInHour = (Date.now() - timestamp) / (1000 * 60 * 60)
時間單位的東西我會弄出一個 enum object 來做管理使用
ref: https://github.com/mirror-media/Adam/blob/dev/packages/mirror-media-next/constants/time-unit.js

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +          <Icon iconName="icon-dot" size="s" />
付費文章和蓋板廣告應該只是特定條件下才要顯示的資訊？

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +                  <Image
應該會需要 avatar 圖載入失敗，改顯示預設 icon 的處理

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +              {latestActionData[0].__typename === 'Pick' ? (
`latestActionData[0]` 可能是 `undefined`

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +            <div className="body-3 ml-2 text-primary-500">
文字區塊，我對規則的理解是：
1. 藉由最新動作的第一筆 (Pick or Comment)，來決定要顯示的動作文字是 `OOO精選了這篇文章` 還是 `OOO在這篇文章留言`
2. 如果最新動作人數是 2 人的話，依照第一筆的動作內容，動作文字調整為 `OOO及XXX都精選了這篇文章` 或 `OOO 及XXX都在這篇文章留言`
3. 如果最新動作人數是 3 人以上（含），依照第一筆的動作內容，動作文字調整為 `OOO及其他N人都精選了這篇文章` 或 `OOO及其他N人都在這篇文章留言

目前看起來不是依照這個規則實作

https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN?node-id=5372-68793&m=dev#811952211

另外， 設計上面還有卡片樣式，針對兩個人情況下，人名的顯示規則，目前看起來也沒被實作
註：這規則應該適用於單人的情況，目的應該是讓整行只用ㄧ行來呈現

https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN?node-id=6138-176069&m=dev#811959815

2024-05-22 05:58 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-comment.tsx
> +  const maxTextLength = 60
這裡看起來是用字數來做截斷，不過設計上是用行數 + 填滿到最後ㄧ行的結尾 🤔

2024-05-22 06:15 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-comment.tsx
> +  const maxTextLength = 60
這個效果目前沒辦法純 CSS 解，我是覺得看能不能跟設計討論，改用漸層的形式
ref: https://css-tricks.com/recreating-mdns-truncated-text-effect/

2024-05-22 08:03 UTC, caesarWHLee reviewed
先就目前快速看到的部分提供 comment，後續會再針對 UI 部分 review

2024-05-22 08:03 UTC, caesarWHLee commented on packages/mesh/app/_components/header.tsx
> +    <header className="fixed top-0 left-0 right-0 z-10 h-[theme(height.header.default)] border-b bg-white sm:h-[theme(height.header.sm)]">
關於 z-index 要定多少，有兩種做法可以討論一下：
1. 可以比照週刊 3.0 定的[方式](https://github.com/mirror-media/Adam/blob/dev/packages/mirror-media-next/constants/index.js#L204-L209)，先在 tailwind.config 上面設定幾個定值，以 10 的倍數為區間，先定義幾個層級，後續開發再依照層級來細寫不同的 z-index 值。
2. 先不設定層級，不過把所有用到 z-index 的地方都先記錄起來，頁面開發到一定程度或是 z-index 複雜度升高之後再來統整所有的 z-index 值，規劃整體用法。

不管是哪個做法，最好都有個文件紀錄所以的 z-index 使用狀況，這邊先快速開了[文件](https://paper.dropbox.com/doc/Development--CPmyLl5XkHRjqV0YkVJlONspAg-I6nQAojaCWIC8sW3fS8DF) 可以先記錄使用狀況。

關於 z-index 的使用可以另外開個 PR 討論，這邊先趁第一次使用到起個頭。

2024-05-22 08:03 UTC, caesarWHLee commented on packages/mesh/components/icon.tsx
> +export default function Icon({ iconName, size, className }: IconProps) {
可以把 `props.className` 預設值設為空字串，這樣就可以直接塞進 `Image` 中了 `<Image className={className}/>`

2024-05-22 08:03 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +        <h1 className="title-1 mb-2 break-words">{story?.og_title}</h1>
這邊應該是要拿 `story.title`，以[這邊](https://mesh-cms-dev-4g6paft7cq-de.a.run.app/stories/1)來說，`og_title` 會含有 `source` 資訊，但 `source` 資訊應該是上面的 h4 在顯示

2024-05-22 08:03 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +          {story?.source?.customId}
這邊應該是拿 `story.source.title`，差異如下圖
![image](https://github.com/readr-media/Sachiel/assets/104348940/180b7918-2ee4-4b9f-aff7-d55578331bb4)

2024-05-22 08:03 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +    if (!foundNewPick) {
應該可以直接用 `seenPickIds.size` 來替代就好

2024-05-22 08:03 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +  )
目前觀察到的社群頁面資料邏輯：
在 gql request 時，會針對 user following 的 member 各拿最新的十個 pick，然後進行好幾輪的取值，第 n 輪拿出每個 member 第 n 個 pick，最多拿到設定數量 (目前是 20) 後停止拿取，再依照各個 pick 的 `createdAt` 的值來排序 (新到舊)。

這個好像沒有寫在 PM 目前捕的文件中，如果確定是這個邏輯的話再請 PM 補一下，另外，因為後續會接著開發 infinite scroll 的功能，可能要連下一頁的資料抓取一併考慮進去，目前的拿法可能就會不知道下一頁的資料要如何接著拿。

2024-05-22 08:05 UTC, caesarWHLee commented on packages/mesh/constants/config.ts
> +    API_ENDPOINT = 'https://mesh-gql-dev-4g6paft7cq-de.a.run.app/api/graphql'
dev 用的 API_ENDPOINT 為之前留下的測試用 endpoint，我再另外開 PR 連同首頁寫的範例 gql request 一起拿掉好了，會一起把 dev 調整成新的。

2024-05-22 08:06 UTC, caesarWHLee commented on packages/mesh/types/graphql.ts
可以討論一下，另外 gql query 中要不要用 fragment 的方式也可以一併討論 convention。

2024-05-22 08:34 UTC, erase2004 commented on packages/mesh/app/_components/header.tsx
> +    <header className="fixed top-0 left-0 right-0 z-10 h-[theme(height.header.default)] border-b bg-white sm:h-[theme(height.header.sm)]">
z-index 的部份應該不用再開文件了，頂多在 convention 中，告知使用 z-index 的情況下，請在 tailwind config 中做設定，並且使用 config 中有的數值

2024-05-22 09:43 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +    (item) => item.story.id === story.id
userId 改成 "17" 的狀況下頁面會報錯，原因是 Pick 有可能是 pick story 或 collection，所以 story 值可能是空的，這個可能需要在 process 的時候就避免掉。

另外需求方面也要確認一下集錦是否只會在個人頁面才會看到 (是的話集錦感覺使用度會很低)

2024-05-22 11:56 UTC, caesarWHLee reviewed
目前看來這個 PR 只包含了基本的初次載入的 data fetch 和靜態的資料呈現，還有蠻多 feature 待補的，建議可以把整個頁面有的 feature 都列出成一份 todo list 然後把這次有實作的打勾，剩下的放到 follow-up 之中比較容易看出還剩下哪些功能待實作。

2024-05-22 11:56 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +    (item) => item.story.id === story.id
目前測試 userId 改成 "17" 的狀況下會遇到頁面報錯，原因是有 pick 的 story 是空的 (null)。

2024-05-22 11:56 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +                  />
兩張 avatar 以上重疊的順序相反了，另外目前有看到 avatar 背景色是透明的導致即便有設置 z-index 也會露出下方的 avatar，需要補上 default 背景色。

2024-05-23 13:14 UTC, tyc67 commented on packages/mesh/app/_components/header.tsx
> +    <header className="fixed top-0 left-0 right-0 z-10 h-[theme(height.header.default)] border-b bg-white sm:h-[theme(height.header.sm)]">
修改於 [4ddc102](https://github.com/readr-media/Sachiel/pull/764/commits/4ddc102f9669a9e38dc10e9df6b678a41a7d4d6b)

2024-05-23 13:15 UTC, tyc67 commented on packages/mesh/components/icon.tsx
> +  const classProps = className ? ` ${className}` : ''
修改於 [194d144](https://github.com/readr-media/Sachiel/pull/764/commits/194d144e8974a84728ab2a22daf623f6b5769441)

2024-05-23 13:15 UTC, tyc67 commented on packages/mesh/components/icon.tsx
> +export default function Icon({ iconName, size, className }: IconProps) {
修改於 [194d144](https://github.com/readr-media/Sachiel/pull/764/commits/194d144e8974a84728ab2a22daf623f6b5769441)

2024-05-23 13:16 UTC, tyc67 commented on packages/mesh/app/_components/header.tsx
> +    <header className="fixed top-0 left-0 right-0 z-10 h-[theme(height.header.default)] border-b bg-white sm:h-[theme(height.header.sm)]">
修改於 [4ddc102](https://github.com/readr-media/Sachiel/pull/764/commits/4ddc102f9669a9e38dc10e9df6b678a41a7d4d6b)

2024-05-23 13:21 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +          <Icon iconName="icon-dot" size="s" />
修改於 [516082b](https://github.com/readr-media/Sachiel/pull/764/commits/516082b332f05afa9fcc36aa11826ecd8c7b2c06)

2024-05-23 13:21 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +  const differenceInHour = (Date.now() - timestamp) / (1000 * 60 * 60)
修改於 [516082b](https://github.com/readr-media/Sachiel/pull/764/commits/516082b332f05afa9fcc36aa11826ecd8c7b2c06) 和 [b16422e](https://github.com/readr-media/Sachiel/pull/764/commits/b16422ea48e66d35d93bd954f6f8f043a5e932d8)

2024-05-23 13:22 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +                  />
修改於 [516082b](https://github.com/readr-media/Sachiel/pull/764/commits/516082b332f05afa9fcc36aa11826ecd8c7b2c06)

2024-05-23 13:22 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +    (item) => item.story.id === story.id
修改於 [516082b](https://github.com/readr-media/Sachiel/pull/764/commits/516082b332f05afa9fcc36aa11826ecd8c7b2c06)

2024-05-23 13:23 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +          {story?.source?.customId}
修改於 [516082b](https://github.com/readr-media/Sachiel/pull/764/commits/516082b332f05afa9fcc36aa11826ecd8c7b2c06)

2024-05-23 13:23 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +        <h1 className="title-1 mb-2 break-words">{story?.og_title}</h1>
修改於 [516082b](https://github.com/readr-media/Sachiel/pull/764/commits/516082b332f05afa9fcc36aa11826ecd8c7b2c06)

2024-05-23 13:26 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +              {latestActionData[0].__typename === 'Pick' ? (
修改於 [516082b](https://github.com/readr-media/Sachiel/pull/764/commits/516082b332f05afa9fcc36aa11826ecd8c7b2c06)

2024-05-23 13:30 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +                  <Image
目前這邊是 Server Component 應該是NextJS `<Image >`API 的預設 Error log, 若要處理 Client Side loading Error 的部分是不是變成這邊要改用 Client Component 呢?

2024-05-23 13:39 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +function getLatestActionData(picks: Pick[], comments: Comment[]) {
這裡的規則為：

- 如果是最新一筆是 Pick -> Return 最新2筆 Pick
- 如果是最新一筆是 Comment -> Return 最新1筆 Comment

如果用 reduce 來確定最新一筆後, 應該還是需要 sort 一次Array 來找最新第2筆Pick 資料
另外, 在 array data <10^5, sort 和 reduce 在速度上會有顯著的差異嗎? 


```javascript
function getLatestActionDataReduce(picks: Pick[], comments: Comment[]) {
  const combinedData = [...picks, ...comments]
  const latestAction = combinedData.reduce(
    (latest: Pick | Comment | null, current: Pick | Comment) => {
      const latestTime = latest ? new Date(latest.createdAt).getTime() : 0
      const currentTime = new Date(current.createdAt).getTime()
      return currentTime > latestTime ? current : latest
    },
    null
  )

  if (!latestAction) return []

  switch (latestAction.__typename) {
    case 'Pick': {
      const pickElements = combinedData
        .filter((item) => item.__typename === 'Pick')
        .sort(
          (a, b) =>
            new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        )
        .slice(0, 2)
      return pickElements
    }

    case 'Comment': {
      return [latestAction]
    }

    default:
      return []
  }
}
```

2024-05-23 13:41 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
Load More Feature 會另外PR處理

2024-05-28 08:07 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  )
修改於 [115db7b](https://github.com/readr-media/Sachiel/pull/764/commits/115db7b1d224883da5f6aa1ca58e368e25be6c44)
說明https://github.com/readr-media/Sachiel/pull/764#issue-2307790186
Pagination 的部分後續再和 Dylan 討論如何串接

2024-05-28 08:07 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +    if (!foundNewPick) {
修改於 [115db7b](https://github.com/readr-media/Sachiel/pull/764/commits/115db7b1d224883da5f6aa1ca58e368e25be6c44)
說明https://github.com/readr-media/Sachiel/pull/764#issue-2307790186

2024-05-28 08:09 UTC, tyc67 commented on packages/mesh/app/social/_components/feed-comment.tsx
> +  const maxTextLength = 60
目前效果有和 @manzoo 討論, 他說ok

2024-05-28 08:09 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +            <div className="body-3 ml-2 text-primary-500">
修改於 [115db7b](https://github.com/readr-media/Sachiel/pull/764/commits/115db7b1d224883da5f6aa1ca58e368e25be6c44)
說明https://github.com/readr-media/Sachiel/pull/764#issue-2307790186

2024-05-28 08:09 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +function getLatestActionData(picks: Pick[], comments: Comment[]) {
修改於 [115db7b](https://github.com/readr-media/Sachiel/pull/764/commits/115db7b1d224883da5f6aa1ca58e368e25be6c44)
說明https://github.com/readr-media/Sachiel/pull/764#issue-2307790186

2024-05-28 08:11 UTC, tyc67 commented on packages/mesh/types/graphql.ts
我先做一個版本
修改於 [115db7b](https://github.com/readr-media/Sachiel/pull/764/commits/115db7b1d224883da5f6aa1ca58e368e25be6c44)
說明https://github.com/readr-media/Sachiel/pull/764#issue-2307790186

2024-05-28 08:24 UTC, tyc67 commented on packages/mesh/types/graphql.ts
我這邊是拿 gql response data 自帶的 `__typename` 來辨別是來自於哪一個 field (pick or comment), 並用於後續 render logic condition 上

2024-05-28 08:46 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  const feedsNumber = 20
修改於 [115db7b](https://github.com/readr-media/Sachiel/pull/764/commits/115db7b1d224883da5f6aa1ca58e368e25be6c44)
說明https://github.com/readr-media/Sachiel/pull/764#issue-2307790186

2024-05-28 08:48 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +
修改於 [115db7b](https://github.com/readr-media/Sachiel/pull/764/commits/115db7b1d224883da5f6aa1ca58e368e25be6c44)
說明https://github.com/readr-media/Sachiel/pull/764#issue-2307790186

2024-05-29 09:02 UTC, erase2004 reviewed
目前的 `processStoryPicksAndComments` 和 `checkLatestAction` 在設計上似乎過於複雜，導致後端 (`FeedLatestAction` 和 `FeedComment`) 上，增加了不少複雜性。

* 針對 `FeedLatestAction`，它應該先用 actions 來辨別是 pick 還是 comment，然後在個別依照數量 1, 2 或 >= 3 的顯示邏輯去處理。

* 針對 `FeedComment`，它其實只需要知道 comment 中是否存在 member.id 與 latestAction 相同的即可

上述這兩個整理，便可以把這四者的處理邏輯給簡化，並且弄得更加清楚

![Snipaste_2024-05-29_16-29-57](https://github.com/readr-media/Sachiel/assets/1367757/74f5e27c-287f-4a5f-8cd6-20edfa006373)

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/graphql/query/get-user-following.ts
graphql 的管理，是以操作名稱作為檔名，內容為該操作和其 type? 還是以 CMS list 為檔名，內容是與 list 相關的操作及 type cc @caesarWHLee ?

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/graphql/query/get-user-following.ts
需要再標註一次
https://github.com/readr-media/Sachiel/pull/764#discussion_r1609234492

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/app/social/page.tsx
> +  Following,
import 是 type 的情況下，請標註

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/app/social/page.tsx
> +  const { data } = await getClient().query<
應該會需要 try-catch 和 errors 資訊的處理
ref: https://github.com/readr-media/Sachiel/blob/361118669cb39eba6a0688377e532ee82db7ef77/packages/readr/pages/index.tsx#L170

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/app/social/page.tsx
> +    (a: any, b: any) =>
這裡不用 `any` 標示，讓 TS 自動 infer 出 type 比較好

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +      const PickAndComment = comments?.find(
一般變數第一個應為小寫

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/graphql/query/get-user-following.ts
>            story {
可以用 fragment 的方式去管理 pick.story 和 comment.story 的結構
ref: https://graphql.org/learn/queries/#fragments

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-comment.tsx
> +  comment: Story['comment'][number]
建議可以用 `Pick`，來讓 comment 的 type 更符合該元件中，所使用到的屬性
ref: https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +    <Image
https://nextjs.org/docs/pages/api-reference/components/image#onerror
可以用 onError 去做 fallback 處理

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +export const renderAvatar = (member: Member, px: number) => {
可以考慮傳入的是 member.avatar，而不是傳入整個 member

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/graphql/query/get-user-following.ts
> +                customId
有些欄位未被使用的情況下，應該要刪除，例如 `member.customId` 之類

2024-05-29 09:02 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN?node-id=6138-176069#811959815
設計稿上有關於使用者名稱過長的顯示處理，目前看起來是沒有實作的

![Snipaste_2024-05-29_16-25-42](https://github.com/readr-media/Sachiel/assets/1367757/1a3e3b29-73cc-4993-a610-918b3764351f)

2024-05-29 09:24 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +function processedPicksAndCommentsData(
`processedPicksAndCommentsData` PR 上的解釋可以加到註解上，加速後續維護/Debug上的理解。

2024-05-29 09:24 UTC, caesarWHLee commented on packages/mesh/graphql/query/get-user-following.ts
相同的 list 可能會有多個 gql query，建議以 cms list 為檔名方式來放改名成 member.tsx，follow [週刊 3.0](https://github.com/mirror-media/Adam/tree/dev/packages/mirror-media-next/apollo/query)、[電視 2.0](https://github.com/mirror-tv/Tabris/tree/dev/packages/mirror-tv-next/graphql/query) 的做法。

2024-05-29 09:40 UTC, caesarWHLee commented on packages/mesh/graphql/query/get-user-following.ts
另外這邊應該只針對 gql query 定義該 query 回傳的 Type，`GetUserFollowingResponse`  可以叫做 `UserFollowing` 就好，`GetUserFollowingRequest` 應該是放在 `fetchUserFollowing` function 旁宣告該 Type 就好 (或是其實沒有需要特別帶這個 request 的 type？)。

2024-05-29 10:12 UTC, caesarWHLee commented
> 目前的 `processStoryPicksAndComments` 和 `checkLatestAction` 在設計上似乎過於複雜，導致後端 (`FeedLatestAction` 和 `FeedComment`) 上，增加了不少複雜性。
> 
> * 針對 `FeedLatestAction`，它應該先用 actions 來辨別是 pick 還是 comment，然後在個別依照數量 1, 2 或 >= 3 的顯示邏輯去處理。
> * 針對 `FeedComment`，它其實只需要知道 comment 中是否存在 member.id 與 latestAction 相同的即可
> 
> 上述這兩個整理，便可以把這四者的處理邏輯給簡化，並且弄得更加清楚
> 
> ![Snipaste_2024-05-29_16-29-57](https://private-user-images.githubusercontent.com/1367757/334723316-74f5e27c-287f-4a5f-8cd6-20edfa006373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzM2MjcsIm5iZiI6MTcxNjk3MzMyNywicGF0aCI6Ii8xMzY3NzU3LzMzNDcyMzMxNi03NGY1ZTI3Yy0yODdmLTRhNWYtOGNkNi0yMGVkZmEwMDYzNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDkwMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTIzZjc1YmVlNjk4YjhkMjllNDgzOGYxMGIyODgxZWI0MzYzOTA1ZTA3N2Q4NzQyZTU1NWM0ZmMzNWM1MjJkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lh5F9m-lotCEUIQXnbSArpsc5bWKHACPrz9bmOuvhhM)

延伸這邊的建議，好奇想問一下現在的版本如果 lastestAction 是 pick 然後 member 是 userA，但 userA 沒有針對這篇文留言，不過另一個 followingMember B 有對這篇文留言，這樣的話 userB 的留言是不會被顯示出來嗎？

2024-05-29 10:14 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +  )
這邊把 `pick` 和 `comments` merge 之後 sorting 看起來有點不必要，因為 `sortedPicksAndComments` 只被用來判斷最新的 action 是 pick 還是 comments，不如直接比較 `picks[0]` 和 `comments[0]` 就好，可以省下 sorting 的迴圈。

2024-05-29 10:38 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +    <>
page 層的 root element 應為 `<main>`

2024-05-29 10:46 UTC, caesarWHLee commented on packages/mesh/graphql/query/get-user-following.ts
> +export const GetUserFollowing = gql`
一般常數命名小寫開頭就好，要大寫的話要寫成 GET_USER_FOLLOWING 才符合 convention。

2024-05-29 14:06 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +        <h1 className="title-1 line-clamp-2 mb-2 break-words">
建議用 h2 取代 h1，[reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page)

2024-05-30 02:55 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  Following,
修改於 [6e87bcd](https://github.com/readr-media/Sachiel/pull/764/commits/6e87bcd9f52d0819c3f0214efb04ffc63ebbb759)

2024-05-30 02:55 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  const { data } = await getClient().query<
修改於 [6e87bcd](https://github.com/readr-media/Sachiel/pull/764/commits/6e87bcd9f52d0819c3f0214efb04ffc63ebbb759)

2024-05-30 02:55 UTC, tyc67 commented on packages/mesh/graphql/query/get-user-following.ts
修改於 [6e87bcd](https://github.com/readr-media/Sachiel/pull/764/commits/6e87bcd9f52d0819c3f0214efb04ffc63ebbb759)

2024-05-30 02:59 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +    (a: any, b: any) =>
修改於 [6e87bcd](https://github.com/readr-media/Sachiel/pull/764/commits/6e87bcd9f52d0819c3f0214efb04ffc63ebbb759)

2024-05-30 02:59 UTC, tyc67 commented on packages/mesh/graphql/query/get-user-following.ts
>            story {
修改於 [6e87bcd](https://github.com/readr-media/Sachiel/pull/764/commits/6e87bcd9f52d0819c3f0214efb04ffc63ebbb759)

2024-05-30 03:00 UTC, tyc67 commented on packages/mesh/graphql/query/get-user-following.ts
> +                customId
修改於 [6e87bcd](https://github.com/readr-media/Sachiel/pull/764/commits/6e87bcd9f52d0819c3f0214efb04ffc63ebbb759)

2024-05-30 03:03 UTC, tyc67 commented on packages/mesh/graphql/query/get-user-following.ts
> +export const GetUserFollowing = gql`
修改於 [6e87bcd](https://github.com/readr-media/Sachiel/pull/764/commits/6e87bcd9f52d0819c3f0214efb04ffc63ebbb759)

2024-05-30 03:05 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +    <>
修改於 [6e87bcd](https://github.com/readr-media/Sachiel/pull/764/commits/6e87bcd9f52d0819c3f0214efb04ffc63ebbb759)

2024-05-30 04:09 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +              {storyPicksAndComments.picks?.slice(0, 4).map((data, index) => (
btw，在開發最新頁面的時候有同步確認這一塊的邏輯其他頁是否會跟社群頁有所不同，有以下討論：

![image](https://github.com/readr-media/Sachiel/assets/104348940/40428c2c-12cd-46ff-89be-3acf524bedd5)

目前結論是精選人數的呈現會先以有追蹤的人為主，但如果有追蹤的人的數量不足 4 人 (包含沒有有追蹤的人有精選），會由沒追蹤的人的頭像來補滿四個，這個可能跟你原本的認知有所不同，如果有問題可以再約個討論～

2024-05-30 06:26 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +    <Image
應該看 app router 版的 [onError](https://nextjs.org/docs/app/api-reference/components/image#onerror)，然後回應之前 YC 的問題，要改成 client component 處理，置換成 default 頭貼。

2024-05-31 07:40 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +              {storyPicksAndComments.picks?.slice(0, 4).map((data, index) => (
修改於 [ee650d4](https://github.com/readr-media/Sachiel/pull/764/commits/ee650d4ad03f840c716c02361922763a5e9de8fc)

2024-05-31 07:40 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +        <h1 className="title-1 line-clamp-2 mb-2 break-words">
修改於 [ee650d4](https://github.com/readr-media/Sachiel/pull/764/commits/ee650d4ad03f840c716c02361922763a5e9de8fc)

2024-05-31 07:40 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +  )
修改於 [ee650d4](https://github.com/readr-media/Sachiel/pull/764/commits/ee650d4ad03f840c716c02361922763a5e9de8fc)

2024-05-31 07:41 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +      const PickAndComment = comments?.find(
修改於 [ee650d4](https://github.com/readr-media/Sachiel/pull/764/commits/ee650d4ad03f840c716c02361922763a5e9de8fc)

2024-05-31 15:30 UTC, tyc67 commented on packages/mesh/app/social/_components/feed-comment.tsx
> +  comment: Story['comment'][number]
修改於 [278f2e1](https://github.com/readr-media/Sachiel/pull/764/commits/278f2e12b0327a238d127e5595b6521a59f13e9c)

2024-06-03 03:31 UTC, tyc67 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
![image](https://github.com/readr-media/Sachiel/assets/114332515/e826eca1-4811-48a0-ab55-5ef732f9c51d)


和 manzoo 討論以 text bytes 的長度 < 9 規則來顯示
修改於 [d82eb2b](https://github.com/readr-media/Sachiel/pull/764/commits/d82eb2be6e62415f57cd1ac263263e91b0fadae2)

2024-06-03 05:31 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +export const renderAvatar = (member: Member, px: number) => {
目前 `alt={${member.id}-avatar}` alt 的部分我用 `member.id` 做顯示, 因此直接傳入整個member 非 `member.avatar` , 想請問這邊用 avatar url 會比較好嗎?

2024-06-04 02:17 UTC, tyc67 commented on packages/mesh/types/graphql.ts
之後想導入 [GraphQL-Codegen](https://the-guild.dev/graphql/codegen) , 可否這部分另外PR處理？

2024-06-04 02:22 UTC, erase2004 commented on packages/mesh/types/graphql.ts
可

2024-06-04 02:22 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +    <Image
有關 Image loading 部分的 issue, 想另外和設計一起討論 沒有url, 有url但失效, network loading ...等使用情況的顯示方式。

2024-06-04 02:25 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +export const renderAvatar = (member: Member, px: number) => {
alt 文字直接用 'member avatar' 就好了？

2024-06-04 02:26 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
應該同步於設計稿上？

2024-06-04 02:33 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +export const renderAvatar = (member: Member, px: number) => {
修改於 [a198867](https://github.com/readr-media/Sachiel/pull/764/commits/a198867fcf3c9722d64f56f624e0643868d47b41)

2024-06-04 02:36 UTC, tyc67 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
ok, 我再請 manzoo 更新Figma

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/apollo/index.ts
> +      console.log(
這裡應該用 `console.error` ?

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/page.tsx
> +  const currentUser = await fetchUserFollowing(GET_USER_FOLLOWING, {
沒有理解 `fetchUserFollowing` 的參數增加 GraphQL schema 的用意，如果是要做 pagination 上的考量的話，應該用另外的 function 來處理？畢竟要抓更多內容的 `Pick` 或 `Comment`，應該不用重抓 `member` 的資料

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/page.tsx
> +    console.error('Error fetching user following:', error)
server-side error log 建議參考這個格式來處理
https://github.com/mirror-media/Adam/blob/f3bea8a9232512bb06fdc071cb4b5ba6895c5e13/packages/mirror-media-next/utils/log/shared.js#L132
這樣在 GCP Logging 上才能有更好的顯示
https://cloud.google.com/logging/docs/structured-logging

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
>    if (!story) {
這一行應該放在更前面的位置，這樣一堆使用到 `story` 的情境就不用加上 `?`

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +      const isMemberPickAndComment = comments.find(
變數命名有問題，`is` 開頭通常作為 boolean type 使用，但這裡卻當作 object，我會改用 `commentFromMember` 之類的名稱
ref: https://www.syncfusion.com/blogs/post/top-javascript-naming-convention

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +      if (matchingPickIndex === 1) {
`matchingPickIndex >= 1` 的情況下，都可以用既有 `matchingPickIndex > 1` 的處理邏輯？

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +  const followingWhoPicked = story?.pick.filter((pick) =>
這裡的變數命名應該是 `picksFromFollowing` ? 看資料結構，是 `Pick` 而不是 `Member`

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +  const followingWhoCommented = story?.comment.filter((comment) =>
這裡的變數命名應該是 `commentsFromFollowing` ? 看資料結構，是 `Comment` 而不是 `Member`

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +  const storyPickFiltered = [
`storyPickFiltered` 是藉由 `actionData?.picksData` 和剩餘的 `story?.pick` 來組成的，
我想 `processActions` 不要回傳 `null`，同時當中的 `picksData` 改用最多 4 則的話，這樣就不用多跑 `storyPicksWithoutActions` 和 `storyPickFiltered` 的處理了

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed.tsx
> +    const convertPickCount = (Math.floor(picksCount / 1000) / 10).toFixed(1)
命名應該是 `convertedPickCount` - 名詞，而非 `convertPickCount` - 動詞？

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
> +    return text.substring(0, maxByte).trim() + '...'
在 `text` 內容含有中文之類文字的情況下，顯示出來的長度明顯超過預想目標

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
> +  if (picksNum === 0 && commentsNum === 1) {
if-else 條件應該拆成以下結構
* picksNum === 0
  * commentsNum === 0
  * commentsNum === 1
  * commentsNum === 2
  * commentsNum > 2
* picksNum === 1
* picksNum === 2
* picksNum > 2

2024-06-04 06:10 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
> +  if (!actions) return null
搭配 `feed.tsx` 中，針對 `processActions` 回傳值的建議，Ln. 8 和 Ln. 120 的 `return null` 應該可以統一放到
`picksNum === 0 && commentsNum === 0` 的區塊中

2024-06-04 07:14 UTC, tyc67 commented on packages/mesh/apollo/index.ts
> +      console.log(
官方給的 [example](https://www.apollographql.com/docs/react/data/error-handling/#advanced-error-handling-with-apollo-link) 是用`console.log` , 這裡要改用 `console.error` 嗎?

2024-06-04 07:25 UTC, erase2004 commented on packages/mesh/apollo/index.ts
> +      console.log(
我想可以用 `console.error` 來記錄錯誤

2024-06-04 07:35 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +      if (matchingPickIndex === 1) {
這裡 pickTime < commentTime, 因此 latest-action 為 'Comment', `picksData` 至多情況為2組 [ Pick1, Pick2 ]

latest-action: 'Comment' 的 user, 先前也有做Pick的動作的話,
-  如果User Pick次序為2, 則 [ Pick2(User Pick), Pick1 ]
-  如果User Pick次序為3,.....9999, 則 [ Pick 9999(UserPick), Pick1 ]

2024-06-04 08:05 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +  const uniquePicks = Array.from(uniquePicksAndCommentsMap.values())
`uniquePicksAndCommentsMap`  轉成 array 之後命名只剩下 picks，邏輯不符

2024-06-04 08:31 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +  const storyPickFiltered = [
所有精選本篇文章的人中，如果 follwoingMember 有最新的動作 actionData 的話，avatar會以followingMember 的優先顯示, 不足的部分則由非追蹤者的avatar補足, 至多為4個avatar.
因此還是需要由Story所有的Pickdata取得非追蹤者但有精選的data

2024-06-04 08:38 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
>    if (!story) {
修正於 [cd341b8](https://github.com/readr-media/Sachiel/pull/764/commits/cd341b85e44918fc4a135bc4e7edf1f3016a6bdd)

2024-06-04 08:39 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +      const isMemberPickAndComment = comments.find(
修正於 [cd341b8](https://github.com/readr-media/Sachiel/pull/764/commits/cd341b85e44918fc4a135bc4e7edf1f3016a6bdd)

2024-06-04 08:39 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +  const followingWhoPicked = story?.pick.filter((pick) =>
修正於 [cd341b8](https://github.com/readr-media/Sachiel/pull/764/commits/cd341b85e44918fc4a135bc4e7edf1f3016a6bdd)

2024-06-04 08:39 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +  const followingWhoCommented = story?.comment.filter((comment) =>
修正於 [cd341b8](https://github.com/readr-media/Sachiel/pull/764/commits/cd341b85e44918fc4a135bc4e7edf1f3016a6bdd)

2024-06-04 08:39 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +    const convertPickCount = (Math.floor(picksCount / 1000) / 10).toFixed(1)
修正於 [cd341b8](https://github.com/readr-media/Sachiel/pull/764/commits/cd341b85e44918fc4a135bc4e7edf1f3016a6bdd)

2024-06-04 08:52 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  const currentUser = await fetchUserFollowing(GET_USER_FOLLOWING, {
這裡是參考 [useQuery](https://www.apollographql.com/docs/react/data/queries/#executing-a-query) 的 argument 設計, 讓 gql `query` 和 `variables` 在 function arguments 處理，增加可讀性 !? 

Pagination 目前還不確定如何實作, 要和 be 討論API設計後才比較清楚fetching的方式。

2024-06-04 09:25 UTC, tyc67 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
> +  if (picksNum === 0 && commentsNum === 1) {
修改於 [97b2841](https://github.com/readr-media/Sachiel/pull/764/commits/97b284116955f373e95ce531cc0e9e064ad8cdeb)

2024-06-04 09:25 UTC, tyc67 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
> +    return text.substring(0, maxByte).trim() + '...'
修改於 [97b2841](https://github.com/readr-media/Sachiel/pull/764/commits/97b284116955f373e95ce531cc0e9e064ad8cdeb)

2024-06-04 10:25 UTC, caesarWHLee requested changes

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +  const uniquePicks = Array.from(uniquePicksAndCommentsMap.values())
uniquePicksAndCommentsMap 轉成 array 之後命名只剩下 picks，邏輯不符

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +  const sortedUniquePicksByPickTime = uniquePicks.sort(
同上，命名應改為 `sortedUniquePicksAndComments`

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +function processedPicksAndCommentsData(
沒有要加註解的話建議改 function 名字為 `sortUniquePicksAndComments`，不然每次都要看實作內容才知道這個 function 做了什麼處理，不好維護

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +export const avatarLayer = ['z-[4]', 'z-[3]', 'z-[2]', 'z-[1]']
這就是我說要紀錄 z-index 的原因，如果沒有特別計入這邊 z-index 用法，之後加上其他各種 z-index 的使用在管理上就要全部找一遍，還是 @erase2004  覺得這個也要加到 tailwind.config.css 中管理？

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +export const renderAvatar = (avatar: string, px: number) => {
px 看起來看起來目前只能使用 28, 44，應該明確定義 px 的型別為 28 | 44

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +export const timeDifference = (date: string) => {
timeDifference, avatarLayer, renderAvatar 等共用 function 應放到 root/utils/  folder 中統一管理，因為都是跟 story 卡片顯示相關，建議可以叫做 story-display.ts 或是其他你覺得適合的名字

另外 timeDifference 命名有點籠統，一方面只帶一個參數看 function 名稱不知道是跟現在時間比較，一方面 function 是回傳顯示字串，看 function 名稱會以為是參數時間和現在時間的間距 (數值)，建議改成 `displayTimeFromNow`

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +        <div className="aspect-[2/1] overflow-hidden bg-multi-layer-light">
目前使用 parent 來固定比例呈現的方式如果圖片的長寬比不適 2:1 的話，以下圖為例，img 的實際大小是 600 x 400，目前的寫法會是把下面 100px 的高度給裁掉不顯示，可能要跟設計確認一下圖片的呈現這樣是否 ok，比較常見的方式應該是設定 object-fit: cover 同時把上下左右裁掉的方式

![image](https://github.com/readr-media/Sachiel/assets/104348940/a49d80be-9458-45fc-9301-d9601266fb66)

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +  )
這裡跑了一次 loop 來檢查所有的 story picks，可以直接改成以下寫法一次把兩種 picks filter 出來，下面就不用在 filter 一次了

```
  const picksByFollowing: Story['pick'] = []
  const picksByStranger: Story['pick'] = []
  story?.pick.forEach((pick) =>
    followingMembers.has(pick.member.id)
      ? picksByFollowing.push(pick)
      : picksByStranger.push(pick)
  )
```

2024-06-04 10:25 UTC, caesarWHLee commented on packages/mesh/app/social/_components/feed.tsx
> +function processActions(picks: Story['pick'], comments: Story['comment']) {
這個 function 同時要做以下事情：
1. 決定 latestAction 到底是 pick 還是 comment 
2. 準備 `FeedLatestAction` 需要呈現的資料 `slicedPicks`, `slicedComments`
3. 決定 Feed 下方的 comment 是否要呈現，是的話要呈現什麼資料

這些邏輯全部疊加在這個 function 中讓這個 functin 非常難理解，最後產出的 actions 名字看起來是 array of actions，實際上卻存了 `picksNum`, `commentsNum`, sliced 過後的 `picksData`, sliced 過後的 `commentsData`，甚至還包含了 `FeedLatestAction` 不會用到的 `feedComment`。

根據 single responsibility principle 的原則，一個 function 最好只處理一件事就好，建議上面三件事情分別拆成三個 function，先由 getLatestAction 來取得最新的 action 到底是 pick 還是 comment (type)，再把該 type 連同 picks、comments 傳進 `FeedLatestAction` 中，在裡面去處理 各種情況下的顯示邏輯，最後 Feed 下方的 comment 可以直接由第三個 function 來取得 displayComment，displayComment 為 falsy 的狀況下直接隱藏就好，不需要同時存 isShowComment 和 comment。

建議如果之後 function 的命名沒辦法說明 function 的行為的話，可以思考是否是因為 function 中同時做了太多事情導致，適當的拆出來會讓後續的維護和開發都更加順利。

2024-06-04 14:39 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +  const currentUser = await fetchUserFollowing(GET_USER_FOLLOWING, {
Tsuki 的意思應該是 fetchUserFollowing 應該是綁定 `GET_USER_FOLLOWING ` 這個 gql schema，理論上 query 值不會改變直接放在 `fetchUserFollowing` 裡面，只保留 variables 當作參數動態傳入就好， `useQuery` 的寫法是通用給所有的 gql query 所以才會需要特別傳入 schema

2024-06-05 03:38 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +function processedPicksAndCommentsData(
修改於 [7c1520c](https://github.com/readr-media/Sachiel/pull/764/commits/7c1520c2b3046593ccf7aad6763e2f07197e3685)

2024-06-05 03:38 UTC, tyc67 commented on packages/mesh/apollo/index.ts
> +      console.log(
修改於 [7c1520c](https://github.com/readr-media/Sachiel/pull/764/commits/7c1520c2b3046593ccf7aad6763e2f07197e3685)

2024-06-05 03:38 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  const currentUser = await fetchUserFollowing(GET_USER_FOLLOWING, {
修改於 [7c1520c](https://github.com/readr-media/Sachiel/pull/764/commits/7c1520c2b3046593ccf7aad6763e2f07197e3685)

2024-06-05 03:38 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +    console.error('Error fetching user following:', error)
修改於 [7c1520c](https://github.com/readr-media/Sachiel/pull/764/commits/7c1520c2b3046593ccf7aad6763e2f07197e3685)

2024-06-05 03:39 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  const uniquePicks = Array.from(uniquePicksAndCommentsMap.values())
修改於 [7c1520c](https://github.com/readr-media/Sachiel/pull/764/commits/7c1520c2b3046593ccf7aad6763e2f07197e3685)

2024-06-05 03:39 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  const sortedUniquePicksByPickTime = uniquePicks.sort(
修改於 [7c1520c](https://github.com/readr-media/Sachiel/pull/764/commits/7c1520c2b3046593ccf7aad6763e2f07197e3685)

2024-06-06 02:35 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +      if (matchingPickIndex === 1) {
In the condition  latestAction=Comment  ->  if the user who made the latest comment also has a pick for the current story (comment + pick) ->  move the user's pick data to the first element of `picksData`

修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 02:36 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +  const storyPickFiltered = [
修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 02:36 UTC, tyc67 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
> +  if (!actions) return null
修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 02:45 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +export const avatarLayer = ['z-[4]', 'z-[3]', 'z-[2]', 'z-[1]']
我的想法為, 各 page component 的 `z-index` 於 constants/z-index.ts 管理, 若為共用component且跨page的 `z-index` 則由 `tailwind.config` 中設定

在`feed`中 avatar index 設定, 因 tailwind css dynamic classname 會有JIT mode抓不到 import classname的狀況發生, 改用 inline-styles 的 style attribute 取代 tailwind css default classname 處理. 

修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 02:46 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +export const renderAvatar = (avatar: string, px: number) => {
修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 02:46 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +export const timeDifference = (date: string) => {
修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 02:47 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +        <div className="aspect-[2/1] overflow-hidden bg-multi-layer-light">
有和 manzoo 確認, 改為 object-fit: cover 處理

修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 02:47 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +  )
修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 03:04 UTC, tyc67 commented on packages/mesh/app/social/_components/feed.tsx
> +function processActions(picks: Story['pick'], comments: Story['comment']) {
`processStoryActions` 處理render logic為:

1. 確認是 pick, comment or pick + comment
2. only pick / only comment case -> story action data 不需額外處理 -> 給 `FeedLatestAction` and `FeedComment` 做 render
3. pick + comment case -> 先確認 latestActionType 為 pick or comment 
- latestActionType=pick -> 確認 latestActionPickMember 是否也有對本篇文章 comment -> 若有調整 commentsData 順序
- latestActionType=pick -> 確認 latestActionCommentMember 是否也有對本篇文章 pick -> 若有調整picksData 順序
- 再將順序處理後的Data 給 `FeedLatestAction` and `FeedComment` 做 render

看上述新版的整理是否有增加 readability and maintainability 

修改於 [63b65ba](https://github.com/readr-media/Sachiel/pull/764/commits/63b65ba310b434d7497ee0034f2af66b1f9a22be)

2024-06-06 06:50 UTC, caesarWHLee approved these changes
LGTM 👍 🚀 ⭐

2024-06-06 06:55 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +    console.error('Error fetching user following:', error)
@erase2004 錯誤處理之後再順一次邏輯，包含從 header 中拿取 `x-cloud-trace-context` 、 Axios error handling、GQL error handling 等一起討論，這邊個 PR 有把錯誤顯示出來就好。

2024-06-06 07:57 UTC, erase2004 approved these changes
Well done 👏

2024-06-06 07:57 UTC, erase2004 commented on packages/mesh/app/social/_components/feed-latest-action.tsx
> +    const shortText = new TextDecoder().decode(unit8).replace(/\uFFFD/g, '')
magic 👏

2024-06-06 07:57 UTC, erase2004 commented on packages/mesh/app/social/_components/render-avatar.tsx
> +export const renderAvatar = (avatar: string, px: 28 | 44) => {
放在 `_components` 底下但不是用大寫開頭命名的元件 🤔  cc @caesarWHLee

2024-06-06 08:03 UTC, tyc67 commented on packages/mesh/app/social/_components/render-avatar.tsx
> +export const renderAvatar = (avatar: string, px: 28 | 44) => {
sorry, 我修正一下

2024-06-06 08:06 UTC, caesarWHLee commented on packages/mesh/app/social/_components/render-avatar.tsx
> +export const renderAvatar = (avatar: string, px: 28 | 44) => {
直接改成 react component 就 ok 了，命名改一下、參數要改成 props object

2024-06-06 08:08 UTC, tyc67 commented on packages/mesh/app/social/_components/render-avatar.tsx
> +export const renderAvatar = (avatar: string, px: 28 | 44) => {
修改於 [3c267b3](https://github.com/readr-media/Sachiel/pull/764/commits/3c267b3f6570b10e69a7732e37966d39b1783b4a)

2024-06-06 08:11 UTC, caesarWHLee commented on packages/mesh/app/social/_components/render-avatar.tsx
> +export const renderAvatar = (avatar: string, px: 28 | 44) => {
其實應該直接叫 Avatar 就好，就像是 Icon component 一樣，畢竟 react component function 的目的就是 render jsx，不過我可以之後改成共用元件的時候一併修改就好，先 merge 吧。

2024-06-06 08:29 UTC, tyc67 commented on packages/mesh/app/social/_components/render-avatar.tsx
> +export const renderAvatar = (avatar: string, px: 28 | 44) => {
那...再拜託後續改成共用元件的人調整了, 或許之後另一個PR我自己來收拾, tks!

修改於 [21613d0](https://github.com/readr-media/Sachiel/pull/764/commits/21613d0b672bd70a30cce707aeeb84a4622f41a8)

2024-06-06 08:44 UTC, merged