(WIP)feat(mesh): profile page
readr-media/Sachiel pull request #789
Opened 2024-06-27 18:02 UTC by LinHeMa

2024-07-03 02:13 UTC, tyc67 requested changes
- `type.ts` , `utils.ts`  參考 [folder structure convention](https://paper.dropbox.com/doc/Convention--CSIFAAQU76EqjKKvb3UjEws1Ag-yDGKaFsVLerISYtxFlM9e) 
- text typography 參考 `styles/global.css` 
- button 參考 `components/button.tsx` 
- 建議 Component 架構, 增加可讀性
```jsx
<ProfileHeader/>
<Profile>
  <UserIntro/>
  <ButtonLists/>
  <UserNumbers/>
  <TabLists/>
  <StoryList/>
<Profile/>
```

2024-07-03 07:31 UTC, caesarWHLee reviewed
先就目前看到的進度給回饋

2024-07-03 07:31 UTC, caesarWHLee commented on packages/mesh/app/profile/[type]/[id]/page.tsx
publisher 和 member 的 profile 建議拆成兩個 folder (route) 就好，避免不必要的複雜度，像是目前要看 member 的 profile 的話其實 url 帶 http://localhost:3000/profile/eee/19?user=19 或是 http://localhost:3000/profile/aaaaa/19?user=19 其實都可以看到某個 member 的 profile，邏輯上不太正確。

建議可以跟 PM 確認一下兩個頁面的 route，看是要 profile/member/[id], profile/publisher/[id] 還是 profile/[memberId], profile/publisher/[id] 切成兩個 page.tsx 然後各自的 components 放到對應的 folder 中會比較好理解維護

2024-07-03 07:31 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/member-profile.tsx
> +  GetMemberProfileQuery,
加上 type keyword 來區別 types 和 components

2024-07-03 07:31 UTC, caesarWHLee commented on packages/mesh/graphql/query/profile.gql
gql files 目前的 conventions 是依照 gql schema 來放，以 `GetMemberProfile`  這個 query 來說要拿的是 `member` 這個 list，所以應該移到 member.gql 裡面管理

命名公式：[listName].gql

2024-07-03 07:31 UTC, caesarWHLee commented on packages/mesh/graphql/query/publisherProfile.gql
gql files 目前的 conventions 是依照 gql schema 來放，以 `GetPublisherProfile`  這個 query 來說要拿的是 `publisher` 這個 list，所以應該移到 publisher.gql 裡面管理

命名公式：[listName].gql

2024-07-03 07:31 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/member-profile.tsx
> +    return <div>Error</div>
建議加上 TODO: comment 以利日後處理

2024-07-03 07:31 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/member-profile.tsx
> +    return <div>Error</div>
建議加上 TODO: comment 以利日後處理

2024-07-03 07:31 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/member-profile.tsx
> +    <div className={`flex ${contentHeight}  flex-col bg-white`}>
Page 的 root element 要使用 `main`

2024-07-03 07:31 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/member-profile.tsx
> +    : 'min-h-screen-without-header-nav sm:min-h-sm-screen-without-header-footer'
之前的 layout 沒寫好所以會需要 chilrdren 各自計算高度來填滿螢幕高，目前修改一版在 [PR](https://github.com/readr-media/Sachiel/pull/791)，這個版本下就不需要再另外計算高度，可以在 root elemnt 上面設置 className="grow" 就會讓 root element 的高長滿畫面

同樣的，再下一層的 component 像是 profile 沒有精選的狀況下要顯示 `這個人還沒有精選新聞` 的區塊，也可以一路設定 parent `flex`, child `grow` 的方式來填滿螢幕

2024-07-09 02:36 UTC, tyc67 reviewed
- 依照 design system, 應該不會有 `leading` 的 classname
- publisher 和 member 的 `_component` 看起來有多個一樣的component, 應該可以共用, 未來不需要維護兩套 css ? 
- `alt="alt"` 也許可以給一個可以辨識的message?

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[userId]/page.tsx
> +        followerCount={userFollowerCount || 0}
和 Ln.41 一樣?

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/layout.tsx
> +      <body className="flex min-h-screen grow flex-col">{children}</body>
應該是加在Page layer Layout ?

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[userId]/_component/publisher-page.tsx
> +  const emptyStatusMaxHeight = 'max-h-[calc(100%_-_152px)]'
沒有condition operator, 是否直接寫在 classname?

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/member/[userId]/layout.tsx
> +    </div>
- `ProfileLayout` 應該只需要一個在 `profile/layout`
- `<ProfileHeader />`,`<Body>`,`<ProfileFooter />`,應該可以直接寫在layout裡面
- `<main>` 目前用於`<Page/>`

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/_components/body.tsx
> +    <main className="flex min-h-screen flex-col bg-white pb-[theme(height.nav.default)] pt-[theme(height.header.default)] sm:pb-0 sm:pl-[theme(width.nav.sm)] sm:pt-[theme(height.header.sm)] md:pl-[th
可以用 `global.css` 的 `primary-container`

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/styles/global.css
> +
[figma guideline](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=3889-258100&t=72HNFgKG87Mm4ISv-4) 似乎沒有這個, 可能需要和設計確認

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/styles/global.css
> +
[figma guideline](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=3889-258100&t=72HNFgKG87Mm4ISv-4) 似乎沒有這個, 可能需要和設計確認

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    'md-fixed-w': 'button-large h-[38px] px-4 py-2 rounded-md sm:w-[180px]', // Lightbox Chip
應該是用md, 由外層控制寬度?

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[userId]/_component/profile-button-list.tsx
> +const ProfileButtonLIst: React.FC<ProfileButtonLIstProps> = ({
- ProfileButtonL"i"st
- 看起來只有color 不同, 應該不需要兩個 `profile-button-list.tsx`

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[userId]/_component/publisher-page.tsx
> +  const [_, setCategory] = useState<TabCategory>(TabCategory.publish)
publisher-page 的 Tab 只有"報導", 應該不需要這個 state ?

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/utils/profile-tab.ts
> +      return createTabFilter(PUBLISHER_TAB_KEYS)
Ln26, Ln28, 是否直接 inline 寫即可? 只有 [FOLLOWER,SPONSORED] 和 [PICK,FOLLOWER,FOLLOWING] 兩種情境的話, 是不是不需用到 `Set` 和 `createTabFilter`

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[userId]/_component/user-profile.tsx
> +            src={avatar || '/images/default-avatar-image.png'}
是否可以用 `icon-avatar-default` ?

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[userId]/_component/publisher-page.tsx
> +          pickCount={pickCount || 0}
如果移至 Page 做 Check, Page 應該就不用 `pickCount={null}` ?

2024-07-09 02:36 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[userId]/_component/publisher-page.tsx
> +      { key: TabKey.SPONSORED, value: '9999次' },
可以考慮 naming
```
  const userStatusList = [
    { tab: TabKey.PICK, count: pickCount },
    { tab: TabKey.FOLLOWER, count: followerCount },
    { tab: TabKey.SPONSORED, count: '9999次' ,
  ];
```

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/graphql/query/publisher.gql
> +query GetPublisherProfile($memberId: ID) {
這裡應該叫 publisherId?

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/graphql/query/publisher.gql
> +  stories(where: { source: { id: $memberId } }) {
1. syntax error，stories 的 where condition 應該要用 `{equals: $memberId }` 包起來
```
stories(where: { source: { id: {equals: $memberId} } }) {
```

建議之後 gql 的 query 可以寫完丟到 playground 或直接在 playground 撰寫，可以直接查看文件：
![image](https://github.com/readr-media/Sachiel/assets/104348940/a4668a91-3798-41e1-b4d8-2f9fa379c363)

2. stories 應該要加上 take，可以和 PM 討論每頁的數量，或是至少開發上先給一個定值，目前 publisherId = 1 的狀況下會有一千多筆資料，造成 gql server response time 過久
 
3. 承接上一點，新增 storiesCount (where: { source: { id: {equals: $memberId} } }) (平行 stories) 來拿取總 stories 數量，之後用於 infinite-scroll 上

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/graphql/query/publisher.gql
> +  }
新增 `storiesCount (where: { source: { id: {equals: $memberId} } })` (平行下面 stories) 來拿取總 story 數量，之後用於 infinite-scroll 上

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/graphql/query/member.gql
> +    picks: pick(where: { kind: { equals: "read" } }) {
1. is_active 需要是 true `pick(where: { kind: { equals: "read" }, is_active: {equals: true} })`
2. 加上 take (同 publiser.gql comment)
3. 加上 picksCount (同 publiser.gql comment)

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/graphql/query/member.gql
> +    books: pick(where: { kind: { equals: "bookmark" } }) {
1. is_active 需要是 true `pick(where: { kind: { equals: "bookmark" }, is_active: {equals: true} })`
2. 加上 take (同 publiser.gql comment)
3. 加上 booksCount (同 publiser.gql comment)

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/graphql/query/member.gql
> +    picks: pick(where: { kind: { equals: "read" } }) {
1. is_active 需要是 true `pick(where: { kind: { equals: "read" }, is_active: {equals: true} })`
2. 加上 take (同 publiser.gql comment)
3. 加上 picksCount (同 publiser.gql comment)

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/app/profile/publisher/[userId]/page.tsx
`publisher/[userId]` > `publisher/[publisherId]`

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/app/profile/publisher/[userId]/page.tsx
> +  const userId = params.userId
`userId` > `publisherId`

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[userId]/page.tsx
`userId` > `customId`

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/graphql/query/member.gql
> +query GetMemberProfile($memberId: String) {
`$memberId` >`customId`

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[userId]/_components/user-profile.tsx
> +          <p className="profile-title sm:profile-title-3 text-primary-700">
這邊應該是 `sm:title-1` 不需要另外新增 class `.profile-title-3`

目前網站所有字體設定都以對照[設計稿](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=3889-258100&t=rG9OkOG5IC6pStky-4)設定對應 className

元件的字體可以在 figma 上的這邊看到對應的 className，格式是 lower case kebab case
![截圖 2024-07-09 中午12 01 45](https://github.com/readr-media/Sachiel/assets/104348940/1903b1d7-1ea1-4890-b5da-506909a87bd3)

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/comment.tsx
> +          <p className="caption-3 leading-[18px] text-primary-500">
這裡應該是 `caption-1`，見 `user-profile.tsx` 的 comment

![image](https://github.com/readr-media/Sachiel/assets/104348940/c204f1cc-68c3-48e4-b939-3965e7c5ba70)

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/comment.tsx
> +          <button className="caption-3 leading-[18px] text-primary-500">
這裡應該是 `caption-1`，見 `user-profile.tsx` 的 comment

2024-07-09 04:30 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/comment.tsx
> +          <p className="caption-3 leading-[18px] text-primary-600">
這裡應該是 `caption-1`，見 `user-profile.tsx` 的 comment

2024-07-09 06:40 UTC, LinHeMa commented on packages/mesh/graphql/query/publisher.gql
> +  stories(where: { source: { id: $memberId } }) {
目前跟PM討論take 20

2024-07-09 16:19 UTC, LinHeMa commented
> * 依照 design system, 應該不會有 `leading` 的 classname
> * publisher 和 member 的 `_component` 看起來有多個一樣的component, 應該可以共用, 未來不需要維護兩套 css ?
> * `alt="alt"` 也許可以給一個可以辨識的message?
第一點與第三點已解決，第二點的話當初是為了考慮到不同的身份各自擁有自己的component，未來如果有需求的話可以考慮整併，目前先維持寫法。🙏

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/graphql/query/member.gql
> +    pickCount(where: { kind: { equals: "read" }, is_active: { equals: true } })
align alias picks to `picksCount`

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/graphql/query/member.gql
> +    pickCount(where: { kind: { equals: "read" }, is_active: { equals: true } })
align alias picks to `picksCount`

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/_components/user-profile.tsx
> +          <p className="profile-title  text-primary-700">{name}</p>
`sm:title-1` 沒補到

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/page.tsx
> +    <>
用 `<main className="flex grow flex-col">` 取代讓每個頁面都有 main tag

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/publisher/[publisherId]/page.tsx
> +    <main className="flex h-full grow flex-col">
應該不用 `h-full` ?

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/index.tsx
目前確定不用 `compoundComponet` 的情況下應該不用多這一層的 container，可以把對應的 type 搬到 `comment.tsx` 之中，另外 useCommentLogic.tsx 建議直接搬到 package root 的 hooks 中，naming convention 一樣是 `lower-kebab-case.tsx`

這樣一來的話 comment folder 就不用保留，剩下 `comment.tsx` 就好

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/index.tsx
> +export type CommentData = CommentProps['data']
這個 type 好像沒用到

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/index.tsx
> +import { StoryItem } from '../../member/[customId]/_components/article-card'
`import { type StoryItem}`

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +  const [showData, setShowData] = useState(picksData)
`showData` 命名有點太籠統，可以直接叫做 `picksOrBookmarks` 或之類的命名，useState 也應該要把兩個 type 都包含進來，可以考慮用 type alias 定義 `Picks` 和 `Bookmarks`

`useState<Picks | Bookmarks>(picksData)`

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +  bookmarkData,
bookmarks，複數 ＋ 不用 Data 後綴

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +  picksData,
不用 Data 後綴

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/_components/article-card-list.tsx
> +  id,
id 命名太籠統，只看 component 不知道是誰的 id

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/_components/article-card-list.tsx
> +  showData,
比照 `member-page.tsx useState` 修改命名

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/comment.tsx
> +  data,
直接命名叫 comment 就好

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/comment.tsx
> +          <div className="mr-2 h-7 w-7 overflow-hidden rounded-full">
直接使用共用元件 `<Avatar src={data.member?.avatar} size="m">` ，無需自行帶入 default-avatar-image.png

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/publisher/[publisherId]/page.tsx
> +  const userLogo = userData.logo || '/images/default-avatar-image.png'
fallback 可以交給 <Avatar/> 元件處理就好，不用重複 hardcode 在這邊

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/_components/user-profile.tsx
> +          <Image
建議改用 `<Avatar>` 共用元件處理，可以擴充元件的 size，新增 xxl 對應 w-20 h-20，RWD 部分這邊可以寫成

```
<Avatar size="xl" src={avatar} extra="sm:hidden"/>
<Avatar size="xxl" src={avatar} extra="hidden sm:inline-block"/>
```

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/publisher/[publisherId]/_component/user-profile.tsx
> +          <Image
同 `member/../user-profile.tsx` 的 comment 改成使用 `<Avatar>`，不需要重複的 `default-avatar-image.png`

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/comment.tsx
> +      <div className="flex items-center justify-between md:hidden">
建議上方加入 jsx comment `{/* mobile comment info */}` 增加可讀性

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/comment.tsx
> +        <div className="mr-2 hidden h-7 min-h-7 w-7 min-w-7 overflow-hidden rounded-full md:flex">
建議加上註解 `{/* non-mobile comment avatar */}`

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment/comment.tsx
> +          <Image
同 Ln 38 改成使用 `<Avatar>`

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/publisher/[publisherId]/_component/story-card-list.tsx
> +        {storyData.map((story, idx) => {
add TODO: comment to remind adding infinite-scroll in the future

2024-07-10 04:29 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/_components/article-card-list.tsx
> +        {showData.map((pick, idx) => {
add TODO: comment to remind adding infinite-scroll in the future

2024-07-10 15:09 UTC, tyc67 commented
> > * 依照 design system, 應該不會有 `leading` 的 classname
> > * publisher 和 member 的 `_component` 看起來有多個一樣的component, 應該可以共用, 未來不需要維護兩套 css ?
> > * `alt="alt"` 也許可以給一個可以辨識的message?
> 
> 第一點與第三點已解決，第二點的話當初是為了考慮到不同的身份各自擁有自己的component，未來如果有需求的話可以考慮整併，目前先維持寫法。🙏

我會建議趁現在記憶尤新的時候調整 Component 設計, 不知道 @caesarWHLee  的看法?

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/components/button.tsx
> +    md: 'w-full button-large h-[38px] px-5 py-2 rounded', // Secondary Button
應該是由外層控制寬度?

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/layout.tsx
> +      <body className="flex min-h-screen grow flex-col">{children}</body>
RootLayout 應該不會給 flex, 由各 Page layout 控制

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[publisherId]/_component/publisher-page.tsx
> +        <ProfileButtonLIst buttonList={buttonList} />
<ProfileButtonL "i" st />

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[publisherId]/_component/publisher-page.tsx
> +  const userStatusList = [{ key: TabKey.SPONSORED, count: '9999次' }]
建議 naming 不要用 `key`, 可以用`tab`,`tabKey`,`tabTitle`.... or 其他, 在 `<UserStatusList />` 的`{key}` 可讀性會比較好

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/tab.tsx
> +      className="flex h-[48px] w-full items-center justify-around  border-b border-t border-[rgba(0,9,40,0.1)]
border color 應為 design system 的顏色

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[publisherId]/_component/article-card.tsx
> +        className={`flex flex-col p-5 after:absolute after:bottom-1 after:h-[1px] after:w-[calc(100%-40px)] after:bg-[rgba(0,0,0,0.1)] md:line-clamp-3 md:pt-[12px] md:after:hidden ${
bg-color 應為 design system 的顏色

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[publisherId]/_component/tab.tsx
> +      className="flex h-[48px] w-full items-center justify-around  border-b border-t border-[rgba(0,9,40,0.1)]
border color 應為 design system 的顏色

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/article-card-list.tsx
> +              className="relative w-full bg-white md:h-full md:rounded-md md:shadow-[0_2px_2px_0px_rgba(0,9,40,0.1)]"
shadow color 應為 design system 的顏色

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[publisherId]/_component/story-card-list.tsx
> +              className="relative h-full w-full bg-white md:rounded-md md:shadow-[0_2px_2px_0px_rgba(0,9,40,0.1)]"
shadow color 應為 design system 的顏色

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[publisherId]/_component/story-card-list.tsx
> +  }
在 `/publisher/[publisherId]` route 底下 userType 應該都是 publisher, 這裡是否還需要做 conditional ?

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +  ]
建議 naming 不要用 key 和 value

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +          pickCount={pickCount || 0}
`<Page/ >` 已經做null check, 這裏應該不用在做一次

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/user-status-list.tsx
> +    {userStatusList.map(({ key, value }) => (
建議 naming 不要用 key , value。 不利於可讀性及維護性

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/article-card.tsx
> +        className={`flex flex-col p-5 after:absolute after:bottom-1 after:h-[1px] after:w-[calc(100%-40px)] after:bg-[rgba(0,0,0,0.1)] md:line-clamp-3 md:pt-[12px] md:after:hidden ${
bg-color 應為 design system 的顏色

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/article-card.tsx
> +}
`isCommentShow = category !== TabCategory.BOOKMARKS`

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/article-card.tsx
> +  data: NonNullable<StoryItem>
建議 naming 可用 `story` or `storyData` ...etc

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/_components/comment/useCommentLogic.tsx
> +export const useCommentLogic = (
這個custom hook 是不是放在 `hooks/`

2024-07-10 17:07 UTC, tyc67 commented on packages/mesh/app/profile/_components/comment/useCommentLogic.tsx
> +    if (!commentRef.current) return
`if (!commentRef.current || !isTooLong) return`

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/hooks/use-comment-logic.tsx
> +    if (!isTooLong) return
Ln.33 有了, 這邊記得刪掉

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[publisherId]/page.tsx
> +  console.log(publisherId)
remove debug `console.log()`

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/_components/article-card.tsx
> +  data: NonNullable<StoryData>
variable naming `story` ,`storyData` ...etc

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/_components/user-profile.tsx
> +          )}
是否少了 publisher 的情境 ? [figma](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=6140-143687&t=uSiJ6hnjLe6GuxdE-4)

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/publisher/[publisherId]/_component/publisher-page.tsx
> +  const userStatusList = [{ tabName: TabKey.SPONSORED, count: '9999次' }]
是否少了 FOLLOWER ?

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/_components/user-status-list.tsx
> +        <p className="profile-title-2 text-primary-700">{count}</p>
如果是 count = 990000 是否應該是顯示 99.9萬, [figma](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=6140-139734&t=uSiJ6hnjLe6GuxdE-4)

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +        memeberId={memeberId}
member

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +  memeberId: string
memberId

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/visitor-page.tsx
> +        memeberId={memberId}
memberId

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/page.tsx
> +          memeberId={userData.id}
memberId

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/article-card-list.tsx
> +  memeberId,
memberId

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/visitor-page.tsx
> +          pickCount={pickCount || 0}
`<Page/>` 已經做null check

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +          pickCount={pickCount || 0}
`<Page/>` 已經做null check

2024-07-11 10:44 UTC, tyc67 commented on packages/mesh/app/profile/_components/tab.tsx
> +  category: TabCategory
naming 建議用 `TabCategory` or `TabOOXX` ...etc, 避免與 CMS 的 Category 混淆

2024-07-12 02:43 UTC, LinHeMa commented on packages/mesh/app/profile/_components/user-profile.tsx
> +          )}
這個詳見 [slack_mesh](https://mirrormedia.slack.com/archives/C0716CSQNVD/p1719388146534159)

2024-07-12 06:31 UTC, tyc67 commented on packages/mesh/app/profile/_components/user-profile.tsx
> +          )}
PM 說保留樣式? [slack](https://mirrormedia.slack.com/archives/C0716CSQNVD/p1720755161185369?thread_ts=1719388146.534159&cid=C0716CSQNVD)

2024-07-12 06:47 UTC, LinHeMa commented on packages/mesh/app/profile/_components/user-profile.tsx
> +          )}
先新增假資料（以回報在slack與PM確認）

2024-07-15 02:42 UTC, tyc67 commented on packages/mesh/app/profile/_components/article-card-list.tsx
> +  ) => React.ReactNode
為何採用 React.Node,而不是寫在Component 裡裏? React.Node 的開放性在這裏是否有其他的用途?

2024-07-15 02:42 UTC, tyc67 commented on packages/mesh/app/profile/_components/tab.tsx
> +          >
`${tabCategory === tabCategory ? activeTabStyle : inactiveTabStyle}`

2024-07-15 02:42 UTC, tyc67 commented on packages/mesh/app/profile/_components/user-profile.tsx
> +type userType = 'member' | 'visitor' | 'publisher'
各 component 的 type UserType, 來源應統一, 建議可以整理一下

2024-07-15 02:48 UTC, LinHeMa commented on packages/mesh/app/profile/_components/tab.tsx
> +          >
想問換成下面的寫法是有什麼技術上的建議嗎？
還是說是比較屬於偏好的部分呢？

2024-07-15 02:50 UTC, LinHeMa commented on packages/mesh/app/profile/_components/article-card-list.tsx
> +  ) => React.ReactNode
我可能會需要了解你的問題，我這邊處理的原因是因為story的資料節點跟pick不同，所以讓render function可以custom

2024-07-15 04:17 UTC, caesarWHLee commented on packages/mesh/graphql/query/member.gql
> +        commentCount
`commentCount` 重複出現

2024-07-15 04:17 UTC, caesarWHLee commented on packages/mesh/graphql/query/member.gql
> +        commentCount
`commentCount` 重複出現

2024-07-15 04:17 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/article-card.tsx
> +        {isCommentShow && (
建議：與其把 `category` 和 `userType` 傳進 `ArticleCard`，不如改成傳 `showComment` (`shouldShowComment`, `isShowComment` 都可)，由三個 page 層去決定要不要 show comment，這樣 `PublisherPage` 就直接帶 `showComment={false}` 而剩下兩個 page 再依照 TabCategory 來決定是否 show comment，日後維護其中一個 page 的時候不需要知道所有 pages 的 comment 顯示邏輯，可以專注在要改的功能上面

2024-07-15 04:17 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/article-card.tsx
> +  const authorComment =
這邊好像沒有處理到 comment 要是該 member 的才算，如果是之後才會補上的功能建議加上 TODO comment

2024-07-15 04:17 UTC, caesarWHLee commented on packages/mesh/hooks/use-comment-logic.tsx
這個 hook 應該只要處理 clamp style 邏輯就好，redirect 邏輯應該直接拆出來在 comment 的 `onClick` function 中直接處理就好

`use-comment-logic` -> `use-comment-clamp`

2024-07-15 04:17 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment.tsx
> +        onClick={handleToggleClamp}
搭配 `use-comment-logic` 的 comment，這邊應該直接在用一個 callback function 來處理 onClick，把 redirect 和 use-comment-clamp 邏輯區隔

```
onClick={() => {
  if (width > 960) {
     // hadle redirect
  }else {
     // handle toggle clamp 
  }
}}
```

2024-07-15 04:57 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/tab.tsx
> +          >
插個話，原本的寫法 `tabActiveStyle` 應該改成 `tabStyle`，因為每個 tab 都有可能是 `activeStyle` 或是 `inactiveStyle`

2024-07-16 01:53 UTC, tyc67 commented on packages/mesh/app/profile/_components/article-card-list.tsx
> +  ) => React.ReactNode
在 `<ArticleCardList/>` 有較開放性的 items and renderItem 設計, 然目前只有 `<ArticleCard />` 使用情境,  在 props property 邏輯上我個人會選擇, 給你參考

```javascript
interface ArticleCardListProps {
  items: StoryData | Picks | Bookmarks
  userType: string
  emptyMessage: string
  category?: TabCategory
  memberId?: string
  avatar?: string
  name?: string
}

      {items.map((item, index) => {
        const isLast = index === items.length - 1
        return (
          <li
            key={index}
            className="relative w-full bg-white md:h-full md:rounded-md md:drop-shadow"
          >
            items === storydata ? (
              <ArticleCard
                storyData={item}
                isLast={isLast}
                userType={userType}
              />
            ) : (
              <ArticleCard
                storyData={item.story}
                isLast={isLast}
                memberId={memberId}
                avatar={avatar}
                category={category}
                name={name}
                userType={userType}
              />
            )}
          </li>
        )
      })}

```

2024-07-16 01:57 UTC, tyc67 commented on packages/mesh/app/profile/_components/tab.tsx
> +          >
> 想問換成下面的寫法是有什麼技術上的建議嗎？ 還是說是比較屬於偏好的部分呢？

已經有 props 已有 `tabCategory` state, 可以不用另外使用 `tabActiveStyle` 去做 condition , 如果 tablist 中的 tabCategory === 當前的 tabCategory state, 應該就是 activeTabStyle, 若不等於則是 inactiveTabStyle

2024-07-18 09:47 UTC, tyc67 commented on packages/mesh/types/profile.ts
> +export type userType = 'member' | 'visitor' | 'publisher'
應為 "U"serType

2024-07-18 09:47 UTC, tyc67 commented on packages/mesh/app/profile/_components/user-profile.tsx
> +        <Avatar size="xl" src={avatar} extra="sm:w-20 sm:h-20 object-cover" />
媒體個人檔案的avatar形式似乎不同 ? , [figma](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=6140-139734&t=lCWT2xGGTcBu7UdC-4)

2024-07-18 09:47 UTC, tyc67 commented on packages/mesh/app/profile/_components/article-card-list.tsx
> +type StoryData = any // 請根據實際類型定義替換
import from '@/types/profile' ?

2024-07-18 09:47 UTC, tyc67 commented on packages/mesh/app/profile/_components/article-card.tsx
> +                publishDate={storyData?.published_date || Date.now()}
publish 時間應該不會是 `Date.now()` ?

2024-07-18 11:30 UTC, caesarWHLee reviewed
是說 comment 其實要留給 reviewer 去按 resolved，方便讓 reviewer 確認當初留了什麼 comment XD

2024-07-18 11:30 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/article-card.tsx
> +  // 此處在gql部分只會拿最新、且是個人檔案本人的留言。
註解建議可以把脈絡寫完整一點 (補充 publisher 沒有 comment 的情境)，publisher 的 story 不會有 comment， member 的 pick/bookmark story comment 會特別拿該個人檔案帳號的 comment

2024-07-18 11:30 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment.tsx
> +  // 之後有文章在更改成slug或id傳入做跳轉功能。
註解可以補一下 `TODO:` prefix 以便後續查找

2024-07-18 11:30 UTC, caesarWHLee commented on packages/mesh/app/profile/_components/comment.tsx
> +    if (width > 960) {
這邊和下面的 960 寬度都建議改成從 tailwindConfig 中的 breakpoint 去拿來統一 breakpoint 使用

可以擴充 `@/utils/tailwind.ts`  如下 (或是改成你習慣的其他寫法)：

```
import resolveConfig from 'tailwindcss/resolveConfig'

import tailwindConfig from '@/tailwind.config'

type Breakpoint = 'sm' | 'md' | 'lg' | 'xl' | '2xl'

function getTailwindConfig() {
  return resolveConfig(tailwindConfig)
}

function getTailwindConfigBreakpointNumber(breakpoint: Breakpoint) {
  const tailwindConfig = getTailwindConfig()
  return parseInt(tailwindConfig.theme.screens[breakpoint]
}

export { getTailwindConfig, getTailwindConfigBreakpointNumber }
```

並把 960 改成 getTailwindConfigBreakpointNumber('md') 的方式

2024-07-18 11:30 UTC, caesarWHLee commented on packages/mesh/graphql/query/publisher.gql
> +    title
重複的 title

2024-07-19 06:45 UTC, caesarWHLee approved these changes
LGTM 👍

2024-07-19 06:58 UTC, tyc67 approved these changes

2024-07-21 10:23 UTC, merged