(WIP)feat(mesh): edit profile
readr-media/Sachiel pull request #814
Opened 2024-08-01 03:00 UTC by LinHeMa

- still in progress

2024-08-13 11:07 UTC, erase2004 reviewed
1. 提問，關於 member 當中的 avatar 和 avatar_image，這兩個欄位，網站和 App 都是使用 avatar_image 的資訊來做顯示嗎？
2. action 裡面的 error 應該用 logServerSideError 來取代 console.error
3. 可能需要在 repo 跟目錄加上 vscode 設定
```JSON
{
  "eslint.workingDirectories": [
    {
      "pattern": "./packages/*/"
    }
  ]
}
```
確保 VSCode ESLint plugin 正確運作

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/_components/nav.tsx
> +    <div className="flex h-8 w-8 items-center justify-center">
`h-8 w-8` 應該合併為 `size-8`

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/_components/nav.tsx
> +      <Avatar src={avatarUrl} size="m" />
Avatar 的 size m，寬高是 28px，與原本的 26px 不同

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/tailwind.config.js
> +      boxShadow: {
這兩者會在其他地方使用到嗎？

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/apollo/index.ts
> +  ApolloLink,
type ApolloLink

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/apollo/index.ts
> +  HttpLink,
HttpLink 未被使用

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/utils/base-sixty-four-to-file.ts
> +export default async function base64ToFile(
詢問，這裡有需要用到 async 嗎？在 function 中沒看到 await 或 promise 的痕跡

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/graphql/mutation/member.gql
> +  deletePhoto(where: { id: $photoId }) {
圖片紀錄可以不用刪除，解除 member 和 photo 的關聯就好了

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/constants/page-style.ts
> +  'edit-profile',
是否為 `/edit-profile` ?

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/page.tsx
> -import { getCurrentUser } from '@/app/actions/auth'
eslint [simple-import-sort/imports](https://github.com/lydell/eslint-plugin-simple-import-sort#sort-order) error

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/layout.tsx
> +    <EditProfileProvider customId={(params['customId'] as string) || ''}>
可以用 `String(params['customId'] || '')` 來替代 `as string`

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/layout.tsx
> +import { EditProfileProvider } from '@/context/edit-profile'
eslint [simple-import-sort/imports](https://github.com/lydell/eslint-plugin-simple-import-sort#sort-order) error

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/edit-profile/_components/upload-image-error-modal.tsx
> +  const { setErrors } = useEditProfile()
沒有 setErrors 的成員

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/_components/edit-profile-header.tsx
> +      <header className="flex h-[60px] border-b bg-white px-5 sm:border-none sm:px-5 md:px-[70px] lg:px-10">
這個元件應該只需要呈現 `<header />` 以下的內容，children 之類的回歸到 layout

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/_components/member-page.tsx
> +import { usePathname, useRouter } from 'next/navigation'
import 區段有 eslint error

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/_components/visitor-page.tsx
> +import { useEditProfile } from '@/context/edit-profile'
import 區段有 eslint error

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/_components/visitor-page.tsx
> +  if (!profile) return <div>error</div>
member-page 也需要這個邏輯？

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/actions/get-profile.ts
> +    const result = await fetchGraphQL(GetMemberProfileDocument, {
這裡是不是用錯 Graphql Query Document 了？

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/edit-profile/_components/edit-profile.tsx
> +        <div className="flex max-w-[600px] w-full grow flex-col">
這裡有 ESLint error

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/_components/edit-profile-header.tsx
> +/* eslint-disable tailwindcss/no-custom-classname */
這個是多餘的

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/hooks/use-profile-state.ts
> +      const currentUser = await getCurrentUser()
currentUser 資訊應從 UserContext 中取得

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/context/edit-profile.tsx
> +    Object.keys(errors).length === 0 && formData !== originalProfileData.current
`formData !== originalProfileData.current` 這個 always true

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/context/edit-profile.tsx
> +      setErrors((prev) => ({ ...prev, avatar: '上傳的檔案大小須小於 10MB' }))
檔案超過上限時，也要載入顯示？

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/page.tsx
> +  const currentUser = await getCurrentUser()
currentUser 資訊應從 UserContext 中取得

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/edit-profile/_components/avatar-edit-menu.tsx
> +/* eslint-disable tailwindcss/no-custom-classname */
這個是多餘的

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/edit-profile/_components/edit-profile.tsx
> +/* eslint-disable tailwindcss/no-custom-classname */
這個是多餘的

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/context/edit-profile.tsx
> +      }))
應該同步更新資訊到 UserContext

2024-08-13 11:07 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/edit-profile/page.tsx
> +      avatar_image={memberData?.avatar_image}
這個元件其實只有 `avatar_image` 有被使用到

2024-08-14 05:14 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/page.tsx
> +  const currentUser = await getCurrentUser()
這邊是 server side 可以直接拿 cache 的 user 資料

2024-08-14 06:57 UTC, caesarWHLee requested changes
幾點建議：
1. 跑一下 `yarn lint` 看一下有哪些 lint error
2. 將 `EditProfileContext` 的 user state 併到 userContext，統一管理 user 資料
3. 合併 `member-page.tsx` 和 `visitor-page.tsx` 合併
    - 透過 props 取得 isVisitor 和被 visit 的 member profile 資料
    - 使用 isVisitor 來控制原本兩個 page 不同的

2024-08-14 06:57 UTC, caesarWHLee commented on packages/mesh/context/edit-profile.tsx
> +    if (formData.intro.length > INTRO_LIMITATION)
目前的字數限制好像過於嚴苛？ 以英文來說隨便一個段落就會超過，看要不要放寬一點

p.s. 如果是已知狀況可忽略
![圖片](https://github.com/user-attachments/assets/d102c74c-c2a7-4b1f-ad63-165a63da658c)

2024-08-14 06:57 UTC, caesarWHLee commented on packages/mesh/app/profile/member/[customId]/edit-profile/layout.tsx
雖然不是在這，`/edit-profile` 頁面需要加到 middleware 中，未登入使用者會被導到 `/login`

2024-08-14 06:57 UTC, caesarWHLee commented on packages/mesh/app/actions/edit-profile.ts
> +        const result = await uploadGraphQL(CreatePhotoDocument, {
目前測試會遇到上傳失敗的問題，測試資料、log 如下

圖片： https://imgur.com/a/HmdmjAd
log: 
```
[0] update avatar failed ReferenceError: File is not defined
[0]     at base64ToFile (webpack-internal:///(action-browser)/./utils/base-sixty-four-to-file.ts:18:5)
[0]     at updateProfile (webpack-internal:///(action-browser)/./app/actions/edit-profile.ts:25:110)
[0]     at endpoint (webpack-internal:///(action-browser)/./node_modules/next/dist/build/webpack/loaders/next-flight-action-entry-loader.js?actions=%5B%5B%22%2FUsers%2Fcaesar%2FDesktop%2Fprojects%2FSachiel%2Fpackages%2Fmesh%2Fapp%2Factions%2Fedit-profile.ts%22%2C%5B%22updateProfile%22%2C%22deletePhoto%22%5D%5D%2C%5B%22%2FUsers%2Fcaesar%2FDesktop%2Fprojects%2FSachiel%2Fpackages%2Fmesh%2Fapp%2Factions%2Fget-profile.ts%22%2C%5B%22getVisitorProfile%22%2C%22getMemberProfile%22%5D%5D%5D&__client_imported__=true!:11:17)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async /Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:418
[0]     at async rS (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
[0]     at async r2 (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1251)
[0]     at async doRender (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/base-server.js:1438:30)
[0]     at async cacheEntry.responseCache.get.routeKind (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/base-server.js:1587:40)
[0]     at async DevServer.renderToResponseWithComponentsImpl (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/base-server.js:1507:28)
[0]     at async DevServer.renderPageComponent (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/base-server.js:1924:24)
[0]     at async DevServer.renderToResponseImpl (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/base-server.js:1962:32)
[0]     at async DevServer.pipeImpl (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/base-server.js:920:25)
[0]     at async NextNodeServer.handleCatchallRenderRequest (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/next-server.js:272:17)
[0]     at async DevServer.handleRequestImpl (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/base-server.js:816:17)
[0]     at async /Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/dev/next-dev-server.js:339:20
[0]     at async Span.traceAsyncFn (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/trace/trace.js:154:20)
[0]     at async DevServer.handleRequest (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
[0]     at async invokeRender (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/lib/router-server.js:174:21)
[0]     at async handleRequest (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/lib/router-server.js:353:24)
[0]     at async requestHandlerImpl (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/lib/router-server.js:377:13)
[0]     at async Server.requestListener (/Users/caesar/Desktop/projects/Sachiel/packages/mesh/node_modules/next/dist/server/lib/start-server.js:141:13)
```

2024-08-14 06:57 UTC, caesarWHLee commented on packages/mesh/utils/fetch-graphql.ts
> +export async function uploadGraphQL<
改成，`mutateGraphQL` 好像比較貼切，要整齊的話可以把上面的 `fetchGraphql` 改成 `queryGraphQl`

2024-08-14 06:57 UTC, caesarWHLee commented on packages/mesh/context/edit-profile.tsx
> +  useEffect(initializeProfileData, [profile.memberCustomId])
需要補上 dependencies (如不保留可忽略)
```React Hook useEffect has missing dependencies: 'profile.avatar', 'profile.intro', and 'profile.name'. Either include them or remove the dependency array.eslint[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)```

2024-08-14 06:57 UTC, caesarWHLee commented on packages/mesh/hooks/use-profile-state.ts
> +  }, [profile.memberCustomId])
需要補上 dependencies (如不保留可忽略)
```
React Hook useEffect has missing dependencies: 'profileConfig.memberId' and 'profileConfig.takesCount'. Either include them or remove the dependency array.eslint[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)
```

2024-08-14 07:17 UTC, caesarWHLee commented
> 幾點建議：
> 
>     1. 跑一下 `yarn lint` 看一下有哪些 lint error
> 
>     2. 將 `EditProfileContext` 的 user state 併到 userContext，統一管理 user 資料
> 
>     3. 合併 `member-page.tsx` 和 `visitor-page.tsx` 合併
>        
>        * 透過 props 取得 isVisitor 和被 visit 的 member profile 資料
>        * 使用 isVisitor 來控制原本兩個 page 不同的

第 2 點我剛沒想清楚，可以編輯的部分應該還是要有 state 去存，其他的 user state 就交給 `userContext`去管理，編輯成功後記得再把新的欄位更新回 `userContext`

2024-08-15 03:44 UTC, LinHeMa commented on packages/mesh/app/profile/member/[customId]/edit-profile/layout.tsx
目前已解決，但是現在是否只有檢查有沒有token，尚未檢查token是否過期？

2024-08-15 05:58 UTC, erase2004 commented
https://akoskm.com/file-upload-with-nextjs-14-and-server-actions
檔案上傳經過 server action 的方式不用手動處理 base64 轉換的樣子，可以藉由 form 的 action 搭配 server action，來直接上傳

2024-08-20 07:38 UTC, LinHeMa commented on packages/mesh/context/edit-profile.tsx
> +    if (formData.intro.length > INTRO_LIMITATION)
目前這邊跟UI討論是決定維持🫡

2024-08-20 07:39 UTC, LinHeMa commented
> https://akoskm.com/file-upload-with-nextjs-14-and-server-actions
檔案上傳經過 server action 的方式不用手動處理 base64 轉換的樣子，可以藉由 form 的 action 搭配 server action，來直接上傳

目前已經更改為透過`ref`取得form，再透過`new FromData(...)`方法轉換，不過`avatar`目前取得方式仍舊有問題，目前先以此種做法替代。

2024-08-20 10:47 UTC, erase2004 commented on .husky/pre-commit
> +# This loads nvm.sh and sets the correct PATH before running hook
環境設定放在這裡不合適，應該放在 postinstall script 之類

2024-08-20 10:47 UTC, erase2004 commented on packages/mesh/middleware.ts
> +    /^\/profile\/member\/[^/]+\/edit-profile$/,
`/^\/profile(\/.*)?$/` 通過的，`/^\/profile(\/.*)?$/` 這個也會通過，所以是多餘的

2024-08-20 10:47 UTC, erase2004 commented on packages/mesh/hooks/use-profile-state.ts
> +        // is is visitor get all the data
`if is` ?

2024-08-20 10:47 UTC, erase2004 commented on packages/mesh/hooks/use-form.ts
> +export const useForm = <T extends Record<string, V>, V>(
V 是多餘的，`T extends Record<string, unknown>` 就夠用了

2024-08-20 10:47 UTC, erase2004 commented on packages/mesh/hooks/use-form.ts
> +  const updateField = useCallback((field: keyof T, value: T[keyof T]) => {
這應該沒使用 useCallback 的必要

2024-08-20 10:47 UTC, erase2004 commented on packages/mesh/context/edit-profile.tsx
>      const reader = new FileReader()
提問：檔案大小超過的情況下，還是要讀進來顯示？

2024-08-20 10:47 UTC, erase2004 commented on packages/mesh/app/profile/member/[customId]/edit-profile/page.tsx
> +  return <EditProfile avatar_image={memberData?.avatar_image} />
EditProfile 只用到 `memberData.avatar_image.id` 的資訊，建議用別的 GraphQL query 的內容，減少不必要的資料和效能浪費

2024-08-20 10:47 UTC, erase2004 commented on packages/mesh/app/actions/edit-profile.ts
> +    try {
提問：
1. 圖片更新失敗情況下，其他資料還要繼續寫入？
2. 在 `formData.get('avatar')` 為 null 的情況下，應該可以直接跳過圖片相關的處理？

2024-08-21 01:41 UTC, LinHeMa commented on packages/mesh/hooks/use-profile-state.ts
> +        // is is visitor get all the data
在86abae19處理

2024-08-21 01:42 UTC, LinHeMa commented on packages/mesh/middleware.ts
> +    /^\/profile\/member\/[^/]+\/edit-profile$/,
fb737a50

2024-08-21 02:58 UTC, LinHeMa commented on packages/mesh/app/profile/member/[customId]/edit-profile/page.tsx
> +  return <EditProfile avatar_image={memberData?.avatar_image} />
bce034d30335

2024-08-21 02:58 UTC, LinHeMa commented on packages/mesh/context/edit-profile.tsx
>      const reader = new FileReader()
bce034d30335

2024-08-21 02:59 UTC, LinHeMa commented on packages/mesh/app/actions/edit-profile.ts
> +    try {
之前未注意，已在bce034d30335處理

2024-08-21 03:00 UTC, LinHeMa commented on packages/mesh/hooks/use-form.ts
> +  const updateField = useCallback((field: keyof T, value: T[keyof T]) => {
7472b58ba811

2024-08-21 03:00 UTC, LinHeMa commented on packages/mesh/hooks/use-form.ts
> +export const useForm = <T extends Record<string, V>, V>(
7472b58ba811

2024-08-21 03:00 UTC, LinHeMa commented on packages/mesh/app/actions/edit-profile.ts
> +        const result = await uploadGraphQL(CreatePhotoDocument, {
目前已處理，圖片上傳流程有更新。

2024-08-21 05:54 UTC, erase2004 reviewed
https://github.com/readr-media/Sachiel/pull/814#discussion_r1722853602
這個似乎還沒處理？

2024-08-21 06:48 UTC, LinHeMa commented on packages/mesh/middleware.ts
> +    /^\/profile\/member\/[^/]+\/edit-profile$/,
這個部分刪除了` /^\/profile\/member\/[^/]+\/edit-profile$/` 讓只要 `/profile` 的所有子頁面都需要有登入資訊。
編輯頁面的部分另外用`isUser`做處理

2024-08-21 07:23 UTC, LinHeMa commented
https://github.com/readr-media/Sachiel/pull/814#discussion_r1722853602 在[b73ae01](https://github.com/readr-media/Sachiel/pull/814/commits/b73ae012fbbda2fd30bda25ddb96c123fc27c91d)做處理，編輯頁面做阻擋

2024-08-21 07:55 UTC, erase2004 reviewed
https://github.com/readr-media/Sachiel/pull/814#pullrequestreview-2249782637
Again

2024-08-21 08:52 UTC, LinHeMa commented on .husky/pre-commit
> +# This loads nvm.sh and sets the correct PATH before running hook
[5b2de80](https://github.com/readr-media/Sachiel/pull/814/commits/5b2de80f38f98aec4d621f3ba91ecb861663aea9)
先刪除

2024-08-21 09:13 UTC, erase2004 approved these changes
LGTM ✔️

2024-08-21 11:07 UTC, caesarWHLee approved these changes

2024-08-22 01:37 UTC, merged