feat(mesh): social page client-side rendering
readr-media/Sachiel pull request #827
Opened 2024-08-14 03:22 UTC by tyc67

## Notable Changes

- converted social page rendering from server-side to client-side
- refactored data fetching and transformation logic into `actions`
- update user state with `useUser()` context
- cached initial render data in localstorage

2024-08-14 04:37 UTC, erase2004 commented on packages/mesh/utils/log.ts
> +'use server'
意思不太一樣，`use server` 是給 server action 使用的

2024-08-14 04:37 UTC, erase2004 commented on packages/mesh/app/social/_components/follow-suggestion-feed.tsx
> +  currentUserId: string
加上 currentUserId 的用途？

2024-08-14 04:37 UTC, erase2004 commented on packages/mesh/app/social/_components/follow-suggestion-widget.tsx
> +  currentUserId: string
加上 currentUserId 的用途？

2024-08-14 05:17 UTC, tyc67 commented on packages/mesh/app/social/_components/follow-suggestion-widget.tsx
> +  currentUserId: string
解conflicts時沒改好, 修改於 [6796037](https://github.com/readr-media/Sachiel/pull/827/commits/6796037183fa2f5c3cce7aad1b9e258c7163086f)

2024-08-14 05:17 UTC, tyc67 commented on packages/mesh/app/social/_components/follow-suggestion-feed.tsx
> +  currentUserId: string
解conflicts時沒改好, 修改於 [6796037](https://github.com/readr-media/Sachiel/pull/827/commits/6796037183fa2f5c3cce7aad1b9e258c7163086f)

2024-08-14 05:20 UTC, tyc67 commented on packages/mesh/utils/log.ts
> +'use server'
因改成 client-side fetching 時會噴錯👇 , 所以改為 `use server`

<img width="360" alt="Screenshot 2024-08-14 at 1 18 34 PM" src="https://github.com/user-attachments/assets/9ad0c9a3-4289-4f95-8992-c12c0a7c9402">

2024-08-15 05:41 UTC, erase2004 commented on packages/mesh/utils/log.ts
> +'use server'
因為 page 變成 client component，但 `utils/log` 使用到 `next/header`，導致他必須在 server component 的環境下才能正常運作，這當中，`utils/most-followed-member` 使用到 fetchStatic，裡面有 import logServerSideError 的方法，這條路徑上需要在 server component 底下才能正常運作，將 most-followed-member 加上 'use server' 轉為 server action 後，問題就解決了

2024-08-15 07:09 UTC, tyc67 commented on packages/mesh/utils/log.ts
> +'use server'
感謝詳細解惑說明，之前找錯錯誤點了，修改於 [58441df](https://github.com/readr-media/Sachiel/pull/827/commits/58441df3badab20119b5af0a33eae023a8a77575)

2024-08-15 07:16 UTC, caesarWHLee requested changes
推薦追蹤顯示數量超過 5 筆
![圖片](https://github.com/user-attachments/assets/2d782c7d-2b31-4421-b138-ff0e579b41fe)

2024-08-15 07:16 UTC, caesarWHLee commented on packages/mesh/utils/most-followed-member.ts
目前 fetchMethod 的設計都是在 server side 使用，這個 util 應該也要搬到 actions 下改成 server actions 呼叫

2024-08-15 07:16 UTC, caesarWHLee commented on packages/mesh/app/social/[id]/page.tsx
> +    }
頁面邏輯搬回 `social/page.tsx` 後，這個判斷頁可以拿掉了

2024-08-15 07:16 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
現在的版本應該就不需要 social/[id] 這個 dynamic 的 route 來處理使用者 id，可以把該頁邏輯放回到這裡了，就不需要再 redirect 一次

2024-08-15 07:16 UTC, caesarWHLee commented on packages/mesh/app/social/[id]/page.tsx
> +      if (cacheAge < MINUTE) {
`localStorage` 的 cache 應該不會只 cache 一分鐘，可以找 HC 確認他想像的 cache 時間，再請 PM 紀錄

2024-08-15 07:16 UTC, caesarWHLee commented on packages/mesh/app/social/[id]/page.tsx
> +      )
fetch 完的資料可以用來更新 userContext 的資料 (比照 userContext 既有格式)，確保 user 資料在頁面切換的時候被更新

2024-08-15 08:09 UTC, tyc67 commented on packages/mesh/app/social/[id]/page.tsx
> +      )
這裡沒有 mutation 也要 `setUser` 嗎 ?

2024-08-15 08:16 UTC, tyc67 commented on packages/mesh/utils/most-followed-member.ts
修改於 [58441df](https://github.com/readr-media/Sachiel/pull/827/commits/58441df3badab20119b5af0a33eae023a8a77575)

2024-08-15 08:16 UTC, tyc67 commented on packages/mesh/app/social/[id]/page.tsx
> +    }
修改於 [5d1977e](https://github.com/readr-media/Sachiel/pull/827/commits/5d1977e3c90e83eae471a5e4922d2db345152fa5)

2024-08-15 08:16 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
修改於 [5d1977e](https://github.com/readr-media/Sachiel/pull/827/commits/5d1977e3c90e83eae471a5e4922d2db345152fa5)

2024-08-15 08:17 UTC, tyc67 commented on packages/mesh/app/social/[id]/page.tsx
> +      if (cacheAge < MINUTE) {
加 TODO 於 [5d1977e](https://github.com/readr-media/Sachiel/pull/827/commits/5d1977e3c90e83eae471a5e4922d2db345152fa5)

2024-08-15 08:34 UTC, caesarWHLee commented on packages/mesh/app/social/[id]/page.tsx
> +      )
userContext 會在第一次打開任何頁面的時候拿 user 資料，之後就不會再更新，這邊有拿到 userContext 相關的資料的狀況下可以更新 user

2024-08-15 09:32 UTC, tyc67 commented on packages/mesh/app/social/[id]/page.tsx
> +      )
我的理解應該是 `mutation` success 的時候更新? query 和 mutation 都對 context setState 不是有可能造成 context state 會不同的情況嗎？

2024-08-16 03:10 UTC, caesarWHLee commented on packages/mesh/app/social/[id]/page.tsx
> +      )
這個頁面不是沒有 mutation 嗎？ 為何會有 context state 不同的狀況？ 而且如果有不同的狀況就更該以最新的 query 結果顯示才是，那表示有 mutation 失敗

2024-08-16 07:48 UTC, erase2004 approved these changes
LGTM :white_check_mark:

2024-08-16 08:14 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +  }, [user, router])
```React Hook useEffect has a missing dependency: 'mostFollowedMembers'. Either include it or remove the dependency array.eslint[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)```

2024-08-16 08:14 UTC, caesarWHLee commented on packages/mesh/app/social/page.tsx
> +  if (!socialData) return <Spinner />
<Spinner/> 的 wrapper 要加上 `grow`
![圖片](https://github.com/user-attachments/assets/3de37a10-8230-4e09-bde2-dd869dd8fbe8)

2024-08-16 10:26 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  if (!socialData) return <Spinner />
修改於 [ba3bfe8](https://github.com/readr-media/Sachiel/pull/827/commits/ba3bfe857f2fc18ed240081ce1af983f81b8a966)

2024-08-16 10:27 UTC, tyc67 commented on packages/mesh/app/social/page.tsx
> +  }, [user, router])
將 `mostFollowedMembers` 邏輯改至 `< NoFollowings />` 處理，修改於 [ba3bfe8](https://github.com/readr-media/Sachiel/pull/827/commits/ba3bfe857f2fc18ed240081ce1af983f81b8a966)

2024-08-16 11:25 UTC, caesarWHLee approved these changes
LGTM

2024-08-19 06:27 UTC, merged