feat: add homepage
readr-media/Sachiel pull request #837
Opened 2024-09-08 21:05 UTC by nihclil

## Changes
* 加入 zod
* 首頁內容

## TODO
* 追蹤按鈕樣式修改，追蹤功能改為共用 function

2024-09-11 08:17 UTC, tyc67 commented on packages/mesh/app/_component/category-story/main-card.tsx
> +            <h3 className="title-2 text-primay-700 mb-2 sm:mb-3">
primary

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/category-story/main-card.tsx
> +            <h3 className="title-2 text-primay-700 mb-2 sm:mb-3">
primary

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/daily-highlight/main-group.tsx
> +              <h3 className="title-2 text-primay-700 mb-2 sm:mb-3">
primary

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/daily-highlight/section.tsx
> +        <h2 className="list-title text-primary-700">今日焦點</h2>
width > 960px 為 title-1 ?

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/most-picked-story.tsx
> +export default async function ReadrStory({ followingMembers }: Props) {
MostPickedStory ?

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/featured-card.tsx
> +            <StoryPickButton storyId={story.id} />
button 顏色與 [figma](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=8820-367607&t=W0MoqmB10fiPdGFA-4) 不同?

<img width="386" alt="Screenshot 2024-09-11 at 4 29 16 PM" src="https://github.com/user-attachments/assets/5e79e7cf-68aa-445f-9c75-825b9648513b">

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/category-story/story-section.tsx
> +          size={{ width: 36, height: 36 }}
[24x24](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=8820-367624&t=W0MoqmB10fiPdGFA-4) ?

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/category-story/nav-list.tsx
> +      {data && (
Ln65 對 data 判斷, 應該不用再判斷一次?

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/top-collector/section.tsx
> +    <section className="px-5 pt-8 md:px-[70px] lg:bg-[#F6F6F6] lg:px-10 lg:pb-10 xl:pb-8 xl:pt-[34px] xxl:pb-10 xxl:pt-8">
須確認設計是否新增 design system color

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/top-collector/section.tsx
> +      <p className="list-title lg:title-1 mb-1 text-primary-700 lg:mb-4 lg:text-primary-500 xl:mb-[14px]">
mb-3 ?

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/top-collector/card.tsx
> +          rank === 1 ? 'bg-brand' : 'bg-[#DADCE3]'
須確認設計是否新增 design system color

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/top-collector/card.tsx
> +          size="lg-small"
應該是 `size=md` 由外層調整寬度 ?

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/most-liked-comments/section.tsx
> +      <h2 className="list-title lg:title-1 mb-3 text-primary-700 lg:mb-4 xl:mb-[22px] xxl:mb-4">
mb-4 ? [figma](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=8820-367810&t=W0MoqmB10fiPdGFA-4)

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/_component/most-liked-comments/card.tsx
> +        <hr className="bg-rgba(0,9,40,0.1)] my-3 h-[0.5px]" />
須確認設計是否新增 design system color

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/page.tsx
> +      memberData.member?.followingMembers?.map((member) => member.id ?? '')
若為登入狀態應可用 `user?.followingMemberIds`

2024-09-11 10:38 UTC, tyc67 commented on packages/mesh/app/page.tsx
> +  let followingMembers: Set<string> = new Set()
若使用者為未登入, 會沒有 `followingMembers data ` , 須確認這樣使用情境 StoryInfo 要顯示什麼?

2024-09-12 00:29 UTC, tyc67 commented on packages/mesh/types/homepage.ts
導入 zod 的話, 也許用 z.infer 管理比較好

2024-09-12 10:10 UTC, nihclil commented on packages/mesh/types/homepage.ts
意思是可以把這個檔案刪除，以 zod schema 為主嗎 🥸

2024-09-12 11:44 UTC, caesarWHLee requested changes
`app/_component` > `app/_components`

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/page.tsx
> +  }
這邊上面全部的 code 都可以被拿掉，因為 `getCurrentUser` 目前已經可以直接拿到 followingMembers 並處理成 user?.followingMemberIds，底層的 component 需要這個欄位的時候有兩種拿法：

1. server component: 直接在該 component 層 call `getCurrentUser` 透過 next.js server component cache 機制來拿到 `user?.followingMemberIds`
2. client component: 使用 `useUser` 來取得 user 資料

這樣修改的話就不會有 props drilling 的狀況

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/_component/daily-highlight/section.tsx
> +  const noGroupStory = noGroupData.slice(0, 6)
Nitpick: `groupStories` and `noGroupStories`

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/_component/daily-highlight/section.tsx
> +  if (!groupData || !noGroupData) return null
Double Check: 正常邏輯是有多少資料顯示多少，這邊只要有一部分資料沒拿到就整段去掉是 PM 定義的行為嗎，是的話可以忽略這個 comment，不是的話建議下方的 `<MainGroup/>` 和 `<StoryCard/>s` 依照資料有無來顯示/隱藏，保險起見可以跟 PM 確定一下這邊的顯示邏輯

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/_component/featured-card.tsx
> +  const displayPicks = getDisplayPicks(story.picks, followingMembers)
`followingMembers` 從 `getCurrentUser` 拿取

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/_component/daily-highlight/main-group.tsx
> +  const displayPicks = getDisplayPicks(story.picks, followingMembers)
`followingMembers` 從 `getCurrentUser` 拿取

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/_component/category-story/nav-list.tsx
> +  const [activeTitle, setActiveTitle] = useState(categories?.[0].title ?? '')
可以考慮把 `activeCategory`  存實際的 `category` 而不是 `slug`，這樣就不需要另外存 `activeTitle` 這個 state，直接 `activeCategory.title` 取得就好，也比較符合 `category` 的字面意義

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/_component/category-story/nav-list.tsx
> +  if (!data) return null
不建議 data 為 falsy 就直接回傳 null，在 A category 拿不到資料的狀況下應該保留 category-selector 讓使用者可以切換其他的 category 來看內容，建議可以請設計補充錯誤狀態的提示，引導使用者看其他的 category 資料，有點類似這邊的[效果](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=7230-148479&t=NK5pj79enHxc2ST7-4)，但是只有針對這個區塊的空狀態顯示

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/_component/category-story/main-card.tsx
> +  const displayPicks = getDisplayPicks(story.picks, followingMembers)
`followingMembers` 從 `getCurrentUser` 拿取

2024-09-12 11:44 UTC, caesarWHLee commented on packages/mesh/app/_component/story-card.tsx
> +  const displayPicks = getDisplayPicks(story.picks, followingMembers)
`followingMembers` 從 `getCurrentUser` 拿取

2024-09-13 00:49 UTC, tyc67 commented on packages/mesh/types/homepage.ts
是的。

2024-09-19 07:05 UTC, nihclil commented on packages/mesh/app/_component/most-liked-comments/section.tsx
> +      <h2 className="list-title lg:title-1 mb-3 text-primary-700 lg:mb-4 xl:mb-[22px] xxl:mb-4">
感謝提醒，修改於 https://github.com/readr-media/Sachiel/pull/837/commits/a08bd1fc1bd4a451bf4659466153bcbe7626ff9d

2024-09-19 07:09 UTC, nihclil commented on packages/mesh/app/_component/category-story/nav-list.tsx
> +  if (!data) return null
感謝提醒！更正為 data falsy 時顯示[設計](https://www.figma.com/design/wqODc69zqgbu7TZFtQAmnN/2024_READr-Mesh_Web?node-id=11730-824709)，修改在 https://github.com/readr-media/Sachiel/pull/837/commits/a2f22f267356442e101a715a06482e93b48598c0

2024-09-19 07:10 UTC, nihclil commented on packages/mesh/app/_component/category-story/nav-list.tsx
> +  const [activeTitle, setActiveTitle] = useState(categories?.[0].title ?? '')
感謝提醒，修改於 https://github.com/readr-media/Sachiel/pull/837/commits/91e9fbf549e6bd44c5ed9356baafb701ce4ea836

2024-09-19 07:12 UTC, nihclil commented on packages/mesh/app/_component/daily-highlight/section.tsx
> +  if (!groupData || !noGroupData) return null
感謝提醒，修正為依照資料有無來顯示/隱藏，https://github.com/readr-media/Sachiel/pull/837/commits/07d602ef3496ea72cee9f9cd1789dd6cf237b864

2024-09-19 07:12 UTC, nihclil commented on packages/mesh/app/_component/daily-highlight/section.tsx
> +  const noGroupStory = noGroupData.slice(0, 6)
感謝提醒，修正於 https://github.com/readr-media/Sachiel/pull/837/commits/5dca6cd8f197d35449949a94977bd9d9c315a0fc

2024-09-19 07:15 UTC, nihclil commented on packages/mesh/types/homepage.ts
這部分想等見面時討論管理 types 方式 🙇‍♀️，之後要修正會再另發 PR！

2024-09-19 07:16 UTC, nihclil commented
> `app/_component` > `app/_components`

感謝～修改於 https://github.com/readr-media/Sachiel/pull/837/commits/81acdfd254584cd1ff05226e654a722feaf9df87

2024-09-19 07:18 UTC, nihclil commented on packages/mesh/app/_component/category-story/main-card.tsx
> +            <h3 className="title-2 text-primay-700 mb-2 sm:mb-3">
感謝提醒～修改於 https://github.com/readr-media/Sachiel/pull/837/commits/5bdfcdfbbeb8645d04eb409c03593a59e301f5f4

2024-09-19 07:19 UTC, nihclil commented on packages/mesh/app/_component/daily-highlight/main-group.tsx
> +              <h3 className="title-2 text-primay-700 mb-2 sm:mb-3">
感謝提醒～修改於 https://github.com/readr-media/Sachiel/commit/5bdfcdfbbeb8645d04eb409c03593a59e301f5f4

2024-09-19 07:19 UTC, nihclil commented on packages/mesh/app/_component/daily-highlight/section.tsx
> +        <h2 className="list-title text-primary-700">今日焦點</h2>
感謝提醒～修改於 https://github.com/readr-media/Sachiel/commit/5bdfcdfbbeb8645d04eb409c03593a59e301f5f4

2024-09-19 07:20 UTC, nihclil commented on packages/mesh/app/_component/most-picked-story.tsx
> +export default async function ReadrStory({ followingMembers }: Props) {
修改於 https://github.com/readr-media/Sachiel/pull/837/commits/8fadb17bf10ce8f2ee268dffdab78322f316c188，感謝！

2024-09-19 07:21 UTC, nihclil commented on packages/mesh/app/_component/featured-card.tsx
> +            <StoryPickButton storyId={story.id} />
感謝提醒，修改於 https://github.com/readr-media/Sachiel/pull/837/commits/536708322b60e5185036de5b367130477b101ec6

2024-09-19 07:23 UTC, nihclil commented on packages/mesh/app/_component/category-story/story-section.tsx
> +          size={{ width: 36, height: 36 }}
感謝～也調整了來源 svg 的 size，https://github.com/readr-media/Sachiel/pull/837/commits/e574ca657960dacf47c166bed22b530be96aeedf https://github.com/readr-media/Sachiel/pull/837/commits/12347a9a992d7c4540c41bb41f7653d26a909692

2024-09-19 07:23 UTC, nihclil commented on packages/mesh/app/_component/category-story/nav-list.tsx
> +      {data && (
感謝！修改於 https://github.com/readr-media/Sachiel/pull/837/commits/17d6a06fc0262fca3ac49951b08f0ee61fc04357

2024-09-19 07:25 UTC, nihclil commented on packages/mesh/app/_component/top-collector/section.tsx
> +    <section className="px-5 pt-8 md:px-[70px] lg:bg-[#F6F6F6] lg:px-10 lg:pb-10 xl:pb-8 xl:pt-[34px] xxl:pb-10 xxl:pt-8">
感謝～這部分是我沒注意到現有的 design system color，修改在 https://github.com/readr-media/Sachiel/pull/837/commits/9b9f423a8c382c4ec04ad4d7c4212a311e86c417

2024-09-19 07:29 UTC, nihclil commented on packages/mesh/app/_component/most-liked-comments/card.tsx
> +        <hr className="bg-rgba(0,9,40,0.1)] my-3 h-[0.5px]" />
設計說她有固定使用幾個 border color，討論是否統一 config 還沒有定論，可以見面討論，我先用 border-[color] 處理～～https://github.com/readr-media/Sachiel/pull/837/commits/dd454048c8bbc9b2f47e83278c9210a1301ad761

2024-09-19 07:30 UTC, nihclil commented on packages/mesh/app/_component/most-liked-comments/section.tsx
> +      <h2 className="list-title lg:title-1 mb-3 text-primary-700 lg:mb-4 xl:mb-[22px] xxl:mb-4">
感謝～修改於 https://github.com/readr-media/Sachiel/pull/837/commits/a08bd1fc1bd4a451bf4659466153bcbe7626ff9d

2024-09-19 07:30 UTC, nihclil commented on packages/mesh/app/_component/top-collector/card.tsx
> +          rank === 1 ? 'bg-brand' : 'bg-[#DADCE3]'
有修正了！在 https://github.com/readr-media/Sachiel/pull/837/commits/a08bd1fc1bd4a451bf4659466153bcbe7626ff9d

2024-09-19 07:31 UTC, nihclil commented on packages/mesh/app/_component/top-collector/section.tsx
> +      <p className="list-title lg:title-1 mb-1 text-primary-700 lg:mb-4 lg:text-primary-500 xl:mb-[14px]">
感謝～修正在 https://github.com/readr-media/Sachiel/commit/a08bd1fc1bd4a451bf4659466153bcbe7626ff9d

2024-09-19 07:32 UTC, nihclil commented on packages/mesh/app/_component/top-collector/card.tsx
> +          size="lg-small"
感謝～修改於 https://github.com/readr-media/Sachiel/pull/837/commits/c82e99b2b1455a194472163b73eea68bb2b843da

2024-09-19 07:36 UTC, nihclil commented
有關 followingMembers 的程式碼都已經移除，因為首頁登入及未登入都是顯示相同 storypicks 的資料，所以不需要 followingMemebrs 的判斷，修正於 https://github.com/readr-media/Sachiel/pull/837/commits/9bebfaaf68ec8f98ffee2c2290260ce46ca0b6c8，謝謝～
@caesarWHLee @tyc67

2024-09-23 02:28 UTC, caesarWHLee commented on packages/mesh/app/_components/category-story/story-section.tsx
> +      {stories ? (
`fetchCategoryStory` 拿到的 data 有遇過正常回傳但是是回傳空的 array，建議把此狀況考慮進去以 cover 全部 empty 狀況

2024-09-23 02:33 UTC, tyc67 commented on packages/mesh/app/_component/most-liked-comments/section.tsx
> +      <h2 className="list-title lg:title-1 mb-3 text-primary-700 lg:mb-4 xl:mb-[22px] xxl:mb-4">
應該沒有 mb-[22px] ?

2024-09-23 02:33 UTC, tyc67 commented on packages/mesh/types/homepage.ts
https://zod.dev/?id=basic-usage

2024-09-23 02:33 UTC, tyc67 commented on packages/mesh/app/_component/featured-card.tsx
> +            <StoryPickButton storyId={story.id} />
應該是由外層給訂顏色, 不會export 共用元件

2024-09-24 05:26 UTC, nihclil commented on packages/mesh/app/_component/featured-card.tsx
> +            <StoryPickButton storyId={story.id} />
修改了～在 https://github.com/readr-media/Sachiel/pull/837/commits/49e9a9d31f6da4651a2dc69fbeeeeb7887e0f5d6

2024-09-24 05:26 UTC, nihclil commented on packages/mesh/app/_component/most-liked-comments/section.tsx
> +      <h2 className="list-title lg:title-1 mb-3 text-primary-700 lg:mb-4 xl:mb-[22px] xxl:mb-4">
這個已經刪除了沒錯？！

2024-09-24 05:29 UTC, nihclil commented on packages/mesh/types/homepage.ts
改了！！在 [4fb88f6](https://github.com/readr-media/Sachiel/pull/837/commits/4fb88f65c82e195be3b370b257cb06b9ae997944)

2024-09-24 05:30 UTC, nihclil commented on packages/mesh/app/_components/category-story/story-section.tsx
> +      {stories ? (
修改了～ 在  [5e7f6d0](https://github.com/readr-media/Sachiel/pull/837/commits/5e7f6d0ae495b12359c6fb2699939cb67c331775)

2024-09-24 05:31 UTC, nihclil commented
另外有修正了使用者精選時要正確顯示精選資訊的功能，在 [ff4f17c](https://github.com/readr-media/Sachiel/pull/837/commits/ff4f17ce6022357ce18a3ad2f1354b66642507b0)

2024-09-24 06:25 UTC, caesarWHLee approved these changes
LGTM 👍 👍 👍

2024-09-24 06:47 UTC, tyc67 approved these changes

2024-09-24 06:48 UTC, merged