(WIP)feat: comment under article
readr-media/Sachiel pull request #857
Opened 2024-10-01 13:44 UTC by LinHeMa

推上來了，發現layout全改了，淚崩

2024-10-01 14:45 UTC, erase2004 requested changes
wip 階段不予 review

2024-10-03 10:14 UTC, caesarWHLee requested changes
目前全部 comment 相關的 component 都是放在 `@/components/comment/client-comment-wrapper/` 之中，有點難區別手機版 comment modal 和非手機版 story comment 之間的關係，提供一個修改的方向供參考：

comment/
- comment-modal/ : 放手機版 comment 相關 components
- story-comment/  ：放非手機版 comment 相關 components
- comment-wrapper ：放原本的 client-comment-wrapper/index.tsx，但把 `CommentBlockContent` component 放到 comment-modal/ 中

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/components/comment/client-comment-wrapper/comment-modal.tsx
> +        <div className="flex w-screen max-w-md flex-col gap-5 rounded-lg bg-white px-5 py-4">
shadow 沒有加到

box-shadow: 0px 0px 24px 0px rgba(0, 9, 40, 0.1);
box-shadow: 0px 2px 40px 0px rgba(0, 9, 40, 0.1);

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/app/story/[id]/layout.tsx
> +      <ClientModalWrapper storyData={storyData.story}>
命名不需要加上 Client，如果是參考下面的 ClientLayout 的話這裡的 Client 只是為了區別 Layout (server) 而取的名字，不是 convention，另外目前的命名看不出跟 Comment 的關聯，建議改成 CommentWrapper

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/components/comment/client-comment-wrapper/comment-modal.tsx
> +                onClick={onLeave}
以 modal 的角度應該 `onConfirm` 之類的，`onLeave` 感覺是外部的邏輯洩漏進來，建議修正

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/components/comment/client-comment-wrapper/story-comment-block-item.tsx
> +                      notMobileWidth && <DropdownMenu />}
如果 DropdownMenu 只能在 非Mobile 中顯示，可以直接在 css 中 hidden 就好，不需要用到 js 判斷寬度

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/app/story/[id]/_components/comment.tsx
> +        isOpen={state.isReporting}
[Nitpick]: isReporting 一併從 Line28 中提取

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/context/comment-context.tsx
> +      return { ...state, isReporting: false }
case `SHOW_REPORTING_MODAL`, `HIDE_REPORTING_MODAL` 沒有用到應刪除

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/context/comment-context.tsx
> +  confirmDeleteCommentModalShow: false,
控制 modal 的 flag 命名應統一格式 isModalOpen, confirmModalShow, confirmDeleteCommentModalShow, isReporting，另外 isModalOpen 命名無法知道是針對 mobileCommentModal 的控制，可以想一下更好的名字

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/components/layout-template/bottom-action-bar/index.tsx
> +    scrollTo({ top: 0 })
打開 modal 應該不需要強制把頁面滑到最上面，可以把 CommentBlockContent 改成 `Fixed` 就好

2024-10-03 10:14 UTC, caesarWHLee commented on packages/mesh/components/comment/client-comment-wrapper/comment-edit-drawer.tsx
> +    })
刪除動作應該在 confirm delete 之後？

btw nonMobile 的版本沒有 call 到 `deleteComment`

2024-10-03 10:15 UTC, caesarWHLee commented
記得更新 `story.gql` comments,commentsCount 的條件，`is_active: { equals: true }`，才不會拿到已刪除的 comment

2024-10-04 07:03 UTC, LinHeMa commented on packages/mesh/components/comment/client-comment-wrapper/comment-modal.tsx
> +        <div className="flex w-screen max-w-md flex-col gap-5 rounded-lg bg-white px-5 py-4">
在[29e43fb](https://github.com/readr-media/Sachiel/pull/857/commits/29e43fb23065e19abb4a883ffe07390eba2297f1)處裡

2024-10-04 07:13 UTC, LinHeMa commented on packages/mesh/app/story/[id]/layout.tsx
> +      <ClientModalWrapper storyData={storyData.story}>
在[50c1526](https://github.com/readr-media/Sachiel/pull/857/commits/50c15265754556a41f61ed5f5bcd036dfc19cb57)進行處理

2024-10-04 07:27 UTC, LinHeMa commented on packages/mesh/components/comment/client-comment-wrapper/comment-modal.tsx
> +                onClick={onLeave}
在[f8b2434](https://github.com/readr-media/Sachiel/pull/857/commits/f8b2434f10b99a7e9e226d061eeedb289af08e01)修改

2024-10-04 07:41 UTC, LinHeMa commented on packages/mesh/components/comment/client-comment-wrapper/story-comment-block-item.tsx
> +                      notMobileWidth && <DropdownMenu />}
原本是因為有使用到 `useOnClickOutside`現在在dropdown裡面處理[0ea7cb3](https://github.com/readr-media/Sachiel/pull/857/commits/0ea7cb36daccc4049c6e05dd598a799f56e6a911)

2024-10-04 07:46 UTC, LinHeMa commented on packages/mesh/app/story/[id]/_components/comment.tsx
> +        isOpen={state.isReporting}
在[b923d40](https://github.com/readr-media/Sachiel/pull/857/commits/b923d40a7ae9e888a717cba4941e72ea7181dd9d)處理

2024-10-04 07:47 UTC, LinHeMa commented on packages/mesh/context/comment-context.tsx
> +      return { ...state, isReporting: false }
在[60c880d](https://github.com/readr-media/Sachiel/pull/857/commits/60c880d88af2823b82c1f384683d2d47795a03a4)處理

2024-10-04 08:14 UTC, LinHeMa commented on packages/mesh/context/comment-context.tsx
> +  confirmDeleteCommentModalShow: false,
在[fc2f3cc](https://github.com/readr-media/Sachiel/pull/857/commits/fc2f3cc94a7697f626d7a6e6f918ce4ce6fdb056)進行處理

2024-10-04 08:50 UTC, LinHeMa commented on packages/mesh/components/layout-template/bottom-action-bar/index.tsx
> +    scrollTo({ top: 0 })
在[515212a](https://github.com/readr-media/Sachiel/pull/857/commits/515212ab8d275f45bf83de7f8661955c1b99325e)處理

2024-10-04 09:03 UTC, LinHeMa commented on packages/mesh/components/comment/client-comment-wrapper/comment-edit-drawer.tsx
> +    })
在[3072728](https://github.com/readr-media/Sachiel/pull/857/commits/30727286dacdbf81f3bef2544a316b8355663130)處理

2024-10-04 09:08 UTC, LinHeMa commented
`story.gql` 在[d18e578](https://github.com/readr-media/Sachiel/pull/857/commits/d18e57851c5ad35abf0893fad4f4a0c00378b155)處理

2024-10-07 08:33 UTC, caesarWHLee commented on packages/mesh/graphql/query/story.gql
>      commentsCount: commentCount(where: { state: { equals: "public" } })
commentsCount 條件比照下面 comments

2024-10-07 08:33 UTC, caesarWHLee commented on packages/mesh/graphql/query/story.gql
>      commentsCount: commentCount(where: { state: { equals: "public" } })
commentsCount 條件比照下面 comments

2024-10-07 08:33 UTC, caesarWHLee commented on packages/mesh/app/story/[id]/layout.tsx
> +      <MobileCommentModalWrapper storyData={storyData.story}>
想了一下，MobileCommentModalWrapper 其實是 CommentProvider + MobileCommentModalContent，命名為 Mobile 開頭容易誤會 非Mobile 不會用到，但命名為 CommentWrapper 好像又把 MobileCommentModalContent 的細節給隱藏了，不如直接把 MobileCommentModalWrapper 的內容放到 layout.tsx 中就好，不需要多一個檔案來裝

```
<MobileCommentModalWrapper storyData={storyData.story}>

</MobileCommentModalWrapper>
```

可以考慮改成下面這樣

```
<CommentProvider initialComments={storyData?.comments || []}>
  <MobileCommentModalContent storyData={storyData} />
  <ClientLayout story={storyData.story}>{children}</ClientLayout>
</CommentProvider>
```

看你覺得如何？

2024-10-07 11:28 UTC, erase2004 reviewed
提問：河馬使用的元件 import/export 方式是

```JavaScript
// nav-item.tsx
export const NavItem = () => {}
```

```JavaScript
// nav-list.tsx
import { NavItem } from './nav-item'
```

其他人是

```JavaScript
// nav-item.tsx
const NavItem = () => {}
export default NavItem
```
或
```JavaScript
// nav-item.tsx
export default function NavItem() {}
```

```JavaScript
// nav-list.tsx
import NavItem from './nav-item'
```

關於這部份，有沒有要統一一下寫法？ cc @caesarWHLee

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/components/layout-template/bottom-action-bar/index.tsx
> +    <nav
使用者點擊底下的贊助或精選按鈕後，會顯示留言的視窗，請問這是符合預期的行為？

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/components/comment/story-comment/dropdown-menu.tsx
> +      dispatch({
Ln. 36 和 Ln. 42 可以合併，提到 Ln. 34 前面？

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/components/comment/story-comment/comment-block.tsx
> +  const backgroundColorFadeTime = 5000
這個設定應該用大寫命名，且放到元件外

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/components/comment/story-comment/comment-block-item.tsx
> +      dispatch({
編輯其他人的 comment 是允許的？

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/components/comment/mobile-comment-section/mobile-comment-modal-content.tsx
> +            {!!sortAndFilterComments(commentList).length && (
`sortAndFilterComments(commentList)` 的結果應該用變數儲存起來，避免重複計算浪費

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/components/comment/mobile-comment-section/mobile-comment-edit-drawer.tsx
> +      dispatch({
Ln. 22 和 Ln. 33 可以合併，放到 Ln. 21 之前？

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/components/comment/mobile-comment-section/mobile-comment-edit-drawer.tsx
handleDeleteComment, handleEditComment 和 handleReport 的處理與 DropdownMenu 中相同，可以考慮把兩邊做整併

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/app/story/[id]/_components/stroy-comments-navigator.tsx
這個似乎沒被使用？

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/app/actions/comment.ts
> +      return newCommentId
提問：如果同時多位使用者對同一篇文章送出 comment 的情況下，如何確定 `newCommentId` 就可以對應到使用者所送出的 comment?

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/context/comment-context.tsx
> +type EditDrawerShowType = '' | 'self' | 'other'
EditDrawerShowType 和 EditDrawerBlockType 建議使用 enum，並且在使用到的地方，也用 enum 替代

2024-10-07 11:28 UTC, erase2004 commented on packages/mesh/context/comment-context.tsx
> +  | { type: 'HIDE_EDIT_DRAWER' }
`HIDE_EDIT_DRAWER` 這個目前沒用到的樣子

2024-10-07 12:03 UTC, caesarWHLee commented
> 提問：河馬使用的元件 import/export 方式是
> 
> ```js
> // nav-item.tsx
> export const NavItem = () => {}
> ```
> 
> ```js
> // nav-list.tsx
> import { NavItem } from './nav-item'
> ```
> 
> 其他人是
> 
> ```js
> // nav-item.tsx
> const NavItem = () => {}
> export default NavItem
> ```
> 
> 或
> 
> ```js
> // nav-item.tsx
> export default function NavItem() {}
> ```
> 
> ```js
> // nav-list.tsx
> import NavItem from './nav-item'
> ```
> 
> 關於這部份，有沒有要統一一下寫法？ cc @caesarWHLee

目前是沒有訂這個 convention，不過 @LinHeMa 可以考慮統一用以下寫法就好，畢竟 `@/comment/mobile-comment-section` 和 `@/comment/story-comment` 中的 component 其實都只有 export 一個而已，用 default export 比較適合
> ```js
> // nav-item.tsx
> const NavItem = () => {}
> export default NavItem
> ```

2024-10-08 02:30 UTC, LinHeMa commented on packages/mesh/graphql/query/story.gql
>      commentsCount: commentCount(where: { state: { equals: "public" } })
在[ff89e52](https://github.com/readr-media/Sachiel/pull/857/commits/ff89e5287e615f85eb44a87c96c0ffc21ed04e41)處理

2024-10-08 02:30 UTC, LinHeMa commented on packages/mesh/graphql/query/story.gql
>      commentsCount: commentCount(where: { state: { equals: "public" } })
在[ff89e52](https://github.com/readr-media/Sachiel/pull/857/commits/ff89e5287e615f85eb44a87c96c0ffc21ed04e41)處理

2024-10-08 02:58 UTC, LinHeMa commented on packages/mesh/app/story/[id]/layout.tsx
> +      <MobileCommentModalWrapper storyData={storyData.story}>
在[3946af9](https://github.com/readr-media/Sachiel/pull/857/commits/3946af94f5af72fc0d41b312ae2f4f37e2cc970f)進行處理

2024-10-08 03:08 UTC, LinHeMa commented on packages/mesh/components/layout-template/bottom-action-bar/index.tsx
> +    <nav
在[25f2284](https://github.com/readr-media/Sachiel/pull/857/commits/25f228434929723c763faf1ca8c743411d7c69e7)進行處理

2024-10-08 06:26 UTC, LinHeMa commented on packages/mesh/components/comment/story-comment/dropdown-menu.tsx
> +      dispatch({
在[fafa675](https://github.com/readr-media/Sachiel/pull/857/commits/fafa67504b641e91b7553a05a6aad7caa53bb162)進行處理

2024-10-08 06:27 UTC, LinHeMa commented on packages/mesh/components/comment/story-comment/comment-block.tsx
> +  const backgroundColorFadeTime = 5000
在[012c7a5](https://github.com/readr-media/Sachiel/pull/857/commits/012c7a5b5c2db5e70b7921a39426358049c3f66f)進行處理

2024-10-08 06:28 UTC, LinHeMa commented on packages/mesh/components/comment/story-comment/comment-block-item.tsx
> +      dispatch({
[c814743](https://github.com/readr-media/Sachiel/pull/857/commits/c814743383c2925708e0d6e8308b04ca8a53a98e)
更改函數命名避免誤會，這裡處理的應該是打開`modal`的時候初始化`useReducer`的值

2024-10-08 06:28 UTC, LinHeMa commented on packages/mesh/components/comment/mobile-comment-section/mobile-comment-modal-content.tsx
> +            {!!sortAndFilterComments(commentList).length && (
在[a5e4977](https://github.com/readr-media/Sachiel/pull/857/commits/a5e4977741402d28ed5fe7c8e5d62e22ef890393)處理

2024-10-08 06:29 UTC, LinHeMa commented on packages/mesh/components/comment/mobile-comment-section/mobile-comment-edit-drawer.tsx
> +      dispatch({
在[4c1cd1a](https://github.com/readr-media/Sachiel/pull/857/commits/4c1cd1a44124c92bab9e4b3689b0ec137fd7b889)進行處理

2024-10-08 06:29 UTC, LinHeMa commented on packages/mesh/components/comment/mobile-comment-section/mobile-comment-edit-drawer.tsx
在[14316c8](https://github.com/readr-media/Sachiel/pull/857/commits/14316c84148865fc8ac527e354264eeb5784a170)進行處理

2024-10-08 06:30 UTC, LinHeMa commented on packages/mesh/app/story/[id]/_components/stroy-comments-navigator.tsx
[2227756](https://github.com/readr-media/Sachiel/pull/857/commits/22277560b36130f7ede9c8655c81431d9346cd42)
刪除未使用的action

2024-10-08 06:30 UTC, LinHeMa commented on packages/mesh/context/comment-context.tsx
> +type EditDrawerShowType = '' | 'self' | 'other'
更改為`enum`
[0bb5c2c](https://github.com/readr-media/Sachiel/pull/857/commits/0bb5c2c4cae94479e02381eef653950223eed0f8)

2024-10-08 06:31 UTC, LinHeMa commented on packages/mesh/context/comment-context.tsx
> +  | { type: 'HIDE_EDIT_DRAWER' }
[9a6839e](https://github.com/readr-media/Sachiel/pull/857/commits/9a6839ec6002b933170b101118101b2557e390a6)
處理

2024-10-08 06:32 UTC, LinHeMa commented
> 提問：河馬使用的元件 import/export 方式是
> 
> // nav-item.tsx
> export const NavItem = () => {}
> // nav-list.tsx
> import { NavItem } from './nav-item'
> 其他人是
> 
> // nav-item.tsx
> const NavItem = () => {}
> export default NavItem

在[d908f80](https://github.com/readr-media/Sachiel/pull/857/commits/d908f80aac050151061ac2ce2542fd4bf783d862)
統一將component使用 `default export`

2024-10-08 09:37 UTC, LinHeMa commented on packages/mesh/app/actions/comment.ts
> +      return newCommentId
目前拿`latestCommentId`
```gql
query GetLatestAddedComment($memberId: ID!, $storyId: ID!) {
  comments(
    where: {
      member: { id: { equals: $memberId } }
      story: { id: { equals: $storyId } }
      is_active: { equals: true }
    }
    orderBy: { createdAt: desc }
    # only need 1st comment
    take: 1
  ) {
    id
  }
}
```
有篩自己的，所以理論上只會拿到自己的最新留言。
不太確定有沒有更好的做法

2024-10-09 03:08 UTC, caesarWHLee approved these changes
LGTM 👍 

lastCommentId 那塊需要再討論，可以之後再改一版就好，先讓 PM 可以測其他功能

2024-10-09 07:26 UTC, erase2004 approved these changes
Accepted

2024-10-09 07:26 UTC, erase2004 commented on packages/mesh/context/comment-context.tsx
`HTMLLIELEMENT` 用 `ELEMENT` 替代會比較泛用

2024-10-09 07:26 UTC, erase2004 commented on packages/mesh/app/story/[id]/layout.tsx
> +import { MobileCommentModalContent } from '@/components/comment/mobile-comment-section/mobile-comment-modal-content'
`mobile-comment-modal-content` 的 export 也調整為 export default function

2024-10-09 08:44 UTC, merged