feat: add subpage
readr-media/Sachiel pull request #860
Opened 2024-10-07 02:29 UTC by nihclil

## Changes
* 新增首頁分類子頁

2024-10-07 12:30 UTC, caesarWHLee requested changes
![圖片](https://github.com/user-attachments/assets/0a340df4-28b3-4f6a-9f8e-8850f233820b)
側欄寬度沒有拉滿

![圖片](https://github.com/user-attachments/assets/63432df1-2306-4dfe-aee8-84cf0c90a49b)
需要避免文章重複 (濾掉最多人精選的文章)

2024-10-07 12:30 UTC, caesarWHLee commented on packages/mesh/app/[slug]/page.tsx
> +  const slug = params.slug
從 slug 名稱無法快速得知是 categorySlug，建議改名以增加閱讀性

2024-10-07 12:30 UTC, caesarWHLee commented on packages/mesh/app/[slug]/page.tsx
> +        </NextLink>
上面這個目前已經搬到 `<LayoutTemplate/>` `nonMobileNavigation` prop 中，見 layout 中的 comment

2024-10-07 12:30 UTC, caesarWHLee commented on packages/mesh/app/[slug]/layout.tsx
> +          />,
回上一頁的 button 目前統一使用 `@/components/navigation/go-back-button`

2024-10-07 12:30 UTC, caesarWHLee commented on packages/mesh/app/[slug]/layout.tsx
> +      }}
`nonMobileNavigation` 目前已經整併到 `<LayoutTemplate/>` 中，格式跟 `mobileNavigation` 一樣

2024-10-07 12:30 UTC, caesarWHLee commented on packages/mesh/app/[slug]/layout.tsx
> +        title: title,
[nitpick]: `title: title` > `title`

2024-10-08 05:27 UTC, nihclil commented
避免文章重複、側欄寬度拉滿調整在 [73d6b6d](https://github.com/readr-media/Sachiel/pull/860/commits/73d6b6d49f7c97dbc31ef444d42be141a30009f9)、[77b1039](https://github.com/readr-media/Sachiel/pull/860/commits/77b103956eba6737f1ec21b31aac042cd1ecd6d5)

2024-10-08 05:27 UTC, nihclil commented on packages/mesh/app/[slug]/page.tsx
> +  const slug = params.slug
調整於 [df0de6f](https://github.com/readr-media/Sachiel/pull/860/commits/df0de6f8c013dc0e198d82797c6b9307b286d105)

2024-10-08 05:28 UTC, nihclil commented on packages/mesh/app/[slug]/page.tsx
> +        </NextLink>
調整於 [9efe317](https://github.com/readr-media/Sachiel/pull/860/commits/9efe31783bde6dc115c0038b97f15d2f6ca8bea1) ～

2024-10-08 05:28 UTC, nihclil commented on packages/mesh/app/[slug]/layout.tsx
> +          />,
調整於 [9efe317](https://github.com/readr-media/Sachiel/pull/860/commits/9efe31783bde6dc115c0038b97f15d2f6ca8bea1) ～

2024-10-08 05:28 UTC, nihclil commented on packages/mesh/app/[slug]/layout.tsx
> +      }}
調整於 [9efe317](https://github.com/readr-media/Sachiel/pull/860/commits/9efe31783bde6dc115c0038b97f15d2f6ca8bea1) ～

2024-10-08 05:28 UTC, nihclil commented on packages/mesh/app/[slug]/layout.tsx
> +        title: title,
調整於 [9efe317](https://github.com/readr-media/Sachiel/pull/860/commits/9efe31783bde6dc115c0038b97f15d2f6ca8bea1) ～

2024-10-08 10:38 UTC, caesarWHLee approved these changes
LGTM 👍

2024-10-08 10:38 UTC, caesarWHLee commented on packages/mesh/app/[slug]/layout.tsx
[Optional] 這邊其實可以改回 server component，利用 next.js server side cache 機制 `fetchCategoryInformation` 的結果可以用在 `layout.tsx` 和 `page.tsx` 上面

2024-10-08 11:08 UTC, nihclil commented on packages/mesh/app/[slug]/layout.tsx
感謝建議，但剛剛試了發現 GoBackButton 有用到 useRouter，必須在 client component 才能使用，所以應該只能這樣用了 ＱＱ

2024-10-08 11:41 UTC, merged